### ISSUE TITLE
Shift value of At annotation not handled correctly

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#1]
Currently, `ASMHelper#getAnnotationValue` iterates over `AnnotationNode.values`, assuming that the name of the value is followed by the value itself.

However, this isn't the case [for Enum values](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/util/ASMHelper.java#L466). Instead of an Enum member, the value is a two-element array containing a descriptor for the enum, and the member name.

For example, this annotation: `@At(value = "JUMP", shift = At.Shift.AFTER)`:

is stored like this: `[value, JUMP, shift, [Lorg/spongepowered/asm/mixin/injection/At$Shift;, BY]`

Because of this, using the `shift` parameter to the `At` annotation causes an error when the class is mixed it.

**Comment by Appu26J** [comment]
yo first issue
