### ISSUE TITLE
Allow a mixin to have any super class in the target's hierarchy

### ISSUE THREAD

**Issue by simon816** [SpongePowered/Mixin#10]
(Originally from https://github.com/SpongePowered/Mixin/pull/9)

There is currently no way for a mixin to have a super class that's not the direct super class of the target.
This is normally fine, but can become an issue when creating a mixin for targeting multiple classes.
Some of the target classes may have a different direct super class, but all have a class in common. However this common class is not the super class of all targets and so the mixin is not possible.

This issue requests that a mixin can have any super class that the target has, and allows for a common super class.

**Comment by Mumfrey** [comment]
@simon816  This should now work as expected, please test it and let me know how you get on.

**Comment by Mumfrey** [comment]
Bear in mind that multi-target mixins **must not** contain any `@Shadow`, `@Overwrite` or `@Inject` annotations.

**Comment by simon816** [comment]
Seems to work fine from some testing, however I have not thoroughly tested all cases but nothing has gone wrong so far.  I'll report back here if I find something failing.
