### ISSUE TITLE
Method overwrite conflict for lambda$null$0

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#100]
_Woo, another issue! However, don't worry: this time it does actually not break anything currently, so feel free to take your time to fix this._

So recently, (I think it actually started after I installed the a recent Java update) everytime I start the server from the IDE (or generally a SpongeVanilla JAR built by me), Mixin reports that it has a _"overwrite conflict"_ for a lambda method:

`Method overwrite conflict for lambda$null$0 in mixins.vanilla.json:network.MixinNetHandlerPlayServer, previously written by org.spongepowered.common.mixin.core.network.MixinNetHandlerPlayServer. Skipping method.`

I think the reason why it doesn't break anything currently, is that the code in the lambda is actually the same for both Mixin classes, even though they're used in different methods: [SpongeCommon mixin](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/network/MixinNetHandlerPlayServer.java#L356) and [SpongeVanilla mixin](https://github.com/SpongePowered/SpongeVanilla/blob/master/src/main/java/org/spongepowered/server/mixin/network/MixinNetHandlerPlayServer.java#L119).

I could imagine one of the reasons why the name is `lambda$null` is that it's a lambda in a lambda, although the names seem to generally differ between Java compiler versions because a) I'm pretty sure this wasn't always the case (and I haven't touched any of the mixins for a while), and b) the compiled versions produced by our Jenkins don't have this problem.

From what I've read the Java compiler does generally only choose unique names (which fails because these are 2 separate Mixin classes), [meaningful names are not guaranteed](http://mail.openjdk.java.net/pipermail/lambda-dev/2014-October/012126.html). Therefore it might make sense to somehow remap the method names in case of conflict, or just generally remap _all lambda names_ to prevent problems arising from this if the lambdas would actually have 2 different method bodies but the same name.

For reference, here is my Java version (basically it's the latest OpenJDK 8 version currently iirc):

```
openjdk version "1.8.0_72"
OpenJDK Runtime Environment (build 1.8.0_72-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
```

**Comment by Mumfrey** [comment]
I cannot reproduce this with JDT or hotspot, does this only happen with OpenJDK?

**Comment by Mumfrey** [comment]
All I need to know is whether these methods are decorated with a synthetic marker.

**Comment by Minecrell** [comment]
It's possible that it only happens with OpenJDK, as I said I think it is also only since I upgraded from u66 to u72, so that might cause some differences.

Seems like it is synthetic though:
```
    private static void lambda$onProcessChatMessage$1(org.spongepowered.api.event.message.MessageChannelEvent.Chat event, org.spongepowered.api.text.Text text);
        Flags: PRIVATE, STATIC, SYNTHETIC
        Code:
                  linenumber      119
               0: aload_0         /* event */
               1: invokeinterface org/spongepowered/api/event/message/MessageChannelEvent$Chat.getChannel:()Ljava/util/Optional;
               6: aload_1         /* text */
               7: invokedynamic   BootstrapMethod #1, accept:(Lorg/spongepowered/api/text/Text;)Ljava/util/function/Consumer;
              12: invokevirtual   java/util/Optional.ifPresent:(Ljava/util/function/Consumer;)V
              15: return         
    
    private static void lambda$null$0(org.spongepowered.api.text.Text text, org.spongepowered.api.text.channel.MessageChannel channel);
        Flags: PRIVATE, STATIC, SYNTHETIC
        Code:
                  linenumber      119
               0: aload_1         /* channel */
               1: aload_0         /* text */
               2: invokeinterface org/spongepowered/api/text/channel/MessageChannel.send:(Lorg/spongepowered/api/text/Text;)V
               7: return     
```
