### ISSUE TITLE
Support accessing method arguments of the enclosing method in a @Redirect

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#101]
Basically I was wondering if there is a way to make this Mixin simpler with a redirect: https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/command/MixinCommandWorldBorder.java#L41-L58

It's supposed to modify the returned world border respecting the world of the sender, instead of always using the same one. The method it injects in looks like this:

```java
    public void processCommand(ICommandSender sender, String[] args) throws CommandException
    {
        if (args.length < 1)
        {
            throw new WrongUsageException("commands.worldborder.usage", new Object[0]);
        }
        else
        {
            WorldBorder worldborder = this.getWorldBorder();
            // blah
        }
    }
```

Normally I'd simply use an `@Redirect` here, but this is not possible because I also need to access the arguments that were given to the enclosing method (the sender). For that, currently I always need to save the sender temporarily to a field so I can access it in the `@Redirect` (or here the `@Overwrite`). I assume I could also use an `@ModifyVariable` and modify the worldborder directly after it has been set but that's not the perfect solution either in my opinion.

That mixin could be easily simplified if there was like an additional option to give the enclosing method arguments similar to a normal `@Inject` also to the `@Redirect`, so for example you would have like:

```java
@Redirect(method = "processCommand", at = @At(...), includeArgs = true)
private void onGetWorldBorder(CommandWorldBorder this$0, ICommandSender sender, String[] args) {
    return sender.getEntityWorld().getWorldBorder();
}
```

Is there any chance something like this could be implemented? Or I'd also appreciate other suggestions to improve this mixin.

**Comment by Mumfrey** [comment]
You already can, read the javadoc.

**Comment by Minecrell** [comment]
Oh, so I would just need to add them without specifying any option anything?

**Comment by Mumfrey** [comment]
Correct, the [logic is basically](https://github.com/SpongePowered/Mixin/blob/initphase/src/main/java/org/spongepowered/asm/mixin/injection/invoke/RedirectInjector.java#L185-L194)

* Is the signature the same as the redirect? If yes, do the thing
* If not, check if signature is same as redirect plus args of target? If yes, do the thing with the other things.
* If all else fails, throw teddies out of pram.

**Comment by Minecrell** [comment]
Well, that works just fine... I was checking the options for the `@Redirect` annotation but not the javadoc of the `@Redirect` annotation directly. Thanks for the info, good to know =)

**Comment by Mumfrey** [comment]
I actually take pains to document my stuff as much as I am physically able. If in doubt, read the javadoc first. Complete [javadoc always available to browse on Jenkins](http://jenkins.liteloader.com/job/Mixin/javadoc/).
