### ISSUE TITLE
Injecting into a method fails if the target method is later overwriten

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#103]
Since injectors were changed to run in two passes, an issue was created when attempting to overwrite a method which was previously targeted by an injector. This results in an error like this: http://hastebin.com/cukotagiqi.avrasm.  To reproduce it, run SpongeForge prior to [this commit](https://github.com/SpongePowered/SpongeForge/commit/0595387a25f1e5753118f7bbd54e20ae12fb3a25) with BungeeCord `ip-forwarding on,` and do a `/sponge audit`.

The issue seems to be this:

In the `MAIN` pass, method replacements get run. This means that an ostensibly higher-priority mixin or config containing an overwrite ends up running *before* injections. Because of this, the `@MixinMerged` annotation gets added, causing the injector to error in the `PREINJECT` phase.

**Comment by Mumfrey** [comment]
Well that sucks, I'll look at that tomorrow. Why is the method being overwritten **and** injected though? That seems like a kind of sub-optimal situation.

**Comment by Mumfrey** [comment]
You can now resolve this by making the other mixin a higher priority.
