### ISSUE TITLE
Mixin crashes when empty "mixins" element left out in json

### ISSUE THREAD

**Issue by CrystalMageX** [SpongePowered/Mixin#105]
SpongeVanilla crashes with the following error: http://pastebin.com/6y6ZniPY when the `mixins` attribute is missing in `mixings.vanilla.json`: http://pastebin.com/FnP9dhLy

This does not happen when `mixins` is added as an empty list: http://pastebin.com/KrwtnqDL

Mixin should detect the null `mixinClasses` field, and handle it.

**Comment by Mumfrey** [comment]
`mixinClasses` is allowed to be null, it was just a typo in the debug message.
