### ISSUE TITLE
Mixin incorrectly reports write access detected to changes made to collections

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Mixin#106]
``    @Shadow @Final private Set<Long> droppedChunksSet = Collections.<Long>newSetFromMap(new ConcurrentHashMap());
``

If I add new long values to that set, Mixin will report:

``[10:06:19] [Server thread/ERROR] [mixin]: Write access detected to @Final field droppedChunksSet:Ljava/util/Set; in mixins.vanilla.json:world.gen.MixinChunkProviderServer::<init>
``

This should check by reference imo.

**Comment by Mumfrey** [comment]
Derp, it's the field initialiser.

**Comment by Mumfrey** [comment]
Just out of interest, why use `@Final` when you're including the initialiser?

**Comment by Zidane** [comment]
@Mumfrey 

That was by mistake, this may not be a bug (never thought about that...)

**Comment by Zidane** [comment]
Nothing to see here, move along...

**Comment by Mumfrey** [comment]
Well, it's kind of a bug because the message should be different under these circumstances. It should effectively say "this shadow should be `final` rather than `@Final`".

**Comment by Zidane** [comment]
Ah, you can change this for that if you like. Still me being silly either way hehe.

**Comment by Mumfrey** [comment]
The warning is misleading, causing you to open this issue, ergo it should be changed to indicate the actual issue.
