### ISSUE TITLE
How do I change the compatibility level in a dev environment?

### ISSUE THREAD

**Issue by luacs1998** [SpongePowered/Mixin#109]
When I attempt to start the game from within IntelliJ IDEA, I get the following error:

>org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unsupported mixin class version 51

I've worked around this in production by adding the MixinCompatibilityLevel jar manifest item, but how would I do this in my development environment?

**Comment by kashike** [comment]
`-Dmixin.env.compatLevel=JAVA_8`

**Comment by luacs1998** [comment]
Thanks.
