### ISSUE TITLE
Ability to redirect constant loading

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#119]
Given the following byte code:
![bytecode](http://puu.sh/ovXJe/ae9d0f8779.png)

I know it'd be fairly simple to either add a new type of redirect for constant loading, or something thereof to inject/modify the constants being loaded to the stack.

While it would probably involve injecting in awkward positions, it should certainly be feasible.

**Comment by Mumfrey** [comment]
You are correct, it wouldn't be too hard to have `@Redirect` also work for `LDC` insns.

**Comment by Mumfrey** [comment]
Closed via f19f4deac6c45e0e1260e458634b0c52d6f772e5
