### ISSUE TITLE
Field descriptor not remapped when generating refmap

### ISSUE THREAD

**Issue by killjoy1221** [SpongePowered/Mixin#125]
This wouldn't be an issue using forge, but it breaks when using notch names.

Here is the [generated refmap](https://gist.github.com/killjoy1221/524667feb2513ff99524a6a7fc582f64) that is made. The first one (`bipedLeftArmwear:ModelRenderer`) is a field reference. The type of it is not obfuscated in the notch names. It should be `Lbkm;`

**Comment by Mumfrey** [comment]
That's odd, it's [supposed to remap the class](https://github.com/SpongePowered/Mixin/blob/initphase/src/ap/java/org/spongepowered/tools/obfuscation/ObfuscationManager.java#L169) in field references, it's possible that [getObfClass](https://github.com/SpongePowered/Mixin/blob/initphase/src/ap/java/org/spongepowered/tools/obfuscation/ObfuscationManager.java#L150) isn't returning the correct data. I'll look into it.
