### ISSUE TITLE
@Redirect method call in constructor

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#128]
I know that `@Redirect`s (or other modifications) can't be used in constructors, but I'm kind of facing a situation where I think it is necessary (unless I write a custom transformer):

This is the class (on 1.9.4):

```java
package net.minecraft.server.management;

public class PlayerChunkMapEntry
{
    public PlayerChunkMapEntry(PlayerChunkMap p_i1518_1_, int chunkX, int chunkZ)
    {
        this.playerChunkMap = p_i1518_1_;
        this.pos = new ChunkPos(chunkX, chunkZ);
        // I want to redirect the loadChunk method call to another method
        this.chunk = p_i1518_1_.getWorldServer().getChunkProvider().loadChunk(chunkX, chunkZ);
        // E.g. the line above is supposed to look like
        // Could be also additionally wrapped in a @Redirect method, that does not matter
        this.chunk = AsyncChunkLoader.queue(p_i1518_1_.getWorldServer().getChunkProvider(), chunkX, chunkZ, this);
    }
}
```

As the comment already explains, I want to redirect the `loadChunk` method call to another method, without calling `loadChunk`. Specifically, I want to redirect it to another method that loads the chunk asynchronously, that's why it is important the original method is not called because it still exists as the synchronous variant.

I've also considered simply replacing the `loadChunk` method using an `@Overwrite` or similar but that's not really an option either because it also has several other usages that should stay unmodified.

Any suggestions?

**Comment by Mumfrey** [comment]
You can use `@Redirect` in constructors. The restriction is on the use of `@Inject` which must be at `RETURN` in a constructor, but `@Redirect` is fine.

**Comment by Minecrell** [comment]
I actually tested that and got an error, but I didn't read it careful enough, it wasn't telling me I can't use it on a constructor but just that my signature is wrong...

Thanks, it works now! :S
