### ISSUE TITLE
Add a general-purpose InjectionPoint with similar semantics to ModifyConstant

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#129]
Given the following injection:

``` java

    @Inject(method = "tickUpdates", at = @At(value = "INVOKE_STRING", target = PROFILER_SS, args = "ldc=cleaning"))
    private void onTickUpdatesCleanup(boolean flag, CallbackInfoReturnable<Boolean> cir) {
        if (!this.isRemote) {
            this.timings.scheduledBlocksCleanup.startTiming();
        }
    }
```

Currently, the output of the target point is along the lines of:

```

   L9
    LINENUMBER 689 L9
   FRAME SAME
    ALOAD 0
    GETFIELD net/minecraft/world/WorldServer.theProfiler : Lnet/minecraft/profiler/Profiler;
    LDC "cleaning"
    INVOKEVIRTUAL net/minecraft/profiler/Profiler.startSection (Ljava/lang/String;)V
```

While adding the injection type is intended to work like this, with `@ModifyConstant` injection added recently, I've had thoughts that this sort of injection could be cleaned up in some way. If possible, I'd imagine the injector would still remain the same in style, but significantly reduced in the values required. 

Thinking about it more, if used in combination with `@Constant`, the `@At` shouldn't require any `target` so long the constant string is used, and with `ordinal`s, it'd still be a matter of finding the `ldc` of the desired constant.

Similarly, one could argue that the injector could be transformed to use something along the lines of `LOAD_CONSTANT`, and optionally of course, use `target` if necessary.

**Comment by Mumfrey** [comment]
We talked about this and it's a good idea, consider it accepted but I will process more pressing features and improvements first.
