### ISSUE TITLE
Allow targeting of (at-runtime) public classes through Mixin#targets

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#134]
Currently, Mixin throws an exception if a public class is targeted through `@Mixin#targets` (instead of `@Mixin#value`. However, this creates an issue when mods such as [CodeChickenCore](https://github.com/SpongePowered/SpongeForge/issues/681) use an access transformer to make these classes at runtime.

Since it's inconvenient to have to make public yourself any class which might have an AT applied by a mod, it would be nice if the at-runtime check were removed, leaving only the compile-time AP check.

**Comment by Zidane** [comment]
@Mumfrey 

Status update on this? Just about everyone uses NEI and SF is breaking a lot of modpacks...

**Comment by Mumfrey** [comment]
Fix is bundled with other changes I'm making at the moment, it wasn't indicated that this was a high priority.
