### ISSUE TITLE
Constraints for annotations other than Overwrite

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#135]
In my code I have a few `@Injects` and `@Redirect`s that are possibly very sensitive to changes in Minecraft/Forge code (mostly redirects with high specified ordinal, for example 6 and 7 in `CommandFill` mixin). Breakages could be possibly silent and hard to detect so constraints would be very useful here.

**Comment by Mumfrey** [comment]
Not a bad shout actually, though injectors are generally easier to audit than overwrites hence adding the constraints mechanism to overwrites in the first instance. I think this is a pretty good idea though since it "can't hurt" to support this for injectors too,
