### ISSUE TITLE
Java Agent Not working properly with latest Mixin

### ISSUE THREAD

**Issue by bloodmc** [SpongePowered/Mixin#136]
The following gist shows the response after adding a simple 'System.out.println' line to a inject method in MixinChunk 

https://gist.github.com/bloodmc/2b8d98b7bb3fa452388558a409d60e10

Everything works fine in Mixin 0.5.7 which is what im using for 1.8.9 but doesn't work in 1.10.2 using Mixin 0.5.11.

**Comment by Mumfrey** [comment]
Ah yes, the check was added so we could detect the error condition with the PREINIT mixins when some other mod has prematurely classloaded them. Of course in this situation *it was us*!

Easy to fix, watch this space.
