### ISSUE TITLE
Support other mapping formats in the AP

### ISSUE THREAD

**Issue by asiekierka** [SpongePowered/Mixin#141]
In order to make the Mixin library a more general-purpose one, it would be useful to support other mapping formats/schemes than MCP.

I have identified the following steps necessary to accomplish this goal (with an attempt at ordering them):

- [ ] Refactor SrgContainer into an interface, making SrgContainer its implementation (also, rename SrgField/SrgMethod to FieldEntry/MethodEntry)
- [ ] Refactor the AP's very hacky mapping writing system into a mapping writer interface
- [ ] Look into making ObfuscationType less hardcoded in terms of mapping types/namings
- [ ] Provide configuration options for enforcing custom mapping readers/writers, as well as passing additional parameters to them

**Comment by Mumfrey** [comment]
As we discussed in IRC, I'm happy to undertake these changes once I am back in the UK.
