### ISSUE TITLE
Class overwrite issue with Ars Magica 2

### ISSUE THREAD

**Issue by ElvenChaos** [SpongePowered/Mixin#147]
_Not sure if this belongs in this issue tracker or Sponge Forge's one, or even if this belongs with AM2's tracker._
_Mirror to AM2's issue instance: https://github.com/Growlith1223/ArsMagica2/issues/17_

With AM2 and Sponge Forge installed, Mixin is throwing an error about a class it is trying to tweak being loaded prematurely.
Paste of relevant fml-server-latest: http://pastebin.com/UdnkCBh7

MC 1.10.2
Forge 2122
Sponge 1874
AM2 1.5.0_6

**Comment by Mumfrey** [comment]
The is an issue with the mod in question. If you wish to track it on Sponge's end then do so via the SpongeForge tracker since this is Mixin raising an error due to environment and not actually an issue with Mixin itself.
