### ISSUE TITLE
When running with -Dmixin.checks.interfaces=true mixin reports unimplementd interface methods in abstract classes

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#150]
I know it's only debug/additional checking option so it's very low priority, but I donn't think it's correct, and I don't think it would be very hard to fix it (or is it hard?)

In my case, I have interface for World with one method that needs different implementation for client and server world, so it's not implemented in World mixin. World is abstract class, so unimplemented methods aren't an issue here, but mixin still shows information about it when `-Dmixin.checks.interfaces=true` is used.

**Comment by Mumfrey** [comment]
It's kind of intentional, since of course Mixins are generally supposed to be declared `abstract` anyway so it can't really suppress those checks for abstract classes because it would suppress everything in most cases. I could add an annotation (or maybe just support `@SuppressWarnings`) so that certain classes could be ignored but in general the processor can't ignore the warnings without some additional info from the author.

**Comment by Mumfrey** [comment]
Oh I misunderstood. You mean if the **target** class is `abstract`? Yeah that could be easily suppressed.

**Comment by JBYoshi** [comment]
I intentionally added warnings for abstract classes some time ago. It was to prevent a situation like this:
```java
// Base game
public abstract class FooBase {
    public void runFoo() {}
}

public class FooImpl extends FooBase {}

// Mod 1
public interface IMixinFoo {
    void runMod();
}

@Mixin(FooBase.class)
public abstract class MixinFooBase implements IMixinFoo {
    @Overwrite
    public void runFoo() {
        runMod();
    }
}

@Mixin(FooImpl.class)
public abstract class MixinFooImpl extends MixinFooBase {
    @Override
    public void runMod() {
        System.out.println("Foo");
    }
}

// Mod 2
public class ModFoo extends FooBase {
    // No mixins for this class
}
```
In this case, if someone tries to call `new ModFoo().runFoo()`, the game will crash, because there is no implementation of `go()` for `ModFoo`.

**Comment by Barteks2x** [comment]
That's a good point, I guess I was just thinking in terms of the world class that I don't think anyone sane will ever extend.

**Comment by Mumfrey** [comment]
Then the answer is just to selectively suppress the warnings to give control to the mixin author, at least you could control the output then.

However in the case you're suggesting, it would make more sense to actually fix the error by actually mixing in implementations for the methods in question which just manually throw `NotImplementedException` or `NoSuchMethodError`

**Comment by Barteks2x** [comment]
That looks like a good solution. 
Implementing this method in World also means that the check is disabled for implementations, but this is only one method and changes in vanilla can't possibly break it in any way so it's not a problem here.
