### ISSUE TITLE
@Implements annotations are not handled by the AP

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#151]
The `@Implements` annotation is usually used for implementing non-obfuscated interfaces, such as from SpongeAPI. However, it can become necessary to use it for obfuscated interfaces (such as `IMerchant`) when mixing obfuscated interfaces onto other interfaces using an interface mixin.

In this case, we need to mix `IMerchant` onto the the SpongeAPI interface `Merchant`. However, due to a conflict with two `getWorld` methods, it's necessary to soft-implement `IMerchant`, in order to be able to call the original `getWorld` in a default method (The original `getWorld` must be made accessible through implemening the interface, rather than `@Shadow`ing, as it exists in a parent interface). Currently, the only solution is to create an intermediate mixin for `Locateable` (the interface containing `getWorld`), whose only purpose is to prefix-shadow the offending mehod.

All of this is necessary due to fact that the annotation processor does not currently generate SRGs for soft-implemented methods. Adding this feature would allow a much cleaner solution to the above issue.

**Comment by Mumfrey** [comment]
I see your issue, `@Implements` is not currently processed by the processor but will need to be remapped for this purpose. The class name in the `@Implements` itself will also need to be remapped for when the target environment is not Searge mappings.

**Comment by Mumfrey** [comment]
So I forgot that the `@Interface` annotation doesn't support "soft targets" so it actually makes it a little simpler to handle. Should be able to close this quite soon.

**Comment by gabizou** [comment]
@Mumfrey so, `@Interface(iface = IMerchant.class, prefix = "imerchant$", remap = ALL)` would be what I'm looking to do (yes, I know the default is ALL anyways, but just to be sure).

**Comment by Mumfrey** [comment]
Essentially yes, I added `ONLY_PREFIXED` so that in the unlikely event of there being an "intrinsic" member in the interface which matches exactly, it won't try to remap it. This remap is a bit brute-force though so I'm hoping it will be sufficient, the only alternative is having to annotated individual members, which I don't really want to do for obvious reasons.
