### ISSUE TITLE
Can't reference classes that are not present during compile time in @Mixin targets

### ISSUE THREAD

**Issue by CrushedPixel** [SpongePowered/Mixin#152]
I'd like to Mixin a class from a different mod that may or may not be available during runtime, but certainly not during compile time.

In my case, I'd like to Mixin the class `shadersmod.client.ShadersRender` from Optifine/Shaders Mod. As the class is not existent during compile time, I'm using the `targets` attribute of the `@Mixin` annotation to reference it.

However, when compiling, the following error occurs:

```
.../replay-workspace/build/sources/main/java/com/replaymod/compat/shaders/mixin/MixinShadersRender.java:12: error: Mixin target shadersmod/client/ShadersRender could not be found
@Mixin(targets = "shadersmod/client/ShadersRender", remap = false)
^
```

Here's my full Mixin class:

```
@Mixin(targets = "shadersmod/client/ShadersRender", remap = false)
public abstract class MixinShadersRender {

    private final Minecraft mc = Minecraft.getMinecraft();

    @Inject(method = "renderHand0", at = @At("HEAD"), cancellable = true)
    private void disableRenderHand0(EntityRenderer er, float partialTicks, int renderPass, CallbackInfo ci) {
        RenderHandEvent renderHandEvent = new RenderHandEvent(mc.renderGlobal, partialTicks, renderPass);
        if (FMLCommonHandler.instance().bus().post(renderHandEvent)) {
            ci.cancel();
        }
    }

}
```

It would be nice to be able to target classes that are not present during compilation in a Mixin.

**Comment by Mumfrey** [comment]
Per our discussion on IRC, I am more than happy to accommodate this so I will look into it and provide a fix as soon as I am able.

**Comment by Mumfrey** [comment]
This is now possible by decorating your mixin with the new `@Pseudo` ([Javadoc](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/Pseudo.html)) annotation.
