### ISSUE TITLE
Insufficient maximum stack size when using constructor redirection in a simple method

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#158]
I've changed the `create` method of [my test class](https://gist.github.com/Minecrell/a56ab40b48bf6884f0c64080f4fd6b3b) to a simple method with only a single constructor invocation:

```java
public static TestClass95 create() {
    System.out.println("Test");
    return new TestClass95("a");
}
```

When I run Mixin with the `-Dmixin.debug=true` or `-Dmixin.debug.verify=true` option I get an error from ASM's verifier, complaining about an insufficient maximum stack size:

```java
Error at instruction 13: Insufficient maximum stack size. create()Lnet/minecrell/test/TestClass95;
00000  :   :    L0
00001  :   :     LINENUMBER 16 L0
00002  :   :     GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
00003  : R  :     LDC "Test"
00004  : R R  :     INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/String;)V
00005  :   :    L1
00006  :   :     LINENUMBER 17 L1
00007  :   :     LDC "a"
00008  : R  :     INVOKESTATIC net/minecrell/test/TestClass95.redirect$onCreateTestClass95$zza000 (Ljava/lang/String;)Lnet/minecrell/test/TestClass95;
00009  : R  :     DUP
00010  : R R  :     IFNONNULL L2
00011  : R  :     NEW java/lang/NullPointerException
00012  : R R  :     DUP
00013  : R R R  :     LDC "@Redirect constructor handler net/minecrell/test/TestClass95::redirect$onCreateTestClass95$zza000 returned null for net.minecrell.test.TestClass95"
00014 ?    :     INVOKESPECIAL java/lang/NullPointerException.<init> (Ljava/lang/String;)V
00015 ?    :     ATHROW
00016  : R  :    L2
00017  : R  :     ARETURN
```

It is working correctly when I remove the verify option. Could that be a bug in ASM's `CheckClassAdapter`?

**Comment by Mumfrey** [comment]
No I think it's correct, I think what's happening is that when I originally wrote it, I just created and threw an exception. I later added the actual message to be thrown and forgot to increase the stack size for it, but likely didn't notice because it's easy for off-by-one stack size calcs to be hidden if the stack in the target method is big enough already.
