### ISSUE TITLE
Invalid SMAP if two Mixins have the same simple class name

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#159]
The source map implementation [stores all strata mapped by their filename](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/transformer/meta/SourceMap.java#L196). Currently, Mixin classes are inserted using their [simple class name](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/transformer/MixinTargetContext.java#L175) ([using `mixin.getName()`](http://jenkins.liteloader.com/job/Mixin/javadoc/org/spongepowered/asm/mixin/extensibility/IMixinInfo.html#getName())).

This causes problems if two Mixins have the same simple class name. As an example: `MixinWorld` in SpongeCommon would be mapped to `world.MixinWorld`. Since `world.MixinWorld` is already mapped to `MixinWorld` in SpongeForge it will use the same SMAP stratum/file for two Mixins. Consequently, all lines in SpongeCommon's mixin will be assigned to the SpongeForge Mixin.

It should be mapped to a name unique to the Mixin class (e.g. [the full class name using `mixin.getClassName()`](http://jenkins.liteloader.com/job/Mixin/javadoc/org/spongepowered/asm/mixin/extensibility/IMixinInfo.html#getClassName())) to ensure a separate entry is added for each Mixin class.

**Comment by Mumfrey** [comment]
Given that (I think) the stratum name is basically irrelevant, I can probably just use the fq class name ya. Or possibly store all the words to bohemian rhapsody in a list and use successive words as the strata names might be fun.
