### ISSUE TITLE
Gradle Build Failure

### ISSUE THREAD

**Issue by mcaustin1** [SpongePowered/Mixin#160]
When I run the gradle build command inside the root folder of Mixin it gives me a build failed with an exception. It says its in the build.gradle file at line 199.

Error, http://pastebin.com/NtT53HLy

**Comment by Mumfrey** [comment]
You're using the wrong gradle version.

**Comment by liach** [comment]
So won't you support Gradle 3.+?

**Comment by Mumfrey** [comment]
It's not a case of "won't", there's just no need to do so.

**Comment by mcaustin1** [comment]
@Mumfrey What version of gradle do I have to use?

**Comment by kashike** [comment]
2.8 - You can use the gradle wrapper and avoid version issues.
