### ISSUE TITLE
Applying to Source Code

### ISSUE THREAD

**Issue by Maxqia** [SpongePowered/Mixin#161]
Is there anyway we could apply Mixins to jars and have them decompiled for use in deobf enviroments so we don't have to have IMixin interfaces? It be kind of like how Forge does it with their patches (setupDecompWorkspace). I'd assume it has something to do with SpecialSource... (for example code I guess)

**Comment by Mumfrey** [comment]
That's really not what Mixins are designed for. The whole point of Mixins is that they are adaptable and flexible at *runtime*, applying them in a static mode is really only useful if you want a kind of declarative DSL for making offline patches, which is okay I guess but kind of defeats the whole object. Fabric had a use-case for this but came up with their own solution to actually pull it off.

> so we don't have to have IMixin interfaces

But **why**? IMixin interfaces are a powerful and flexible way to achieve this functionality.

> It be kind of like how Forge does it with their patches (setupDecompWorkspace).

You're thinking of patches, Mixins are not patches, they're mixins. If you want to do patches, use patches.

> I'd assume it has something to do with SpecialSource... (for example code I guess)

You can't just pick random words that you don't understand and throw them into a sentence and hope for the best, it just leads to non sequitur statements like this.

**Comment by Maxqia** [comment]
IMO IMixin interfaces are a solution to a problem that shouldn't exist. Mixined classes should be available during compile time. I mentioned SpecialSource there because it has a lot of useful code for scanning a jar for all it's bytecode.
