### ISSUE TITLE
InjectLocals for Redirects

### ISSUE THREAD

**Issue by Maxqia** [SpongePowered/Mixin#163]
There's been many times where I had to have a Redirect and Inject method with external variables to pass the variables to the Redirector, can we also have a InjectLocals for Redirects?

**Comment by Barteks2x** [comment]
Is this what you mean? https://github.com/SpongePowered/Mixin/issues/110

**Comment by Mumfrey** [comment]
Already answered by #110.

**Comment by Maxqia** [comment]
Yeah, thanks!
