### ISSUE TITLE
Array access redirect

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#164]
Basically I want to turn my Column class into a Chunk mixin (this will allow to make compatibility with sponge much easier), and the only thing that makes it close to impossible is that I can't redirect access to ExtendedBlockStorage array to my own method.

For example with code like this:

```java
    public int getLightFor(EnumSkyBlock p_177413_1_, BlockPos pos)
    {
        int i = pos.getX() & 15;
        int j = pos.getY();
        int k = pos.getZ() & 15;
        ExtendedBlockStorage extendedblockstorage = this.storageArrays[j >> 4];
        return /*complicated logic here */;
    }
```

I want to be able to return different ExtendedBlockStorage, without any array access. 

In this example case it can be worked around by redirecting BlockPos.getY() but in cases like `public IBlockState getBlockState(final int x, final int y, final int z)` I would need to modify method argument, which may have unintended side effects when something else modifies that method. 

And working around that issue is much less clear and is more fragile than redirecting array access.

**Comment by Mumfrey** [comment]
Okay that makes sense, `@Redirect` can already redirect field accesses so really this just amounts to an enhancement of an existing feature.
