### ISSUE TITLE
Throw error if overwritten method has invalid access modifiers

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#167]
Currently, Mixin will always replace the target method of an `@Overwrite`, even if it has incompatible access modifiers. Example:

The original method is defined as:

```java
public boolean init() throws IOException;
```

Now I can write the following Mixin:

```java
@Mixin(DedicatedServer.class)
public class MixinDedicatedServer {
    @Overwrite
    private static boolean init() throws IOException {
        return false;
    }
}
```

At runtime, Mixin will happily replace the original method with my `private static` version. Since the method is no longer public (and also static now), it will throw an error at runtime:

```
[17:39:34] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AbstractMethodError: net.minecraft.server.MinecraftServer.init()Z
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:514) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

Mixin should verify the method access modifiers and fail early when the Mixin is applied to prevent potential errors later at runtime.

**Comment by Mumfrey** [comment]
That's a bloody good point.

**Comment by Mumfrey** [comment]
FYI `@Overwrite` doesn't signify that a method will overwrite - any method with the same name as a target method will do that. `@Overwrite` is just needed for *obfuscated* methods so that the AP knows to rename them, so this check actually needs to be made for all member methods.

**Comment by Minecrell** [comment]
@Mumfrey 
Right. Personally I think it would be useful if there was a marker annotation for methods which are supposed to replace a method in the target classes (even if no obfuscation is needed) because `@Overwrite` also comes with the `@author` and `@reason` Javadoc checks, as well as a check that the target method actually exists. It can be quite hard to keep a stray, unused method like https://github.com/SpongePowered/SpongeVanilla/blob/bleeding/src/main/java/org/spongepowered/server/mixin/chunkio/MixinMinecraftServer_ChunkIO.java#L34-L40  up to date.

**Comment by Mumfrey** [comment]
That is a separate issue... not relevant here.

**Comment by Minecrell** [comment]
@Mumfrey Right, I'll open a separate issue for that when I find the time.
