### ISSUE TITLE
Cannot shadow Enum based methods

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#168]
To put it plainly, a Mixin class cannot shadow Enum based methods, such as `name()`.

**Comment by Mumfrey** [comment]
This is correct per the contract of shadows. Shadows can only shadow methods in the target class, and `name()` exists in the superclass `Enum`.

To access `Enum` members in an enum mixin, simply cast via object: eg. `((Enum)(Object)this).name();`
