### ISSUE TITLE
Wildcard Operator

### ISSUE THREAD

**Issue by mcjp78** [SpongePowered/Mixin#170]
Hi,
When developing a lot of mixins it becomes tedious to register each one within the mixin config, especially if every class within the parent package is a mixin. Therefore I suggest an everything (*) operator.

**Comment by Barteks2x** [comment]
I think it looks like something so obvious that if it was easy to do it would be already there. So there must be some technical reason why it's not done (especially when you can't use any package that contains mixins for any other classes).

But if it's possible, I would also like to see that feature.

**Comment by Mumfrey** [comment]
I am on holiday at the moment so there's not really an opportunity to explain the technical ins and outs of why this isn't feasible, but it's not going to happen. However there is a feature request for mcdev for this which may automate the process in the future.
