### ISSUE TITLE
Resolve obfuscation mappings of methods defined in super interfaces

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#171]
This is very similar to #33, except that it doesn't apply to a method defined in a super class, but rather to a method defined in a super interface.

The problem can be reproduced using a mixin when referencing the `getName()` call in `CommandBase.checkPermission`:

```java
public boolean checkPermission(MinecraftServer server, ICommandSender sender)
{
    return sender.canUseCommand(this.getRequiredPermissionLevel(), this.getName());
}
```

The `getName()` call is compiled to a method with the descriptor `net.minecraft.command.CommandBase.getName()Ljava/lang/String;` but it is actually only defined in the `ICommand` super interface of `CommandBase`. If we attempt to `@Redirect` the call to `this.getName()`, Mixin is unable to locate an obfuscation mapping at compile time:

```java
@Mixin(CommandBase.class)
public class MixinCommandBase {
    
    @Redirect(method = "checkPermission", at = @At(value = "INVOKE", 
            target = "Lnet/minecraft/command/CommandBase;getName()Ljava/lang/String;"))
    private String onGetName(CommandBase command) {
        return command.getName();
    }

}
```

```
MixinCommandBase.java:11: warning: Cannot find method mapping for @At(INVOKE.<target>) 'Lnet/minecraft/command/CommandBase;getName()Ljava/lang/String;'
```

As a fix for #33, the Mixin annotation processor walks up the hierarchy of the class to locate an obfuscation mapping. However, it doesn't check interfaces currently. In this case, the obfuscation mapping for `getName()` is only defined on the super interface `ICommand`.

**Comment by Mumfrey** [comment]
I'm on holiday at the moment I will look at this when I'm back.
