### ISSUE TITLE
Awesome diagrams

### ISSUE THREAD

**Issue by OsipXD** [SpongePowered/Mixin#175]
Hello!
What you use to draw that awesome UML diagrams? I am currently writing a coursework at the Institute, and it would be beautiful to draw fancy UML sequence and class diagrams.

Thank you in advance. And I apologize for the offtopic

**Comment by kashike** [comment]
[Visio](https://products.office.com/en-ca/visio/flowchart-software)

**Comment by ewized** [comment]
My school briefly used this. https://www.bluej.org/index.html aside from that I also heard that https://www.lucidchart.com is pretty good also.

**Comment by DemonWav** [comment]
Nothing compares to Visio.

**Comment by OsipXD** [comment]
Thank you. (I assumed this)
