### ISSUE TITLE
`remap = false` on `@Mixin` annotation doesn't seem to affect remap in `@At`

### ISSUE THREAD

**Issue by mikroskeem** [SpongePowered/Mixin#177]
I get [bunch of warnings](https://paste.nightsnack.cf/oyakaxuvip.rb) about missing mappings for `@At`, even though I have `remap=false` for `@Mixin` annotation.

Not sure if that is intended.

(Some) [Code is here](https://paste.nightsnack.cf/iwiwucofod.java), if anyone wants to take a closer look.

**Comment by Mumfrey** [comment]
It could be that the `remap=false` on the class itself isn't propagating down the processing chain to the At handler, most likely broke it when I refactored some of the AP internals a while ago. It shouldn't affect any output and you can safely ignore the warnings if your target is not remapped anyway.

**Comment by mikroskeem** [comment]
Yes of course I can ignore these warnings, because they do not affect anything for me really. I opened an issue to point out that those warnings are very likely caused by a bug, and it would be nice to get it fixed :)

**Comment by Mumfrey** [comment]
Available in 0.6.9, it's now also possible to selectively *enable* `remap` on annotations even if `remap` is false at the `@Mixin` level. I'm not sure if this has any specific utility but it makes sense that if the value is explicitly specified then the AP should respect it.
