### ISSUE TITLE
Translate casts to Mixin class into casts to target classes

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#18]
I propose that the Mixin project convert casts to a mixin class into casts to the class targeted by said mixin. This would allow mixins to be written much more cleanly, without needing to add in an interface for every mixin whose added methods need to be added.

Consider the following scenario (many such examples exist in the Sponge repository)

* A mixin called `MixinEntity` adds a method - `isTeleporting`.
* Another class wants to access the mixed in `isTeleporting` method of an `Entity` instance it has.

Since mixin classes don't exist at runtime, it's impossible to cast the `Entity` instance to `MixinEntity`. Instead, this procedure must be followed:

* Create an interface (let's call it `IMixinEntity`) containing the method that you want to access - in this case, `isTeleporting`
* Make the mixin class implement the interface, thus making the target class implementing it.
* When another class wants to access `isTeleporting`, it casts its `Entity` instance to `IMixinEntity`, then calls the method.

This is quite common in the Sponge codebase.

This could be simplified greatly by having Mixin convert all such casts to casts to the target class. Since the mixin class doesn't exist at runtime, there's no scenario under which such a cast would lead to desired behavior, and would need to be left unchanged.

**EDIT**: After discussion on IRC, it's been proposed that this only apply to mixins - that is, only casts in mixin classes are transformed.

**Comment by gratimax** [comment]
I brought up the point in IRC that currently, one of the basic guarantees of Mixin is that it _only modifies the target class_ (@Aaron1011 later corrected me in saying that it also modifies the mixin class). The point of this is that Mixin does no work beyond classes directly affected by it (the target and mixin classes). This change, while rather simple, drops that guarantee and lets Mixin work on code that _uses_ mixins in addition to classes _directly affected_ by it. 

I think that whether Mumfrey thinks this guarantee should be held will pretty much determine if this issue will pass or fail.

**Comment by Mumfrey** [comment]
> EDIT: After discussion on IRC, it's been proposed that this only apply to mixins - that is, only casts in mixin classes are transformed.

They [already are](https://github.com/SpongePowered/Mixin/blob/feature/supermixin/src/main/java/org/spongepowered/asm/mixin/transformer/MixinTargetContext.java#L261-L263), see current feature branch. As for the other thing: **no**, a mixin should never, ever, be referenced outside itself so this isn't happening.
