### ISSUE TITLE
Slice for @ModifyConstant

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#180]
The ordinals with ModifyConstant can also sometimes become larger, And the possibilities of breakage is even larger when small or commonly appearing constants are replaced, gnd frequently the breakage can be silent. Slice would be useful there.

**Comment by Mumfrey** [comment]
Good point.

**Comment by Barteks2x** [comment]
Another reason it would be *very* useful thing to have: even *finding* the right ordinal in some cases, like replacing zeros in `Teleporter.makePortal` is a hell.
