### ISSUE TITLE
public static Accessor and Invoker

### ISSUE THREAD

**Issue by LeafHacker** [SpongePowered/Mixin#182]
I am using liteloader/mixin and need to access `private static` methods and fields.

`@Accessor` and `@Invoker` have worked fine for non-static methods and fields, but AFAICT `@Overwrite` is the only mixin that can be `public static`.

I understand that one limitation of mixins is that you cannot add visible static members to a class, so it may be impossible to have `public static` `Accessor`s.

Perhaps this would be better fixed with access transformers being supported by liteloader?

Or maybe I should use a hack such as creating an instance of the class and using a non-static mixin on the instance to access a static field/method on the target class?

Apologies if this has already been covered somewhere else.

**Comment by Mumfrey** [comment]
You **can** add `public static` accessors, this is one of the exceptions to a rule specifically provided for in accessor mixins.

**Comment by LeafHacker** [comment]
Interesting. I shall have to test more thoroughly before believing my IDE's error linting in future. Is `Invoker` also an exception?

**Comment by DemonWav** [comment]
You wouldn't happen to be using my IntelliJ plugin would you? If so it may be possible there is an error in one of my inspections.

**Comment by LeafHacker** [comment]
@DemonWav yes I am using your (awesome) Minecraft Dev plugin. I'll open a separate issue over there for the code inspection.

@Mumfrey if you can have `public static` `Invoker`s, feel free to close this as invalid - otherwise probably best to just remove `Accessor` from the title.

**Comment by DemonWav** [comment]
Whoops, sorry about that. I'll look into the issue then.

**Comment by LeafHacker** [comment]
Wait... Don't Accessors have to be `abstract` to be implemented by Mixin? And doesn't java [not support](https://stackoverflow.com/questions/370962/why-cant-static-methods-be-abstract-in-java) `static abstract` members anyway?

**Comment by Mumfrey** [comment]
> Wait... Don't Accessors have to be abstract to be implemented by Mixin? And doesn't java not support static abstract members anyway?

They don't have to be abstract, the method body is just ignored.
