### ISSUE TITLE
Mixin fails build on classes needing generated classes?

### ISSUE THREAD

**Issue by luacs1998** [SpongePowered/Mixin#183]
So besides Mixin, I'm using the Hibernate AP, which reads annotations from a class then generates metadata based on the annotations

However, using both the Mixin AP and Hibernate AP together are giving me some extremely odd results. It would see that (sometimes) I'm getting build errors because the classes which require generated class files are being evaluated before there's an opportunity to generate the needed classes.

Is this a problem with my buildscript, or with Mixin, or something else altogether?

Logs: https://puu.sh/wbx8L/722e4434b1.txt

I can only reproduce this sometimes - it happens on my PC and not on my build server, for example.

**Comment by Mumfrey** [comment]
I am away on an event until the 12th, I'll take a look into this when I'm back.

**Comment by luacs1998** [comment]
I've found the issue - apparently one of my mixins was invalid and it was throwing errors.

The Hibernate AP stuff was just noise, apparently. Thanks anyway.

**Comment by Mumfrey** [comment]
Good to know, thanks for keeping me posted. Things worth mentioning which might help:

* If you use eclipse, you can use the AP directly within eclipse and you get proper wiggly-line error marking and stuff with it, so you get instant feedback if the AP is gonna choke on something.
* If you use idea, then you can use [mcdev intellij](https://plugins.jetbrains.com/plugin/8327-minecraft-development) (made by @DemonWav with contributions from @Minecrell) and as well as picking up errors that the AP would, it also tends to spot more subtle things and also has a shit-tonne of functionality for autocompletion in mixins and suchlike.
