### ISSUE TITLE
Change the superclass of a class

### ISSUE THREAD

**Issue by DaMatrix** [SpongePowered/Mixin#184]
Hi! Over at [Valkyrien Warfare](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped) I'm trying to port all our ASM over to mixin. I'm encountering one big problem. We change the superclass of net.minecraft.entity.Entity to our own custom ValkyrienWarfareBase.Interaction.EntityDraggable, to avoid using reflection for lots of internal code. Is there a way that this can be done using mixins? If so, how, and if not, could it be implemented? Thanks!

**Comment by kashike** [comment]
Here's how we do it without Mixin:
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/launch/transformer/SpongeSuperclassRegistry.java
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/launch/transformer/SpongeSuperclassTransformer.java
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/launch/SpongeLaunch.java#L112-L123
https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/java6/java/org/spongepowered/mod/SpongeCoremod.java#L138-L143

**Comment by DaMatrix** [comment]
We already have it working without mixins, but we're trying to use only mixins.
https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/blob/4c5aacf7de52a853c4a3c9cdfbaec213c5861c5d/src/main/java/ValkyrienWarfareBase/CoreMod/ValkyrienWarfareTransformer.java#L42-L46

**Comment by DaMatrix** [comment]
If not, is there a way to get access to a method name that doesn't exist at compile time but does at runtime WITHOUT using reflection?

**Comment by gabizou** [comment]
> If not, is there a way to get access to a method that doesn't exist at compile time but does at runtime WITHOUT using reflection?

This is what we do in Sponge: We make these interfaces that provide us methods necessary to "do things", and we simply cast the objects to those interfaces (Of course, you implement them with a Mixin, like in [`MixinWorldServer`](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L215)). You can see [here](https://github.com/SpongePowered/SpongeCommon/search?p=2&q=IMixinWorldServer&type=&utf8=✓) how many results of casing or using [`IMixinWorldServer`](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/interfaces/world/IMixinWorldServer.java#L53).

None of this requires specifically making superclass changes either, and it's more than likely to be safer overall.

**Comment by DaMatrix** [comment]
Great, thanks. This looks a LOT cleaner than what we'd had before anyway :P thanks!
The fix for anyone interested: https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/commit/3b7b63a077d448cd76188384bf125ea11381de83
