### ISSUE TITLE
Combined Accessor and duck interface

### ISSUE THREAD

**Issue by LeafHacker** [SpongePowered/Mixin#185]
`@Accessor` and `@Invoker` provide a nice way to create public accessors for target fields/methods, without having to manually implement getters/setters.

I have existing duck interfaces that can largely be replaced with Accessor interfaces without any api changes, however a few of these interfaces also define new public members which must be implemented in the associated mixin class.

For example:

```java

@Mixin(Minecraft.class)
public interface IMinecraft {
    @Accessor Timer getTimer();
    @Accessor void setRightClickDelayTimer(int delay);

    @Invoker("clickMouse") void leftClickMouse();
    @Invoker("rightClickMouse") void rightClickMouse();
    @Invoker("middleClickMouse") void middleClickMouse();

    void clickMouse(ClickEvent.MouseButton button);
}

@Mixin(Minecraft.class)
public abstract class MixinMinecraft implements IMinecraft {
    @Override
    public void clickMouse(ClickEvent.MouseButton button) {
        // IF statements are required because Mixin doesn't support SWITCH
        if (button == LEFT)
            leftClickMouse();
        if (button == RIGHT)
            rightClickMouse();
        if (button == MIDDLE)
            middleClickMouse();
    }
}
```

**Comment by JBYoshi** [comment]
I think you can `default`-implement the methods; if it doesn't work in the interface itself, you can try putting it in a superinterface and casting `this`.

**Comment by LeafHacker** [comment]
I got the impression that Mixin Accessor interfaces cannot contain anything other than Accessor/Invoker members?

I might try adding default/static methods to an Accessor interface later, but that wouldn't help more complex cases where you require a full blown Mixin class, an Accessor interface and a duck interface.

My current work around is to have a duck interface, and put the Accessor annotation in the implementing Mixin class, but it would still be great to support non-mixin public members in Accessor interfaces to allow them to be used as ducks.

**Comment by Mumfrey** [comment]
By definition, a duck interface and an accessor interface are two different things. You cannot combine them because any non-accessor methods in the interface will invalidate its status as an accessor mixin. However, you *can* reduce boilerplate by using `@Accessor` methods in a regular mixin.

Whilst I agree that from a purely aesthetic standpoint it might be nice to combine the two, it doesn't actually improve functionality and invalidates some of the existing contract of accessor-only mixins.
