### ISSUE TITLE
Cannot resolve Injectionpoint TAIL

### ISSUE THREAD

**Issue by kingdevnl** [SpongePowered/Mixin#188]
Cannot resolve Injectionpoint TAIL
http://i.imgur.com/jM5dO9Z.png
http://i.imgur.com/5FRKhkv.png

**Comment by JonathanxD** [comment]
AFAIK there is no `TAIL` `InjectionPoint`, a similar target is `RETURN`, which injects before `return` instructions

**Comment by kingdevnl** [comment]
There always was a TAIL point.

**Comment by kingdevnl** [comment]
I have it in my older project,

**Comment by gabizou** [comment]
This isn't an issue with Mixin, it's an issue with [MinecraftDev](https://github.com/minecraft-dev/MinecraftDev). If you run the mixin in production, I'm sure no warnings or errors will actually show up.

**Comment by DemonWav** [comment]
This is not an issue with MinecraftDev. MinecraftDev is correctly reporting that there is no `TAIL` injection point. It is mostly likely the case that your older project is using an older version of Mixin which may have had a `TAIL` injection point, but modern versions of Mixin definitely do not.

**Comment by gabizou** [comment]
> It is mostly likely the case that your older project is using an older version of Mixin which may have had a TAIL injection point, but modern versions of Mixin definitely do not.

There's [`BeforeFinalReturn`](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/injection/points/BeforeFinalReturn.java#L58)...

**Comment by DemonWav** [comment]
That class was added Jan 9, so forgive me for not knowing about it. :)

This tells me it's the opposite problem - the Mixin version he's using is too old to support `TAIL`.

**Comment by JonathanxD** [comment]
So, [At](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/injection/At.java) javadoc should be updated.

**Comment by Mumfrey** [comment]
[Ok](https://github.com/SpongePowered/Mixin/commit/8fe09fb9781c33b460e95778f6dd4f4bfe53b93c).
