### ISSUE TITLE
Access Transformers trip visibility sanity check for overwritten methods

### ISSUE THREAD

**Issue by Mumfrey** [SpongePowered/Mixin#189]
This is an issue which has been illuminated by SpongePowered/SpongeForge#1604.

As a solution to #167, Mixin performs sanity-checks of overwritten methods to ensure that the access modifier of the mixin method is always the same or more permissive than the method being overwritten. This check can actually cause problems when a previously-`private` target method is transformed to `public` by another transformer ("Access Transformer" for example).

In general it is important that access modifiers are preserved because `private` methods will receive static bindings (`INVOKESPECIAL`) whilst any higher levels of visibility will be dynamically bound (`INVOKEVIRTUAL`).

> **Example:** Consider a mixin for `Entity` which *overwrites* a `private` method called `getInternalId()`. Other methods in the mixin can call `getInternalId()` and the calls will be statically bound using `INVOKESPECIAL`.
>
> A mod comes along and wants to override `getInternalId()` in their `EntityModded` subclass, they use an *Access Transformer* to change the visibility of the method to `protected` in order to do so.
>
> **Without** the mixin sanity check in place, the method could be overwritten. However statically bound invocations of the method in the mixin *do not* respect the virtual calling convention, and thus in instances of `EntityModded` the base-class version of the method is called. This could lead to invalid state in the `EntityModded` when calling in from mixin code.
>
> **With** the sanity check in place, the overwrite fails (correctly), however the game is inhibited from starting as a consequence.

1. The current sanity check is correctly identifying a problem and preventing unexpected negative consequences
2. Mixin should provide an option to gracefully deal with this situation.

The most straightforward approach to solving this issue is to allow graceful *upgrade* of access modifiers on an overwritten method to match the target, with all invocations of the method within the mixin similarly upgraded to dynamic bindings to respect invocation semantics for a protected or public method. However this leads to another potential pitfall:

> Assume that `MixinEntity` overwrites the private helper method `getInternalId()` in `Entity`. A mixin for `EntityLiving` happens to contain a `public` method `getInternalId()` and the two methods **do not exist in an "override" relationship** because the base class method is `private` and the derived class method cannot "see" the superclass method.
>
> The mod *Access Transformer* makes the `getInternalId()` method in `Entity` to `protected`.
>
> Mixin "upgrades" the overwrite method to `public` to correspond to the new target method, it also "upgrades" invocations of the method to `INVOKEVIRTUAL`.
>
> The result is that `EntityModded` now *intentionally overrides* the `getInternalId()` method, as intended by the mod author. However the mixed-in method in `EntityLiving` now **unintentionally overrides the base class method**.

This is a contrived example, but in particular in a production environment where methods are just called `a`, `b`, etc. this is a real concern (less so in Forge because of srg renaming, but still possible).

This leads to the following conclusions:

* The option to allow "upgrading" (for the purposes of user-facing terminology, I will refer to this as *conforming* the access modifiers) access modifiers needs to be gated behind a mixin-set level option and explicitly enabled when necessary, since the user is declaring that they accept responsibility for unforseen side-effects of conforming.
* When a conform operation is performed, a warning must be output. The warning can be suppressed if the upgrade is not from `private` since only `private` will experience the possible static/dynamic binding conflict (override semantics being easily observable in the cases where the candidate is already `protected`.

**Comment by Barteks2x** [comment]
I also had that problem once when I submitted forge or to change method visibility.. And with that I broke my own mod. I didn't know it could be considered sponge issue...

**Comment by ryantheleach** [comment]
@Barteks2x Strictly speaking it's not, but having this feature allows a compromise that would have otherwise been painful to work around.

**Comment by Mumfrey** [comment]
> &#064;&#xfeff;Barteks2x Strictly speaking it's not, but having this feature allows a compromise that would have otherwise been painful to work around.

Exactly, I feel like even though this isn't technically my problem, I still want to solve it, and ideally in as robust a way as possible. My concern is that the cure could be worse than the disease in some bizarre corner cases (and we all know how often *those* actually tend to crop up) it could lead to some very weird behaviour, and I'm wondering if the warning message is enough.

Play with *Access Transformers*, get burned.

**Comment by Mumfrey** [comment]
Resolved in version 0.6.13, commit 64232fe110ed339aab08c590dfdae0b50d478f57
