### ISSUE TITLE
Pre-super() redirect broken again

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Mixin#193]
#174 seems to be back  again... with the exact same injection, just a newer Mixin version. After looking into the issue, it seems that Mixin performs the constructor-specific error check ([this line](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/injection/invoke/RedirectInjector.java#L233), referring to [this method](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/injection/invoke/InvokeInjector.java#L91)), which works... then turns around and does the regular `static` check ([this line](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/injection/invoke/RedirectInjector.java#L234), referring to [this method](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/injection/invoke/InvokeInjector.java#L74)), which fails.

**Comment by Mumfrey** [comment]
Hoorah, I'll look at that.
