### ISSUE TITLE
Make ModifyConstant.slice an array

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#194]
It's already an array in `Inject`, I don't see any reason it wouldn't be in `ModifyConstant` or any other injectors. It also feels a bit inconsistent.

In some cases I need to modify the same constant (mostly zero) in many places, but need to specify slice to avoid replacing ones I don't want to change. Currently I just need to copypaste the same method many times changing only te slice.

I think the same could also apply to: `ModifyArg`, `ModifyArgs`, `ModifyVariable` and `Redirect` (but sor some of them it could be mostly useless)

**Comment by Mumfrey** [comment]
It's mainly just like that for legacy reasons, I see no reason not to change it.
