### ISSUE TITLE
A more intuitive way to specify max allowed injections for an injector

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#195]
There are some injections, mostly `ModifyConstant`, where replacing a new unknown one should be considered a critical failure. When replacing a constant there is no way to know what that constant means aside of reading the code, so any constants added by transformers or version updates could cause hard to track down unintended side effects.

Currently I usually use `@Group` on each of those injectors, usually with group size of 1. But it's a bit unintuitive and conflicts with actual groups of injectors. It's also far from what it's intended for.

**Comment by Mumfrey** [comment]
If you specify an `ordinal` value then the number of injections is limited to 1.

> It's also far from what it's intended for.

On the contrary, it's exactlly what `@Group` is intended for.

**Comment by Barteks2x** [comment]
Then the documentation could also mention that. For me group feels a bit strange when the group size is 1.

And when there are 3 or more places, adding separate method with specified ordinal for each of a bit verbose.

**Comment by Mumfrey** [comment]
So just a `max` or `allowed` value on injectors is what you're after?

**Comment by Barteks2x** [comment]
This would be ideal.

But if this is really what `@Group` is intended for then I can keep using it. But I think it should be made clear in documentation. And `require` already "duplicates" the `min` part of `@Group` functionality.

**Comment by Mumfrey** [comment]
Yeah I agree. To be clear, `@Group` is intended as a way of sanity checking maximal number of injections across any number of injectors, so it can be from 1 injector to many. The thing is as you say, it makes sense to put a max allowed marker on the injectors where you want a specific distribution of injection counts as well, so it's both a more concise way of achieving the same thing, and also adds some extra capability where needed.
