### ISSUE TITLE
Globally assigned variables are sometimes null.

### ISSUE THREAD

**Issue by me4502** [SpongePowered/Mixin#20]
Variables that are assigned globally in the class, specifically

private List<PatternLayer> patterns = Lists.newArrayList();

in MixinTileEntityBanner, do not actually set the variable.

As can be seen here, https://github.com/SpongePowered/Sponge/commit/f9851975f7d5280348e3d290377371cb9c54a82f

**Comment by simon816** [comment]
Thing is, it does work. Looking at the decompiled output of the mixins (in jd-gui) you can see it sets the field just fine.
![Screenshot](http://puu.sh/ghECk/f003899aa3.png)
(Mind you, I am on the `feature/supermixin` branch but pretty sure it would work on master too)

**Comment by me4502** [comment]
Yeah, it seems to work on supermixin. I'll just leave this open until then I guess.

**Comment by Minecrell** [comment]
The `master` branch doesn't seem to add it:
```java
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package net.minecraft.tileentity;

import ...

public class TileEntityBanner extends TileEntity implements Banner {
    private int baseColor;
    private NBTTagList field_175118_f;
    private boolean field_175119_g;
    private List field_175122_h;
    private List field_175123_i;
    private String field_175121_j;
    private static final String __OBFID = "CL_00002044";
    private List<PatternLayer> patterns;

    public TileEntityBanner() {
    }

    ...
}
```

**Comment by simon816** [comment]
Actually I was on the master branch, forgot I checked-out. I've just tested with supermixins too and it also works.

To be specific, it works using the Mixin commits 8748534d18c8f8db7209e3393def72c2b4bdfc40 and 25570a0ada10449f31867326551d3662eb9e236d. With SpongePowered/Sponge@013191ff296f831049c6cacfc99e4a4abb1fc33e

**Comment by ryantheleach** [comment]
I thought mix-ins mixed at runtime, how are you getting the files into jd and fernflower?

**Comment by simon816** [comment]
@ryantheleach add `-Dmixin.debug.export=true` to the VM launch arguments. It dumps the mixed-in classes into `{run_dir}/.mixin.out/`
See [MixinTransformer:161](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/transformer/MixinTransformer.java#L161)

**Comment by Mumfrey** [comment]
This was already fixed a while ago on the current feature branch, I will close this issue when I merge it.
