### ISSUE TITLE
Don't suppress exception in MixinPlatformAgentFML#initFMLCoreMod

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#203]
[Supressing all Exceptions](https://github.com/SpongePowered/Mixin/blob/ee0c879dc7c3d16c82d77be69f3d3faad106310d/src/main/java/org/spongepowered/asm/launch/platform/MixinPlatformAgentFML.java#L114) ended up hiding an important problem that I was debugging.

**Comment by Mumfrey** [comment]
Ok.
