### ISSUE TITLE
Mixin expects weird method parameters for redirect

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#204]
With Mixin 0.7.1 this [`@Redirect` in `MixinWorldServer` in SpongeCommon](https://github.com/SpongePowered/SpongeCommon/blob/2b828ac9c30e11a576735b81c68106aa08f072b7/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L1957-L1960) is failing for some reason:

```java
@Redirect(method = "canAddEntity", at = @At(value = "INVOKE", target = "Lorg/apache/logging/log4j/Logger;warn(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V", remap = false))
public void onCanAddEntityLogWarn(Logger logger, String message, Object param1, Object param2) {
    // don't log anything to avoid useless spam
}
```

The redirected call takes a `String` and two `Object`s so the method parameters for the `@Redirect` look correct for me. However, Mixin insists to remove one of the `Object` parameters:

```
@Redirect handler method net/minecraft/world/WorldServer::redirect$onCanAddEntityLogWarn$zke000 has an invalid signature,
expected (Lorg/apache/logging/log4j/Logger;Ljava/lang/String;Ljava/lang/Object;)V 
found    (Lorg/apache/logging/log4j/Logger;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
```

I'm not sure why Mixin does that but the target method also has two calls to `warn(Ljava/lang/String;Ljava/lang/Object;)V` which might be related.

It doesn't happen with Mixin 0.7 (or older versions) so it must have been introduced by a change in Mixin 0.7.1.

**Comment by Mumfrey** [comment]
Ah ok, I think I know which change in 0.7.1 would cause that, it's to do with the runtime refmap remapping. I most likely made the BeforeInvoke matcher too permissive when refmap remapping is active. The good news is this should be fine in production, it'll just fail in dev. Should be pretty easy to fix.
