### ISSUE TITLE
Modify arguments that are given to a void.

### ISSUE THREAD

**Issue by pKalju** [SpongePowered/Mixin#212]
Hello, I would like to know how to modify a void which gets called in multiple places. I thought about using `@ModifyConstant`, but that requires the overwritten input to be finalized. Ideally I want to be able to change the value so it could be changed multiple times.

I also tried using @Inject, but that won't make it so the modified variable gets called later.

Example:
```java
public void callNumber(Number number, boolean isLandLine) {
    //Inject: start
    isLandLine = false;
    //Inject: end
    if (isLandLine) {
        phoneBill.add(10);
    } else {
        phoneBill.add(5);
    }
    call(number);
}
```

**Comment by Mumfrey** [comment]
The problem in question is quite target-specific. Depending on the nature of your target will determine the type of injection you use. You are most likely looking for [ModifyVariable](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/ModifyVariable.html) but it very much depends.

In your example case an `@ModifyVariable` can be used at `HEAD` with a `boolean` discriminator and `ordinal` zero, but depending on target there may be better ways available to you. Without seeing the actual target code I can't really suggest anything additional.

**Comment by pKalju** [comment]
This works for my use perfectly. Thanks for the help.
```java
@ModifyVariable(method = "callNumber", at = @At(value = "HEAD"))
private boolean onCallNumber(boolean isLandLine) {
    LandLineEvent event = new LandLineEvent(isLandLine);
    EventBus.pre(event);

    isLandLine= !event.isLandLine();
    return isLandLine;
}
```
