### ISSUE TITLE
Error loading class: net/minecraft/world/chunk/Chunk

### ISSUE THREAD

**Issue by Ordinastie** [SpongePowered/Mixin#213]
It seems the first mixin in the list from https://github.com/Ordinastie/MalisisCore/blob/1.12/src/main/resources/mixins.malisiscore.core.json#L9 always show an error in the log : 
`[14:58:00] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/World`
`[14:58:00] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/world/World to metadata cache`
`[14:58:00] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.World was not found mixins.malisiscore.core.json:MixinClientNotif$MixinWorld`

If I remove the first one in the JSON , I get : 
`[15:22:25] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/WorldServer`
`[15:22:25] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/world/WorldServer to metadata cache`
`[15:22:25] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.WorldServer was not found mixins.malisiscore.core.json:MixinClientNotif$MixinWorldServer`

And if I remove the first two : 
https://gist.github.com/Ordinastie/d029f5cf4089ff913dff49cfd9cc2db4#file-fml-log-L271

**Comment by Mumfrey** [comment]
Hm, yes it's not possible to tell what error is being caught in the classload which is leading to that because mixin catches it and just emits that error. I'll change the relevant part to log the exception stacktrace so we can see where it's failing.

**Comment by Mumfrey** [comment]
Ok if you give that few minutes to build on jenkins and upload to creeperhost it should generate some more useful log info.

**Comment by Ordinastie** [comment]
Is it supposed to be uploaded yet ? I can't seem to have the exception shown.

**Comment by Mumfrey** [comment]
Yes it was available nearly an hour ago.

**Comment by Ordinastie** [comment]
I don't see any exception in the log. Apprently vanilla launcher eats logs, so that doesn't help but even inside the log window, I don't see any exception.

**Comment by Mumfrey** [comment]
Did you definitely refresh-dependencies before you rebuilt your mod?

**Comment by Ordinastie** [comment]
I did. Let's do it again to be sure.

**Comment by Ordinastie** [comment]
This time it worked I think, but I don't see the exception being that helpful : 
https://gist.github.com/Ordinastie/b038e3f19180e393a06c87100a9cb76c#file-fml-log-L271

**Comment by Ordinastie** [comment]
I should specify it only happens in prod, not in dev.

**Comment by Mumfrey** [comment]
Can you send me a binary or link me to the project source please. I have no idea why that would happen it's very unusual.

**Comment by Ordinastie** [comment]
https://github.com/Ordinastie/MalisisCore
https://puu.sh/xNpqq.jar

**Comment by Ordinastie** [comment]
If you launch a world, it will crash also, if you want to take a look at it too :)

**Comment by Mumfrey** [comment]
Is that definitely the correct binary? It works 100% perfectly for me:

[log file](https://gist.github.com/Mumfrey/55e0e232519a6a929caaee6503d71d2c)

Including creating a world and loading in in single player:

![image](http://eq2.co.uk/minecraft/2017-10-01_16.12.25.png)

**Comment by Ordinastie** [comment]
I don't know about the crash when loading a world, but there is the exception in your log : https://gist.github.com/Mumfrey/55e0e232519a6a929caaee6503d71d2c#file-fml-client-latest-log-L267

**Comment by Mumfrey** [comment]
For comparison (since I'm using the old Java launcher) I tested using the new native windows launcher as well, just to make sure it isn't an issue with the new launcher:

[log file](https://gist.github.com/Mumfrey/f5bb89a7f1ca60ca6a1053336144721a)

**Comment by Mumfrey** [comment]
Ah ok, that means I can attach a debugger to it and figure out what's going on then.

**Comment by Mumfrey** [comment]
Okay I've identified the problem. There was a race condition between detecting the name transformer and when the first mixin could be processed. Resolving the race condition fixes the problem.

**Comment by Ordinastie** [comment]
My other issue doesn't seem to happen anymore for some reason, but it was that : https://github.com/Ordinastie/MalisisCore/issues/124

**Comment by Mumfrey** [comment]
It might be you were running a version of mixin before [this fix](https://github.com/SpongePowered/Mixin/commit/5a1a51a2f059a1a62c32741422b3032591537b29) which fixed the mappings generated by the AP for inner-class mixins. Looking at the current binary everything seems to be properly obfuscated.

**Comment by Ordinastie** [comment]
I don't know, I was sure I updated the snapshot, but today it took me like half-dozen tries to have it downloaded. I need to make a new release, I'll see if it's fixed in that one.
Thanks for your help.

**Comment by Mumfrey** [comment]
Do yourself a favour and put this in your global gradle init:

```groovy
allprojects {
    configurations.all {
        resolutionStrategy {
            cacheChangingModulesFor 0, 'seconds'
        }
    }
}
```
It basically sets system-wide that SNAPSHOTs should be checked every build and basically means you hardly ever have to run `--refresh-dependencies`. Only add it if you have a good internet connection though.
