### ISSUE TITLE
Trying to have Sponge run in a dev environment.

### ISSUE THREAD

**Issue by Ordinastie** [SpongePowered/Mixin#215]
I'm trying to have Songe in my dev environment to help me fix my mixin, but it crashes.
I just put the dev jar in mods/ folder.
Here is the log : https://gist.github.com/Ordinastie/ffdb58b42b4ff7a58fa62cde7a544946

**Comment by Mumfrey** [comment]
Looks like something else you have in your environment is breaking the coremod contract.

**Comment by Mumfrey** [comment]
Also there is not sufficient information in the console log to troubleshoot something like that, the fml log will provide the required details.

**Comment by Ordinastie** [comment]
I added the log to the gist.

**Comment by Mumfrey** [comment]
Looks like it's discovering the spongeforge jar too late to get the PREINIT phase mixins applied, you could try putting the spongeforge jar on the classpath instead.

**Comment by Ordinastie** [comment]
If I just put the jar on the classpath, it apparently gets loaded first and takes its Mixin version instead of the 0.7.4 MalisisCore needs.
I don't see to be able to change the order.

**Comment by Mumfrey** [comment]
Assuming you're using eclipse, you can just click on the sponge jar in the run configuration and change its order with respect to the other items on the classpath.

**Comment by Ordinastie** [comment]
I got the same result for both : 
https://puu.sh/xRsYy.png and https://puu.sh/xRsY2.png

**Comment by Mumfrey** [comment]
Hm weird, I wonder if there's some internal sorting going on in FML or ForgeGradle. There's two possible remedies:

* Add the mixin 0.7.4 jar to the classpath directly, at the top
* Open the spongeforge jar and just delete `org.spongepowered.asm` package, it only needs the manifest entries in order to detect it properly

**Comment by Ordinastie** [comment]
I somehow broke everything as I can't even launch at all anymore, even without Sponge. I'll get back to you once it's fixed.

**Comment by Mumfrey** [comment]
It's probably easier to deal with this kind of thing over IRC anyway, better to wait until this evening if you can.
