### ISSUE TITLE
-Dmixin.env.refMapRemappingFile does nothing (always empty)

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#219]
After looking at the code, [this line](https://github.com/SpongePowered/Mixin/blob/404f5da0b6b18980b4e44c7f1cfeddcd47fe4aa6/src/main/java/org/spongepowered/asm/mixin/MixinEnvironment.java#L554) always returns the default value for the option, because parent is never null, and the `ENVIRONMENT` one always returns `false` as booleanValue, so mixin never attempts to access the system property. And I really don't know what the intended behavior of this method is.

**Comment by Mumfrey** [comment]
That's a refactoring fail I think, I changed the way the inheritance worked to try and remove some code duplication a while back and it must have buggered up the string property handling. I'll take a look and fix that.
