### ISSUE TITLE
Inject into a forge mod?

### ISSUE THREAD

**Issue by w-o-a-h** [SpongePowered/Mixin#220]
Is there a way to inject something into a forge mod I'm trying to do this to fix a issue in a mod that is closed source.

**Comment by liach** [comment]
@w-o-a-h You can. Add that mod's deobfuscated version as one of your dependencies and make a coremod that add your mixin config into your mixin. Then, you can target your mixins to classes in that mod.

**Comment by w-o-a-h** [comment]
Its compiling there mod into my mod for some reason
