### ISSUE TITLE
Question - Modifying local variable

### ISSUE THREAD

**Issue by pKalju** [SpongePowered/Mixin#226]
Hello, I would like to know how to modify a local variable that gets modified and called multiple times in a method. I tried looking for ```@ModifyLocal```, but that does not seem to exist.

I noticed there are quite a few interesting methods here, but there are no full examples about them.
https://github.com/SpongePowered/Mixin/tree/master/src/main/java/org/spongepowered/asm/mixin/injection/modify

The method I'm trying to modify has no input, only calls variables which are public and in the same class. My goal is to times the value of ```elapsedPartialTicks``` in the line that it is being ```+=```'d.
```
public void updateTimer() {
        long i = Minecraft.getSystemTime();
        this.elapsedPartialTicks = (float)(i - this.lastSyncSysClock) / this.tickLength;
        this.lastSyncSysClock = i;
        this.renderPartialTicks += this.elapsedPartialTicks /*Injection start*/ * timerSpeed /*Injection end*/;
        this.elapsedTicks = (int)this.renderPartialTicks;
        this.renderPartialTicks -= (float)this.elapsedTicks;
    }
```

**Comment by Mumfrey** [comment]
What you're looking for is [`@ModifyVariable`](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/ModifyVariable.html) though bear in mind it can be a bit sensitive to changes in the target method which is why it takes a "discriminator" approach where possible. If you have any questions about its use then let me know below.

**Comment by Minecrell** [comment]
Your example is confusing: If I understand you correctly, you want to multiply `elapsedPartialTicks` with another value before it is added to `renderPartialTicks`. However, `elapsedPartialTicks` is a field, not a local variable. Therefore you can just `@Redirect` the field normally.

**Comment by pKalju** [comment]
Alright I tried to use ```@Redirect```, but that caused this error:
```Mixin apply failed mixins.future.json:MixinTimer -> net.minecraft.util.Timer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Redirect method getter net/minecraft/util/Timer::redirect$onUpdateTimer$zbh000 has an invalid signature. Expected (Lnet/minecraft/util/Timer;)F but found ()F
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Redirect method getter net/minecraft/util/Timer::redirect$onUpdateTimer$zbh000 has an invalid signature. Expected (Lnet/minecraft/util/Timer;)F but found ()F```
```
@Redirect(method = "updateTimer", at = @At(value = "FIELD", target = "net/minecraft/util/Timer.elapsedPartialTicks:F", ordinal = 1))
    private float onUpdateTimer() {
        return elapsedPartialTicks *= timerSpeed;
    }
```

Then I just replaced it with ```@Inject``` and it is working, even though I think it is not supposed to work and something needs to be changed here.
```
@Inject(method = "updateTimer", at = @At(value = "FIELD", target = "net/minecraft/util/Timer.elapsedPartialTicks:F", ordinal = 1))
    private void onUpdateTimer(CallbackInfo ci) {
        elapsedPartialTicks *= timerSpeed;
    }
```

**Comment by Minecrell** [comment]
The reason why the `@Inject` is working is that you actually modify the actual `elapsedPartialTicks` field, instead of only the number that will be added to `renderPartialTicks`.

The reason why your `@Redirect` isn't working is that you need to add a single `Timer` parameter (you don't have to use it, though).

**Comment by pKalju** [comment]
Alright now that this is figured out, I would like to know how to modify an if check, making one of the parts return true.
```
public void doSomething() {
    if (cantDoRightNow) {
        doSomethingElse();
    }
    if (canDoRightNow() && canDoAfter()) { // <-- Make canDoAfter() return true
        doThis();
    }
}
```

**Comment by Mumfrey** [comment]
Then Redirect `cantDoAfter()`.
