### ISSUE TITLE
Mixin and forge coremods policies (dependency extraction)

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#228]
I already asked about that on IRC but got no reply so far, so asking here instead.

As of Minecraft 1.12, modders are supposed to separate coremods into separate jars, that just handle the class transformation, and to still keep it one file to download - use forge dependency extraction system, where forge will extract the coremod jar from inside the normal mod.

According to lex, this is also supposed to work with mixin too but I can't get it working. When I put mixin + my mixin classes into separate jar - mixin will try to load the classes directly referenced by mixin classes, which obviously fails because the mod jar they are in isn't loaded yet.

Normally i would look at how sponge handles it, but it doesn't seem to handle it at all and keeps  doing everything the old way with everything in one jar.

How can I do that?

**Comment by Mumfrey** [comment]
This is a discussion for IRC, also not on Christmas day.

**Comment by Mumfrey** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/4081

**Comment by Mumfrey** [comment]
> As of Minecraft 1.12, modders are supposed to separate coremods into separate jars, that just handle the class transformation, and to still keep it one file to download - use forge dependency extraction system, where forge will extract the coremod jar from inside the normal mod.

Yes I know, and believe me Sponge will be at the forefront of that adoption wave as soon as it's *physically* possible

> According to lex, this is also supposed to work with mixin too but I can't get it working.

It doesn't work currently because Forge extracts bundled deps but has no mechanism to *then* choose the most recent version, instead if mod x and mod y both ship versions of mixin as an extracted dep, then the **oldest** one will get loaded because the files are actually loaded alphabetically so the oldest version will get loaded first.

> When I put mixin + my mixin classes into separate jar - mixin will try to load the classes directly referenced by mixin classes, which obviously fails because the mod jar they are in isn't loaded yet.

Yes.

> Normally i would look at how sponge handles it, but it doesn't seem to handle it at all and keeps doing everything the old way with everything in one jar.

Because the new way doesn't work yet.

> How can I do that?

You can't do it yet because Forge doesn't support it yet.

**Comment by Barteks2x** [comment]
> It doesn't work currently because Forge extracts bundled deps but has no mechanism to then choose the most recent version, instead if mod x and mod y both ship versions of mixin as an extracted dep, then the oldest one will get loaded because the files are actually loaded alphabetically so the oldest version will get loaded first.

This is not the issue I was talking about

> Yes.

So how are changes to forge going to make it possible? Mixin will still try to load stuff from the main mod jar, which at that point isn't yet in any classloader.

if it only needed the mixin interfaces to be there, I could put some of them in the core jar, and as lex suggested add API jar to classloader myself. But if it attempts to load classes that are just called somewhere in the methods, or used as field types, whatever forge does it seems like it would be equivalent to everything being in a single jar anyway.

**Comment by Barteks2x** [comment]
@Mumfrey any update on this? The dependency extraction forge PR has been merged (a second one submitted by lex, not sure if its able to select the right version for now, but that's not my issue). Does it change the status of this in any way?

**Comment by Mumfrey** [comment]
Hopefully, the proposed solution was that non-mod jars would just need to include some version metadata but the format wasn't nailed down. If the issue has now been solved then the relevant metadata will be added to Mixin artefacts going forward.

**Comment by Barteks2x** [comment]
The problem I'm actually talking about is not selecting the right mixin version, which I'm fully aware of, and I know what is needed for it to be fixed, but that actually separating the mixin classes and actual mod into separate jar makes mixin attempt to load many of the classes from the mod jar that are referenced from mixins. Another issue is that the interfaces would need to be in the coremod jar, which is going to be an issue if these interfaces are intended to be part of API of the mod.
