### ISSUE TITLE
ClassNotFoundException in InnerClassGenerator

### ISSUE THREAD

**Issue by gaeqs** [SpongePowered/Mixin#231]
Mixin: 0.7.4-SNAPSHOT (The build in the last Spongevanilla update)
I'm trying to edit a non-static nested class, But it seems Sponge crashes when it tries to load the class, throwing a ClassNotFoundException.

Error log: https://pastebin.com/czLcjpfQ
(Shouldn't it be ClassRemapper instead of Remapper?)

Code: https://pastebin.com/BtAJQ6QG

**Comment by Mumfrey** [comment]
This looks like a packaging error, that class hasn't been included in the jar.

> (Shouldn't it be ClassRemapper instead of Remapper?)

No, they are two different classes.
