### ISSUE TITLE
Mixin is sometimes detecting my plugin, sometimes not.

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Mixin#234]
I've recently developed a public Sponge plugin using Mixin which works fine for me and for most users but for some users using SpongeForge my plugin is not working at all because my mixin config does not seems to be applied or even detected. I don't know if I'm doing something wrong or it's a Mixin issue and I cannot reproduce the issue on my computer that's why I'm asking for help. Here is my plugin https://github.com/Yeregorix/AntiXray

**Comment by Mumfrey** [comment]
Wrong repo.
