### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by VRCube** [SpongePowered/Mixin#238]
Stacktrace:
```java
SEVERE: Unable to launch
java.lang.ClassCastException: org.apache.logging.log4j.simple.SimpleLogger cannot be cast to org.apache.logging.log4j.core.Logger
	at org.spongepowered.asm.mixin.MixinEnvironment$MixinLogger.<init>(MixinEnvironment.java:679)
	at org.spongepowered.asm.mixin.MixinEnvironment.init(MixinEnvironment.java:1235)
	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:157)
	at org.spongepowered.asm.launch.MixinBootstrap.init(MixinBootstrap.java:122)
	at cc.hyperium.launch.HyperiumTweaker.injectIntoClassLoader(HyperiumTweaker.kt:224)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)```
Does anyone know what is the problem?

**Comment by mikroskeem** [comment]
What Mixin library version?

**Comment by VRCube** [comment]
0.6.4 SNAPSHOT
```gradle
compile('org.spongepowered:mixin:0.6.4-SNAPSHOT') {
        exclude module: 'launchwrapper'
        exclude module: 'guava'
        exclude module: 'gson'
        exclude module: 'commons-io'
        }```

**Comment by mikroskeem** [comment]
`org.apache.logging.log4j.core.Logger log = (org.apache.logging.log4j.core.Logger)LogManager.getLogger("FML");` is (possible) culprit.

**Comment by VRCube** [comment]
Wdym?

**Comment by VRCube** [comment]
+ I am not using Forge

**Comment by mikroskeem** [comment]
You don't need to use Forge for that. MixinLogger class expects Log4j2 LogManager#getLogger to return `org.apache.logging.log4j.core.Logger` implementation, but that's not in the case.

So any idea how SimpleLogger gets used instead?

**Comment by VRCube** [comment]
I have no idea, the source code is at https://github.com/HyperiumClient/Hyperium you can take a look

**Comment by VRCube** [comment]
When I run the client from Workspace it worked fine, but not when I run from the launcher

**Comment by VRCube** [comment]
Anyone?

**Comment by Mumfrey** [comment]
Sorry I'm away at the moment until early next week. I'll take a look into it when I get back, I suspect there's a simple fix for it but that code was added as part of the initphase scaffolding so I can't remember who wrote it or why it would use a concrete class rather than an interface.

**Comment by VRCube** [comment]
```
SEVERE: Unable to launch
java.lang.ClassCastException: org.apache.logging.log4j.simple.SimpleLogger cannot be cast to org.apache.logging.log4j.core.Logger
	at org.spongepowered.asm.mixin.MixinEnvironment.gotoPhase(MixinEnvironment.java:1431)
	at org.spongepowered.asm.mixin.EnvironmentStateTweaker.getLaunchArguments(EnvironmentStateTweaker.java:58)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:122)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

```
Still does not work, please reopen

**Comment by VRCube** [comment]
@Mumfrey

**Comment by VRCube** [comment]
@Mumfrey so I need to use version 0.7.7 right?

**Comment by Mumfrey** [comment]
Yes. In general you should always be using the latest version because Mixin guarantees backward compatibility so your mixins will not break with newer versions, however you benefit from improvements in the core and in compatibility and stability improvements.

**Comment by Mumfrey** [comment]
See also [this PSA](https://github.com/SpongePowered/Mixin/wiki/PSA-Forward-Compatibility-Features-in-Mixin) about the use of `minVersion`.

**Comment by VRCube** [comment]
is the maven repo updated?

**Comment by VRCube** [comment]
also do you have discord so I can contact you easier?

**Comment by Mumfrey** [comment]
> is the maven repo updated?

Yes.

> also do you have discord so I can contact you easier?

No I can't stand discord, you can contact me on IRC in `#spongedev` on esper if necessary. If my nick name has uppercase `M` then I'm online, lowercase `m` is my bouncer.
