### ISSUE TITLE
How do I override method call in method I am injecting into

### ISSUE THREAD

**Issue by VRCube** [SpongePowered/Mixin#239]
![](http://cubxity.hypixel.life/7ac8afe.png)
I would like to override these 4 method calls with my own code, How could I do that?
Inject Annotation: `@Inject(method = "drawSplashScreen", at = @At(value = "INVOKE", target = "net/minecraft/client/renderer/Tessellator.draw()V", shift = At.Shift.BEFORE))`

**Comment by Pokechu22** [comment]
Use [@Redirect](http://jenkins.liteloader.com/job/Mixin/javadoc/org/spongepowered/asm/mixin/injection/Redirect.html), or alternatively [@ModifyArgs](http://jenkins.liteloader.com/job/Mixin/javadoc/org/spongepowered/asm/mixin/injection/ModifyArgs.html).

**Comment by VRCube** [comment]
@Pokechu22 Any examples on those?

**Comment by VRCube** [comment]
Anyone else?

**Comment by mikroskeem** [comment]
[@Redirect](https://github.com/OrionMinecraft/Helios/blob/master/implementation/src/main/java/eu/mikroskeem/helios/mod/mixins/world/MixinPlayerList.java) example. Also consider using [MinecraftDev](https://github.com/minecraft-dev/MinecraftDev) plugin if you happen to use IntelliJ

**Comment by Zidane** [comment]
This repo is for issues with using Mixin, not to explain its usage. Read the javadocs, examples, or find others on github (there are many).
