### ISSUE TITLE
Out of memory JVM fully frozen

### ISSUE THREAD

**Issue by pKalju** [SpongePowered/Mixin#246]
Hello,

Please add fallbacks to when there is no more free RAM to run Mixin injections.

I'm not entirely sure if it's really out of memory, but I got the JVM to crash when I run a stress test (100% CPU usage) with only 1 GB of RAM.

I have a few mixin injection points when Minecraft is heavily allocating RAM to load in the World.

I'm not entirely sure why it crashes, but it might be one of these launch arguments.
`-Xmx2G -Xms2G -Xmn1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -client -d64 -XX:+DisableExplicitGC -XX:+UseParNewGC -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true`

Thank you,
Kalju.

**Comment by gabizou** [comment]
Can you provide evidence pointing to Mixins being at fault?

**Comment by DemonWav** [comment]
Or just close this ridiculous, stupid issue.

**Comment by pKalju** [comment]
Interesting how I can't replicate the JVM fully freezing "crash" any more

**Comment by mikroskeem** [comment]
>Please add fallbacks to when there is no more free RAM to run Mixin injections

wat

In my opinion adding such fallback would be completely useless as JVM will run soon out of memory anyway.

**Comment by Mumfrey** [comment]
This issue is frivolous, closing as invalid.
