### ISSUE TITLE
GuiButton class not mixed

### ISSUE THREAD

**Issue by VRCube** [SpongePowered/Mixin#248]
Hello there,
My MixinGuiButton is not mixed, in dev env it does work but not when I launch the client from launcher with tweakclass. 

> ### Info
> Mapping: NOTCH stable_20 <br />
> Source: https://github.com/HyperiumClient/Hyperium

Please review this issue ASAP, thanks.
- Cubxity

**Comment by Mumfrey** [comment]
Logs?

**Comment by VRCube** [comment]
there is no error or any logs about mixin

**Comment by Mumfrey** [comment]
>there is no error or any logs about mixin

Then what exactly are you asking me to fix? Either submit an actual bug report or demonstrate that you have done even basic troubleshooting on this issue to warrant investigation. So far you have

* Provided no basic information about the issue. There are a slew of reasons that your mixin might not be applied but you are too lazy to even bother submitting the debug logs or show the result of running an audit pass. As far as I'm concerned this might not even be a bug it might be user error.
* Submitted a link to a github page with no binaries, building the project just creates an installer which installs a broken launcher profile which doesn't run, so I can't even reproduce the issue locally.

This is **NOT A SUPPORT FORUM**, this is an **ISSUE TRACKER**. If you want support then use IRC.

**Comment by VRCube** [comment]
The program/project is not released yet, so installer won't work yet. Could I dm you the guide or something?

**Comment by Mumfrey** [comment]
The IRC channel is `#spongedev` on esper, when the `m` in my name is uppercase, I am online.
