### ISSUE TITLE
ClassCircularityError: scala/Predef$

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Mixin#252]
https://pastebin.com/wAXDrwha

SpongeForge issue: https://github.com/SpongePowered/SpongeForge/issues/1840

User reported that modifying Mixin to not transform scala library classes "fixes" it.

Cleaning up old tickets on SF issue tracker, is this still a problem? (Unsure if I missed a relevant commit). Is this something needing to be changed on SpongeForge end?

**Comment by Mumfrey** [comment]
Couldn't this just be readily fixed by adding a transformer exclusion for `scala.`, since really no transformers should be touching those classes anyway?

**Comment by Zidane** [comment]
@Mumfrey 

Thanks, I've added the transformer exclusion.

**Comment by Foxxtail1** [comment]
On which version of mixin was this fixed? Because the issue still exists. Getting this with OpenComputers.

**Comment by gabizou** [comment]
> On which version of mixin was this fixed? Because the issue still exists. Getting this with OpenComputers.

You have to add the `Scala.` to the transformer exclusion list, like [SpongeForge does](https://github.com/SpongePowered/SpongeForge/blob/1d4eca0ea9155fd5490227198d2fade911141328/src/main/java/org/spongepowered/mod/SpongeCoremod.java#L128).

**Comment by Foxxtail1** [comment]
I see, I just assumed that this change was applied globally. A malisisCore and SGCraft both use it and still give me those issues. I'll try to fix it with what you gave me, thanks :)
