### ISSUE TITLE
Extremely odd LinkageErrors

### ISSUE THREAD

**Issue by luacs1998** [SpongePowered/Mixin#26]
As described in ForgeEssentials/ForgeEssentialsMain#1333, some of my users have been encountering funny LinkageErrors when using Mixin-enabled versions of FE.

Sample log here, more in the linked issue: http://pastebin.com/WBUM0iLa

Is there any workaround I can use, or does any fixing have to be done on your part?

**Comment by Mumfrey** [comment]
Looking at the issue comment, is this now resolved?

**Comment by luacs1998** [comment]
Nope, not yet resolved.

What would the root cause be?

**Comment by Mumfrey** [comment]
Nope, more likely something is using ASM before I get a chance to exclude the package in [MixinBootstrap](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/launch/MixinBootstrap.java) which means ASM gets half-loaded in the ACL and half in the LCL. If I shade ASM instead in a different package then the cast exception wouldn't happen.

Basically the expectation is that the tweaker will take care of this but if another tweaker is getting in before it and accessing ASM first then it could cause this.

**Comment by luacs1998** [comment]
So would a workaround to be set TweakOrder at a high enough level to ensure the Mixin tweaker gets loaded first?

**Comment by Mumfrey** [comment]
TweakOrder is actually lowest-first. The issue is that the tweak has to be loaded after the FML tweaker in order for the coremod injection to work. You could try playing with the TweakOrder and see what results you get, but I believe the lowest value you'll get away with will be 1001 but don't quote me on that.

**Comment by luacs1998** [comment]
With the assistance of some users, I have tracked the problem down to the Mariculture mod. I will work with the developer on a solution, and will get back to you if there's anything more needed on your part.

**Comment by gFreezer** [comment]
The same thing happens when you try to load Sponge together with another coremod (tried with CodeChickenCore): http://pastebin.com/xBpnPqPX

Seems like this should definitely be fixed on Mixin's side

**Comment by luacs1998** [comment]
I tried to run FTB Infinity (which obviously includes CCC), and only encountered issues with mariculture.

**Comment by Zone22** [comment]
I also have experience this problem with sponge and CodeChickenCore. It's not fixed as of sponge 445 and forge 1371.
