### ISSUE TITLE
Add rename feature to @Shadow

### ISSUE THREAD

**Issue by cakoyo** [SpongePowered/Mixin#260]
#### Example:
(Mixin)
``` java
@Shadow(name = "lit") private boolean isLightPopulated;
```
(Target)
``` java
private boolean lit;
```
Then we can use `isLightPopulated` in our mixin codes instead of `lit`. This is very useful when use mixin to modify obfuscated classes (such as Spigot), and may an improvement version of `prefix`.

**Comment by gabizou** [comment]
I think what you're looking for is `aliases` which are available currently, but I'm not sure how you're aiming to remap mixins otherwise.

**Comment by cakoyo** [comment]
Oh, I saw that, thanks.
