### ISSUE TITLE
ClassNotFoundExceptions in InnerClassGenerator

### ISSUE THREAD

**Issue by Runemoro** [SpongePowered/Mixin#263]
An anonymous class inside a mixin causes a `ClassNotFoundException` in `InnerClassGenerator`: https://paste.dimdev.org/agetotuxeh.txt

The ClassNotFoundException randomly changes between these classes from one run to another:
 - org.spongepowered.asm.lib.commons.FieldRemapper
 - org.spongepowered.asm.lib.commons.AnnotationRemapper
 - org.spongepowered.asm.lib.commons.MethodRemapper

**Comment by gabizou** [comment]
Do you have some example of the mixin to reproduce the issue?

**Comment by Mumfrey** [comment]
> Do you have some example of the mixin to reproduce the issue? And version info?

The version info is in the stack trace, and this is clearly just a shading issue so I don't really need an example mixin.

**Comment by gabizou** [comment]
> The version info is in the stack trace, and this is clearly just a shading issue so I don't really need an example mixin.

Oh yeah, that's what I get trying to read things at 3am....

**Comment by Mumfrey** [comment]
@Runemoro give that a try, if it doesn't fully resolve the issue then re-open this issue.

**Comment by Runemoro** [comment]
@Mumfrey Thanks, that fixed it!
