### ISSUE TITLE
maxShiftBy has no effect

### ISSUE THREAD

**Issue by Runemoro** [SpongePowered/Mixin#265]
Setting `maxShiftBy` in a Mixin config has no effect, and this warning still appears:

> [00:36:59] [main/WARN] [mixin]: @Inject(@At("INVOKE")) Shift.BY=2 on mixins.vanillafix.crashes.json:MixinCrashReportCategory::handler$afterGetStacktrace$zzl000 exceeds the maximum allowed value 0. Increase the value of maxShiftBy to suppress this warning.

This is caused by `MAX_ALLOWED_SHIFT_BY ` ([in InjectionPoint](https://github.com/SpongePowered/Mixin/blob/2d410a79df9d4aa4ed1c5004603064849c3eac9a/src/main/java/org/spongepowered/asm/mixin/injection/InjectionPoint.java#L166)) being 0. I'm not sure if this is intentional, but if it is, what's the point of even having a `maxShiftBy` option? Also, the log message is misleading, and it should be different when `maxShiftBy` exceeds `MAX_ALLOWED_SHIFT_BY`.

**Comment by Mumfrey** [comment]
Looks like a typo, and I take the point about different message when the hard limit is exceeded.

**Comment by MadSciSlack** [comment]
@Inject(@At("INVOKE")) Shift.BY=2 on forge-dramaticdoors_forge.mixins.json:OpenDoorsTaskMixin::handler$cal000$injectStartP1 exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

This is still the same 6 years later.

**Comment by LlamaLad7** [comment]
Why do you need a shift by in the first place? It's inherently brittle and almost never necessary which is why the warning exists in the first place.

**Comment by MadSciSlack** [comment]
Please re-open this issue.

**Comment by Earthcomputer** [comment]
Considered the possibility that your modpack is using an outdated version of mixin?

**Comment by MadSciSlack** [comment]
> Considered the possibility that your modpack is using an outdated version of mixin?

Mods specify their own versions of Mixin and MixinExtras, don't they?  I built the modpack, and the only Mixin elements are those provided by / integrated with the mods and Forge itself.  This isn't at a "modpack" level as far as I can tell, nor do I have any control over what version of Mixin this and that things use.

**Comment by TheBearodactyl** [comment]
> Please re-open this issue.

bump
