### ISSUE TITLE
Redirect void which is in an anonymous inner class

### ISSUE THREAD

**Issue by pKalju** [SpongePowered/Mixin#268]
Hello, I need help figuring out how to redirect `displayGuiScreen` in the GuiDisconnected class.

```
protected void initGui() {
    this.multilineMessage = this.fontRenderer.listFormattedStringToWidth(this.message.getFormattedText(), this.width - 50);
    this.textHeight = this.multilineMessage.size() * this.fontRenderer.FONT_HEIGHT;
    this.addButton(new GuiButton(0, this.width / 2 - 100, Math.min(this.height / 2 + this.textHeight / 2 + this.fontRenderer.FONT_HEIGHT, this.height - 30), I18n.format("gui.toMenu", new Object[0])) {
        public void func_194829_a(double p_194829_1_, double p_194829_3_) {
            GuiDisconnected.this.mc.displayGuiScreen(GuiDisconnected.this.parentScreen);
        }
    });
}
```

I tried to do this, but this does nothing.
```
@Redirect(method = "initGui", ordinal = 0, at = @At(value = "INVOKE", target = "net/minecraft/client/Minecraft.displayGuiScreen(Lnet/minecraft/client/gui/GuiScreen;)V"))
private void onActionPerformed(Minecraft minecraft, GuiScreen guiScreenIn) {
    System.out.println("cool");
}
```

**Comment by Barteks2x** [comment]
You would probably need to target the inner class in your mixin, which would probably need to be done by string for it to work as you can't reference inner classes otherwise. If it can work at all.

**Comment by Pokechu22** [comment]
That actually isn't a lambda, but an anonymous inner class.  You can mix into it by using `@Mixin(targets="fully.qualified.class.Name$Inner")`, which would probably be something like `net.minecraft.client.gui.GuiDisconnected$1`.  However, I don't see this code in any of the versions of the game, so I'm not sure where you're even getting that inner class...

**Comment by pKalju** [comment]
This is Minecraft 1.13, they changed how buttons work, that is actionPerformed.
I checked the jar and indeed the class name is with $1.

I got it to work now, but I don't think this is a reliable solution, is claims there is an error with this, since it can't be found:
![cool](https://i.futureclient.net/0E6dqvrd.png)
