### ISSUE TITLE
Allow config inheritance

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#273]
Large projects like Sponge can end up with a significant number of Mixin config files. Many options (`minVersion`, `target`, `compatibilityLevel`, `injectors`, etc) will be identical across all of these configs.

To help reduce duplication, and to make it easier to maintain a large number of configs, it would be helpful if Mixin were to provide a simple inheritance options for Mixin configs. This could take the form of an optional 'parent' option, the options of which would be applied in the absence of an override in the child config.

**Comment by Mumfrey** [comment]
Yes! This is a really great idea.

**Comment by Mumfrey** [comment]
I assume that @Demonwav would need to add support to mcdev for this as well, since I assume he reads those values out of the config?

**Comment by Mumfrey** [comment]
Closed by ab935e061fbc48aa2c2d4b7ae6a020ae2f9cc633

**Comment by gabizou** [comment]
So, how does this work now in 0.8?

**Comment by Mumfrey** [comment]
Simply set the `parent` key in a configuration to the resource path of the parent config, all configuration aspects of the config will then be inherited unless *explicitly* defined in the child config.
