### ISSUE TITLE
Question: Target classes that extends and overrides...

### ISSUE THREAD

**Issue by TerminatorNL** [SpongePowered/Mixin#280]
First off, I love Mixin and all its capabilities. Thank you so much for all your effort.

However, I am struggling to target classes that extend a class.
For example:

```java
@Mixin(value = Base.class, priority = 1001)
public abstract class MixinBase  {
    @Inject(method = "doSomething", at = @At("HEAD"))
    public void crashOnDoSomething(CallbackInfo ci) {
        throw new RuntimeException("It worked!");
    }
}
```
Does not target
```java
public class Variant1 extends Base  {
    @Override
    public void doSomething() {
        //body to target
    }
}
```
and
```java
public class Variant2 extends Base  {
    @Override
    public void doSomething() {
        //body to target
    }
}
```
How do I target `Variant1` and `Variant2` without directly referencing it? (It's added by another mod, it may be present or not, and new mods may pop into existence without my knowledge extending `Base`)

I tried digging in the docs and existing issues, but I am not really sure what I am looking for, and if it even exists.

Thank you for your time.

**Comment by gabizou** [comment]
You won't be able to override sub classes if they do not call `super.doSomething()`. This is why Sponge does a lot of wraparounds or `@Redirect`s to ensure logic is called when you have subclassed classes.

**Comment by TerminatorNL** [comment]
Allright, I'll try that. Thank you
