### ISSUE TITLE
[1.10.2]Get problem when the compiled mod (using Mixin) was loaded with forge.

### ISSUE THREAD

**Issue by bxz2311196368** [SpongePowered/Mixin#285]
Get problem when the compiled mod (using Mixin) was loaded with forge ,but works well in IDEA development environment Debug.
log show error:
java.lang.NoClassDefFoundError: net/minecraft/block/BlockContainer
But I didn't modify "BlockContainer"
I only modify "ItemBucket"
full log: [https://paste.ubuntu.com/p/hVxKJszGFk/](https://paste.ubuntu.com/p/hVxKJszGFk/)
Code: [here](https://github.com/bxz2311196368/someusefulthings/blob/1.10.2/src/main/java/com/bxzmod/someusefulthings/mixinhandler/MixinItemBucketHandler.java)

**Comment by Mumfrey** [comment]
You are [doing something stupid](https://github.com/bxz2311196368/someusefulthings/blob/1.10.2/src/main/java/com/bxzmod/someusefulthings/asm/ItemBucketClassTransformer.java#L87) in your `ItemBucketClassTransformer` which I'd pick as the prime candidate.

Not a Mixin issue, your transformer is violating the transformer contract.

**Comment by bxz2311196368** [comment]
I comment it out, makes it do nothing.
And removed FMLCorePlugin attribute in build.gradle.
