### ISSUE TITLE
Mixin uses Guava 18.0 while Minecraft (1.8.X) provides only Guava 17.0

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#29]
Mixin is currently [referencing Guava 18.0 as dependency](https://github.com/SpongePowered/Mixin/blob/master/build.gradle#L80) while Minecraft 1.8.X only provides Guava 17.0. Therefore, using features of Guava 17.0 will fail on most implementations (and especially in Forge mods as Forge is using the Guava version provided by Vanilla).

Due to transitive dependencies, Guava gets also silently upgraded in projects referencing Mixin unless the Guava dependency gets explicitely excluded. That caused a few problems in Sponge for example where usages of Guava 18.0 were silently breaking running Sponge in production without noticing it at compile time. We should consider downgrading it in Mixin so unavailable features are not used and projects get the correct Guava dependency directly.

**Comment by Mumfrey** [comment]
I think I only ended up upgrading that reference because [a transitive dependency had it pegged at 18.0](https://github.com/MinecraftForge/Srg2Source/blob/master/build.gradle) and the 17.0 was being evicted anyway, so I think if I remove it then the transitive dependency will just evict the older version regardless.

**Comment by progwml6** [comment]
once we figure out which dep we can exclude it from that dependency

**Comment by Mumfrey** [comment]
I linked to it, it's srg2source. I can happily downgrade my reference with no issues.

**Comment by Mumfrey** [comment]
[Found a way to prevent srg2source evicting the older version](http://stackoverflow.com/questions/27004899/how-do-i-resolve-dependency-conflicts-with-gradle) so I've reverted to Guava 17.0, hopefully should work for Sponge as well but if it doesn't then we can just add the same declaration to the Sponge build script.
