### ISSUE TITLE
Mixin AP ignores @Dynamic, causing needless warnings and impossible to fix errors

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#290]
For example this optifine-specific mixin into `RenderList.class` and `VboRenderList.class`

```java

    @Dynamic @ModifyArg(method = "preRenderRegion",
            at = @At(value = "INVOKE", target = "Lnet/minecraft/client/renderer/GlStateManager;translate(FFF)V"),
            index = 1)
    private float drawRegionRedirect(float zero) {
        /* whatever */
    }
```

works fine at runtime but mixin AP fails with the following error:
```
/home/bartosz/Desktop/dev/java/Minecraft/CubicChunks/CubicChunks/1.12/build/sources/main/java/io/github/opencubicchunks/cubicchunks/core/asm/mixin/selectable/client/optifine/MixinRenderList.java:82: error: Unable to determine signature for @ModifyArg target method
    @Dynamic @ModifyArg(method = "preRenderRegion",
             ^
```

Using `remap=false` silences this error, but then the `GlStateManager.translate` part doesn't get a refmap entry. The mixin works fine after manually adding the missing refmap entry.

**Comment by Mumfrey** [comment]
`@Dynamic` is a decorator and has no contractual function:

From the javadoc:

> Decorator annotation for mixin elements whose targets are not available in the original class and are either fabricated or transformed at runtime. This annotation is purely for decoration purposes and has no semantic implications of any kind.

You need to disable remapping for the target and enable remapping for the injection point.

**Comment by Barteks2x** [comment]
I also have quite a few warnings that I really don't know how to deal with, and on Discord the only help I got was "they are just warnings, ignore them".

**Comment by Barteks2x** [comment]
There is currently no way to silence these warnings when mixing into classes modified by other mods:
```
warning: Cannot find target method for @Inject in <mixin name>
warning: Cannot find target for @Shadow field in <mixin name>
```
