### ISSUE TITLE
Add support for SuppressWarnings annotation in Mixin AP to allow silencing nuisance warnings

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#306]
I want to have zero warnings when compiling my code, but currently mixin makes this impossible. This is basically the same issue as #290 but since `@Dynamic` not helping is intentional, it was closed. But this still leaves no solution to silence the warnings.

Consider there is a class `X` (in my case `RenderChunk`) that some coremod (in my case, OptiFine) modifies by adding some fields (`renderChunkNeighboursValid` and `renderChunkNeighbours`), that I need to access within that my mixin.

Adding a `@Shadow` for these fields works perfectly fine when running the code, but mixin AP will show the following error, even with `remap=false`:
```
MixinRenderChunk.java:51: warning: Cannot find target for @Shadow field in net.minecraft.client.renderer.chunk.RenderChunk
    @Dynamic @Shadow(remap = false) private RenderChunk[] renderChunkNeighbours;
             ^
```

While it may not look like a big issue ("it's just warnings"), it makes it very hard to notice the meaningful warnings that I don't want to ignore in the compile output.

**Comment by Mumfrey** [comment]
Would adding support for the standard Java `@SuppressWarnings` annotation be sufficient? It would allow fine grained control of AP-generated warnings like this.

**Comment by Barteks2x** [comment]
Yes, that looks like a good idea. It's probably better than adding a separate annotation to silence each warning separately.
