### ISSUE TITLE
Mixin transformer needs to account for synthetic inner classes

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/Mixin#31]
**Stacktrace**: https://gist.github.com/zml2008/0d935592484363d6c601

**Relevant code**: https://github.com/SpongePowered/Sponge/blob/feature/permissions/src/main/java/org/spongepowered/mod/mixin/core/command/MixinSubject.java

I'm thinking this is related to the switch statement -- those sometimes create inner classes for some reason, and is part of the hasPermission method, which is what was being invoked when this error occurred.

**Comment by Mumfrey** [comment]
Ah yes, that old chestnut. I'll take a look at this now I'm back and see about handling the inner class shenanigans. Since it's synthetic I should be able to handle it gracefully.

**Comment by Mumfrey** [comment]
@zml2008 hopefully that should fix the issue for (static) synthetic inner classes used for switch table implementation but still allow non-static and non-synthetic inner classes to cause a crash. I've tested it locally but would be great if you could verify and report back.

**Comment by zml2008** [comment]
yup, seems to work. thanks!
