### ISSUE TITLE
Failure in optional mixin config results in required mixins being skipped

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#313]
If an `InvalidMixinException` occurs during the application of an optional mixin, Mixin will stop applying any further mixins applicable to the target class, and return the current transformed bytecode.

However, this can result in required mixins being skipped, if they had not yet been fully processed at the time the exception occured. This can result in extremely hard-to-diagnose bugs, since Mixin consumers do not expect that the game will continue to execute with some required mixins not applied.

**Comment by Mumfrey** [comment]
Ah ok, for sure this isn't the intended behaviour, will look into this.
