### ISSUE TITLE
Computer Language & Mixins

### ISSUE THREAD

**Issue by asbyth** [SpongePowered/Mixin#315]
so in this project called [Hyperium](https://github.com/HyperiumClient/Hyperium) we use mixins, and it's worked pretty well, up until we launched B17 in July of 2018
since then, users using a different computer language other than English weren't able to use the client due to it trying to read a different mapping or something of the sort
we had absolutely no idea how to fix this and weren't sure if it was our issue, or something to do with mixins

today, i checked a log file of someone having this issue again, and in our IMixinWorld class, we have an Invoker annotation calling isChunkLoaded(IIZ)Z, however, when looking at the log, it was trying to find the method ýsChunkLoaded(IIZ)Z, despite the code using an I, not a ý
to test the theory of the computer language messing with the mappings, i set my computer language to theirs (Turkish) and installed the client, and there's the problem, it's trying to get ýsChunkLoaded when in Turkish, and not isChunkLoaded

hopefully this issue can be fixed, as i currently have no way of knowing how to fix this, otherwise i'd make a pr fixing it
appreciate it 
@Mumfrey

**Comment by simon816** [comment]
If I was to guess, I'd say it's this here: https://github.com/SpongePowered/Mixin/blob/81a22a4f1d1cf59089bed40cdab4913860340c22/src/main/java/org/spongepowered/asm/mixin/gen/AccessorInfo.java#L257
[`toLowerCase`](https://github.com/SpongePowered/Mixin/blob/81a22a4f1d1cf59089bed40cdab4913860340c22/src/main/java/org/spongepowered/asm/mixin/gen/AccessorInfo.java#L412) doesn't specify a locale so it uses the system one.

We've had this problem before in SpongeCommon, https://github.com/SpongePowered/SpongeCommon/commit/b608aa1b881732f6c9f1cbe5460642916f92609a

**Comment by Mumfrey** [comment]
Interesting. Definitely not the intended behaviour. If @simon816 is right then fix should be fairly straightforward.

**Comment by asbyth** [comment]
this can also be solved with adding -Duser.country=US -Duser.language=en to the JVM arguments in the launcher

**Comment by mikroskeem** [comment]
>this can also be solved with adding -Duser.country=US -Duser.language=en to the JVM arguments in the launcher

That's more like a temporary workaround, proper solution would be indeed changing underlying toLowerCase/toUpperCase calls
