### ISSUE TITLE
Capture Locals with Redirects

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#324]
Currently, LocalCapture is only available through `Inject`, but it should be technically feasible to use `LocalCapture` with a `Redirect` (in the same fashion that they're appended to the parameter of the method).

**Comment by Barteks2x** [comment]
It has been already rejected in #163 and #110

**Comment by gabizou** [comment]
Yeah, kept trying to find the original issue, but couldn’t.
