### ISSUE TITLE
Mixin not working on forge when trying to @Overwrite a method

### ISSUE THREAD

**Issue by Technerder** [SpongePowered/Mixin#325]
I am currently in the process of writing a mod which removes the code within a base minecraft client method using Mixins, however it does not seem to work or print out any errors. How would I go about fixing this? 

Repo: https://github.com/Technerder/NoHurtcamMod (Not working)

I'd appreciate any and all help with fixing this.

**Comment by Barteks2x** [comment]
Mixin classes need to be in separate package. And whatever you are doing in the coremod class definitely doesn't look right. It appears to be forcing the mod to load. Mixin already does that for you (maybe not necessarily the same way) if you set properties in MANIFEST.MF right. For dev environment, it should work anyway.

**Comment by Technerder** [comment]
@Barteks2x  I've implemented your suggestions however, the mod still does not seem to be working, including (https://github.com/Technerder/NoHurtcamMod/blob/master/src/main/java/com/technerder/nohurtcammod/FMLLoadingPlugin.java#L30) which is never printed out.

**Comment by Barteks2x** [comment]
You don't make a custom tweaker with mixin. You use mixin tweaker. And in dev environment, you need a commandline argument to specify coremod to load (and you jsust make IFMLLoadingPlugin, and call your misin setup code in constructor).

**Comment by Technerder** [comment]
Would you happen to know of an example mod repository which contains an example of how I'd go about doing this? I'm somewhat confused by what you're saying.
