### ISSUE TITLE
Injecting into redirects from other mods breaks quickly between versions - Dynamic targets

### ISSUE THREAD

**Issue by TerminatorNL** [SpongePowered/Mixin#330]
Since #323, I lost compatibility with SpongeForge over incremental changes.
I have been using the following code to target redirected methods by SpongeForge:

```java
    @Dynamic(value = "onCallEntityUpdate is added by SpongeForge (redirect$onCallEntityUpdate$zme000)", mixin = MixinWorldServer.class)
    @Inject(method = "redirect$onCallEntityUpdate$zme000", at = @At("HEAD"), cancellable = true, require = 1)
    private void onCallEntityUpdate(Entity entity, CallbackInfo ci){
        if(IS_CONTROLLED_BY_TIQUALITY == false){
            TickHub.onEntityTick(entity);
            ci.cancel();
        }
    }
```

This works fine, but as soon as SpongeForge releases newer versions, targetting no longer works due to the method name changing. (eg: `zmd000` -> `zme000`)
```java
    @Dynamic(value = "onCallEntityUpdate is added by SpongeForge (redirect$onCallEntityUpdate$zme000)", mixin = MixinWorldServer.class)
    @Inject(method = "redirect$onCallEntityUpdate$zme000", at = @At("HEAD"), cancellable = true, require = 1)
    private void onCallEntityUpdate(Entity entity, CallbackInfo ci){
        if(IS_CONTROLLED_BY_TIQUALITY == false){
            TickHub.onEntityTick(entity);
            ci.cancel();
        }
    }
```
Is there a way to get a wild-card reference for the method suffix, or a cleaner way to reference it?

And if so, is it also possible for `@Shadow` references? I have the very same issue here:

```java

    @Dynamic(value = "onCallEntityUpdate is added by SpongeForge (redirect$onCallEntityUpdate$zme000)", mixin = MixinWorldServer.class)
    @Shadow protected abstract void redirect$onCallEntityUpdate$zme000(Entity entity);
```

The sourcecode for the entire class is available [here](https://github.com/TerminatorNL/Tiquality/blob/f8676af3dda0e44455ff4eab8d6713f74833a9e7/src/main/java/cf/terminator/tiquality/mixin/MixinWorldServerSponge.java) if you need more context.

I feel like you've probably already thought of this, and I might be missing something here.
Thanks in advance.

**Comment by Mumfrey** [comment]
Method names are conformed to avoid conflicts and also to defeat further transformation because by design the content of a redirect handler is not a suitable target for other injections or transformations.

> Is there a way to get a wild-card reference for the method suffix, or a cleaner way to reference it?

No, by design these are runtime-specific and can even change between runs if other mixins are involved, eg. mixins from another mod.

> And if so, is it also possible for `@Shadow` references?

No for the same reason. Handler methods are not designed to be accessed by other code.

Mixins can be transformed on load by other transformers, but the functionality you're talking about is intentionally not supported. If you need to interface with another mod you should be asking the mod to add a hook for the functionality you want, rather than trying to monkey-patch a handler.

**Comment by TerminatorNL** [comment]
All right, I understand that the architecture of Mixin doesn't allow for the 'monkey-patching' approach like I did here. Quite frankly, it's very ugly and I'd rather not have it.

I'd like to stay as far away from hacky solutions as I can, but realistically, I cannot expect the SpongeForge team to provide an API for my very specific scenario, which takes control of all in-world ticking behaviour and then returns control. Do you have any suggestions on how to proceed? I could make my own transformer, but I like the beauty that Mixin has.

**Comment by TerminatorNL** [comment]
I have decided to utilize `postApply` in the MixinConfigPlugin
```java
    @Override
    public void postApply(String target, ClassNode classNode, String mixin, IMixinInfo iMixinInfo) {
    }
```

Obviously, it's not as clean as Mixin, but it gets the job done.
If other people run into the same issue, here's how I worked around it: https://github.com/TerminatorNL/Tiquality/commit/13f4b71a9881d0de1d7bfe02b6210b575e21a92c
