### ISSUE TITLE
Mixin does not detect a re-entrance error while configs are still being loaded

### ISSUE THREAD

**Issue by simon816** [SpongePowered/Mixin#333]
It is well known that Mixin does not support re-entrant class transformers. I have found a minor issue where Mixin does not throw an error when a re-entrant transformer is detected. Of course later on an error is thrown but it is harder to track down the root cause as re-entrance is not mentioned in the error.

The misleading error thrown is `MixinTargetAlreadyLoadedException`, which suggests that mixin was loaded too late but this is not the case.

An example of this error is https://github.com/TeamWizardry/LibrarianLib/issues/77
```
Message : Critical problem: mixins.common.core.json:text.MixinTextComponentBase target net.minecraft.util.text.TextComponentBase was already transformed.
```

The problem stems from this part in `MixinTransformer`:
https://github.com/SpongePowered/Mixin/blob/2c72246fe0b67c145db5510e66c8873df18b5a9f/src/main/java/org/spongepowered/asm/mixin/transformer/MixinTransformer.java#L471-L496

If the `mixins` variable is not null (i.e. there are mixins for the target class) then `locked` must not be set. If the lock is set then a transformer must have been re-entrant.

When Mixin loads configs, it fetches the metadata for each mixin immediately, applying the transformer chain for each mixin's target.

Because this happens immediately then there is a chance that a required mixin is not known yet, in turn this causes the `mixins` variable from above to be null and Mixin believes it's safe to continue.

Here is an example to better illustrate the problem:

There are two runtime classes:
```
public class ClassA {
}
public class ClassB {
}
```
There are mixins for both these classes:
```java
@Mixin(ClassA.class)
public class MixinClassA {
}
@Mixin(ClassB.class)
public class MixinClassB {
}
```
With this config:
```json
    "mixins": [
        "MixinClassA",
        "MixinClassB"
    ]
```

A re-entrant transformer does something like this:
```java
public class ReentrantTransformer implements IClassTransformer {

    @Override
    public byte[] transform(String name, String transformedName, byte[] basicClass) {
        if (name.equals("ClassA")) {
            try {
                Class.forName("ClassB", true, Launch.classLoader);
            } catch (ClassNotFoundException e) {
            }
        }
        return basicClass;
    }

}
```

`MixinClassA` is first in the config so a `MixinInfo` object is created for it, which pulls `ClassA` through the transformer chain.

The `ReentrantTransformer` forces `ClassB` through the classloader, therefore through the transformer chain.

At this point Mixin should identify the re-entrance and throw:
https://github.com/SpongePowered/Mixin/blob/2c72246fe0b67c145db5510e66c8873df18b5a9f/src/main/java/org/spongepowered/asm/mixin/transformer/MixinTransformer.java#L495
`locked` is in fact `true`, but `mixins` is null because the existance of `MixinClassB` is not known yet.

So the problem is that re-entrance checking is not forward-looking.

**Comment by Mumfrey** [comment]
This is an interesting race condition with Mixin self-pwning itself. I think this can be addressed by pushing the re-entrance lock during the delegate transformer run (which neatly wraps it with the LW code as well) and that should address this problem, though I need to do some testing.

Thanks for the detailed report.
