### ISSUE TITLE
Any way for a Mixin to remove a method call?

### ISSUE THREAD

**Issue by Frontear** [SpongePowered/Mixin#334]
This is more specific to Minecraft 1.8.9, I'd like to remove the `System.gc()` calls littered all over the Minecraft.class, as it just ends up slowing down the client for little benefit. I'm aware I could probably just create an `IClassTransformer`, then just iterate through all the methods, find all `INVOKESTATIC` methods that are from `java/lang/System` and call `gc`, then just remove it, but I'd like to have a mixin way to go about it. Is it possible?

**Comment by gabizou** [comment]
You can redirect all `System.gc()` calls to do nothing, but you cannot *remove* a method call.

Something like
```java
@Redirect(method = "doSomething", at = @At(value = "INVOKE", target = "Ljava/lang/System;gc()V", remap = false))
private static void ignoreGcCall() { } // literally will do nothing
```

**Comment by Frontear** [comment]
The issue I've found is that this only removes for a particular method. Is there no way to just target all of them without needing to specify each and every one?

**Comment by Barteks2x** [comment]
Overwrite the method with an empty one?

**Comment by Frontear** [comment]
I mean target all System.gc across the entire class.

Here's a sort of class representation:

```java
class MyClass {
	public void myMethod() {
		System.gc();
		// ...
		System.gc();
	}

	public void exit() {
		System.gc();
		// ...
	}

	public void launch() {
		// ...
		System.gc();
	}
}
```

I want to be able to find all of the System.gc, without needing to `@Redirect(target = "myMethod"), @Redirect(target = "exit"), @Redirect(target = "launch")`.

**Comment by gabizou** [comment]
You don't need to make multiple redirects for multiple methods, there's the array method targeter [as shown in the javadocs](https://github.com/SpongePowered/Mixin/blob/2c72246fe0b67c145db5510e66c8873df18b5a9f/src/main/java/org/spongepowered/asm/mixin/injection/Redirect.java#L230-L236) it's possible to redirect the same method called in multiple instances of different methods like so:
```java
@Redirect(method = { "run()V", "freeMemory()V", "someOther()V" }, at = @At(value = "INVOKE", target = "Ljava/lang/System;gc()V", remap = false))
private void ignoreSystemGcCalls() {
  System.err.println("nulled system.gc call.");
}
```

**Comment by Mumfrey** [comment]
You can also just use `*` as a selector for every method.

**Comment by DemonWav** [comment]
Wouldn't the easier solution here be to just add the `-XX:+DisableExplicitGC` JVM argument? It will make the calls to `System.gc()` do nothing (and is a flag I generally recommend for Minecraft).

**Comment by Frontear** [comment]
@gabizou I assume that's valid then, since I was avoiding that because the MinecraftDev plugin was warning me that it was invalid:

![minecraft_dev](https://user-images.githubusercontent.com/31909298/61597279-8ee46b80-abdc-11e9-98d4-e6d9ab301fa5.png)

@DemonWav I honestly agree, but this is a forge mod, and not everyone is knowledgeable enough to know where to apply this kind of setting. As a result, they'd be unable to appreciate the performance benefit, additonally, this is meant to be a performance enhancing mod as well, so I can't just skip this feature.

**Comment by DemonWav** [comment]
@Frontear the plugin is missing a few Mixin features.
