### ISSUE TITLE
Allow warning to be suppressed for public Mixin#targets when target is in the default package

### ISSUE THREAD

**Issue by tomocrafter** [SpongePowered/Mixin#338]
When I used default package class in Mixin's targets, I get this warning.
We can not import default package so please allow using default package in Mixin
`warning: Mixin target ~~~ is public and must be specified in value @Mixin(targets = {"~~~"})`

**Comment by Barteks2x** [comment]
This is just a warning and shouldn't really affect anything. I think I remember running into it and ignoring it.

**Comment by tomocrafter** [comment]
> This is just a warning and shouldn't really affect anything. I think I remember running into it and ignoring it.

Yes, It works, just a warning but I think it is correct usage of targets so I hope it will be allowed.

**Comment by Pokechu22** [comment]
Assuming it already works, I'd say it _is_ already "allowed" &mdash; you're instead asking for the warning to be suppressed.  I agree with that; this seems like a valid use case and the only way to achieve it.

**Comment by Mumfrey** [comment]
So you're actually asking to allow the warning to be suppressed? The warning is intentional in the first place so I'm not going to just remove it. I'm ok with allowing `@SuppressWarnings` to be used here though.
