### ISSUE TITLE
Invoker on constructors

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#339]
It doesn't seem to be currently supported, and this is the only thing that's missing for me right now. Could that be supported or is there a technical reason not to do it? (considering that static methods and fields appear to be supported (but not documented), it should be possible)

**Comment by Mumfrey** [comment]
This is actually something @gabizou suggested a few weeks ago and it makes perfect sense as long as the mixin only has one target. I'd agreed in principle that this was something I will add support for so I guess this issue just formalises that.
