### ISSUE TITLE
"Unexpected state" when static accessor is used first before the target class is loaded

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#342]
As an example in Minecraft, I have the following accessor mixin:
```java
@Mixin(NoiseGeneratorImproved.class)
public interface INoiseGeneratorImproved {
    @Accessor("GRAD_X") static double[] getGradX() {
        throw new Error("INoiseGeneratorImproved failed to apply");
    }
    // a few others
}
```
And I use `INoiseGeneratorImproved.getGradX()` during mod initialization, which is before the class `NoiseGeneratorImproved` would normally be loaded. This causes the following exception: https://gist.githubusercontent.com/Barteks2x/55da975f53a12b489a6bec98e7aba011/raw/116a2ea44fdba1037e534cc7f1692e7b5553ea6d/mixin-exception.log

An easy workaround is to manually load the class, but I don't think this is intended (and looks fixable to me) so I'm reporting it here.

**Comment by Mumfrey** [comment]
Ah hmm ok. At least I put that sanity check in there! Otherwise this would have ended up with a very cryptic `NoSuchMethodError` at runtime.

The class doesn't actually need to be loaded the mixin just needs to be conformed, which should be fairly simple to fix.

**Comment by gabizou** [comment]
Wait, static accessors worked all this time as long as the target class was already classloaded?
