### ISSUE TITLE
Modify method return value

### ISSUE THREAD

**Issue by Lortseam** [SpongePowered/Mixin#364]
Hello, I would like to know what's the best way to modify the return value of a method. The method looks like this:
```java
public boolean isGlowing() {
    return this.glowing || this.world.isClient && this.getFlag(6);
}
```
I know I could overwrite this method, but then I would have to copy the whole code in my own method which is not a good solution I think. Also I would like to avoid to modify the `glowing` field.

**Comment by Mumfrey** [comment]
Using a *cancellable* `@Inject` at `RETURN` will do what you want:

```java
@Inject(method = "isGlowing()Z", at = @At("RETURN"), cancellable = true)
private void customIsGlowing(CallbackInfoReturnable<Boolean> cir) {
    cir.setReturnValue(whatever);
}
```

**Comment by Mumfrey** [comment]
Please not that this is **not a support forum**, this is an **issue tracker**. Please direct questions to `#mixin` channel on the SpongePowered discord next time.
