### ISSUE TITLE
Disable JDK 8 doclint

### ISSUE THREAD

**Issue by bloodmc** [SpongePowered/Mixin#37]
https://github.com/SpongePowered/Sponge/blob/master/build.gradle#L253

Can this be added to Mixin build.gradle? Currently, the latest Mixin master is failing in travis due to javadoc errors. Adding the fix above will ignore javadoc errors.

**Comment by Mumfrey** [comment]
Seems like a good idea. I honestly can't wrap my head around how unspeakably dumb the javadoc parser in JDK8 is :/
