### ISSUE TITLE
Mixin breaking ASM class transformers

### ISSUE THREAD

**Issue by DarkShadow44** [SpongePowered/Mixin#370]
I'm using forge for 1.7.10 and am trying to gradually move from ASM to Mixin.
However, when enabling the Mixin Tweaker class, my ASM breaks.
I already tried Mixin-0.8, but that didn't help either.

For reference, this is how I added it: https://github.com/DarkShadow44/CptsModdingLight/commit/c5cb72333234c3402dc1f88ef60b4d4b5491575d
For eclipse I'm using
`--tweakClass org.spongepowered.asm.launch.MixinTweaker --mixin mixins.lightoverhaul.json`
and
`-Dfml.coreMods.load=coloredlightscore.src.asm.ColoredLightsCoreLoadingPlugin`.

The transformers actually still run, I get all the debug messages - but the changes are not done properly, since it doesn't work anymore.
As noted, ASM breaks after "gradlew reobf", but works perfectly fine in eclipse.

**Comment by Mumfrey** [comment]
> my ASM breaks.

Breaks how? Do you actually have an error message?

> The transformers actually still run, I get all the debug messages - but the changes are not done properly, since it doesn't work anymore.

"It"? What doesn't work any more?

I can tell you for sure that Mixin doesn't "break ASM class transformers" because it's been in use for years with no issues. This tracker is also for bugs not a support forum. Please use [`#mixin` on the Sponge discord server](https://discord.gg/tBcwxz2) if you wish for assistance. Please **also** provide some actual details (logs, error messages, etc) about your problem and be less vague.

**Comment by DarkShadow44** [comment]
I can't provide an error message, since I don't have one. I don't know what's going wrong here, only that, when I add `"TweakClass": "org.spongepowered.asm.launch.MixinTweaker"` into the Manifest, my mod breaks. The transformers run, everything looks fine. But the mod doesn't work anymore. That's all I have.

A log is here: https://pastebin.com/UqReTAhQ
Compiled version of the problematic mod: https://www.mediafire.com/file/ydsgc9qhaxv7nb5/ColoredLightsCore-1.4.c5cb723.jar/file

It's a mod that adds colored glowstone, for example "red glowstone". It's supposed to light up red (in the darkness) but it doesn't.
Howerver, remove
`TweakClass: org.spongepowered.asm.launch.MixinTweaker`
from the Manifest of the mod, and it suddenly works again.
Sorry for being vague, but actually testing is the only way to see a difference here.

Doesn't this classify as bug? I mean, it's good to hear it usually works, but currently, for me, it doesn't.

**Comment by DarkShadow44** [comment]
I guess it's related to the fact that the class transformers run multiple times... (Also see https://github.com/SpongePowered/Mixin/issues/309).
The transformers I "inherited" from the original mod seem to have the same issue. I didn't know about that contract, sorry for that - Mixin is probably right here.
