### ISSUE TITLE
Javadocs do not seem to build properly

### ISSUE THREAD

**Issue by luacs1998** [SpongePowered/Mixin#38]
When building javadocs for mixin, the build fails with the following errors:

`<redacted>\Mixin\src\main\java\org\spongepowered\asm\mixin\transformer\meta\MixinRenamed.java:37: error: reference not found`
 `* {@link org.spongepowered.asm.mixin.transformer.meta.MixinInfo} and`
`<redacted>\Mixin\src\main\java\org\spongepowered\asm\mixin\transformer\meta\MixinRenamed.java:38: error: reference not found`
` * {@link org.spongepowered.asm.mixin.transformer.MixinPreProcessor} to mark`

Am I doing something wrong, or is something that shouldn't be there happening?

**Comment by Mumfrey** [comment]
That's not on the latest master it was fixed in commit [88932f117e05546659d1360f2ce83f489f27c688](https://github.com/SpongePowered/Mixin/commit/88932f117e05546659d1360f2ce83f489f27c688) a few days ago.

**Comment by luacs1998** [comment]
Ah, sorry.
