### ISSUE TITLE
`@ModifyVariable` gives poor error message when trying to modify multiple locals

### ISSUE THREAD

**Issue by Earthcomputer** [SpongePowered/Mixin#382]
When I forgot the `ordinal` on `@ModifyVariable`, it gave me the following error message:
```
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method getCrustHeight(I)I in worldgentests.mixins.json:MixinChunkProviderGenerate failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap world-gen-tests-refmap.json
```
which is unclear. Instead it could tell me that I can't match more than one local in implicit mode.

Relates to #381

**Comment by Mumfrey** [comment]
I can definitely raise this as a warning, throwing an exception early would break the expect/require contract. If I can propagate the failure of a single selector up to the injector itself then the detail could also be included in the requirement failure message posted above, which would save hunting for it in the logs.

This can definitely be improved, I will make this enhancement.
