### ISSUE TITLE
A question relating to compatibility.

### ISSUE THREAD

**Issue by luacs1998** [SpongePowered/Mixin#39]
Why does Mixin even require the use of the system class loader anyway?

I've been having to troubleshoot various compatibility issues between FE and various other coremods, and seem to keep running into the problem of ASM being split-loaded by the LaunchClassLoader before I get a chance to call MixinBootstrap.

**Comment by Mumfrey** [comment]
To be honest, discussing this the other day in IRC I think we came to the conclusion that submitting a PR to FML to exclude ASM at startup is going to be the most effective solution. The only other option is to shade ASM with a package rename

**Comment by luacs1998** [comment]
Shall I do it, or do you want to? It seems to be a one-line change for both the 1.7.10 and 1.8 branches...

Also, I fail to understand why the Mixin subsystem is so particular about having ASM be loaded by the system class loader.

**Comment by Mumfrey** [comment]
It's because mixin itself has to load in the system classloader, so if ASM is not then it causes the split where some classes get loaded in the wrong classloader, since it doesn't matter where ASM gets loaded it's just easier and cleaner to push ASM up into the system classloader as well.

**Comment by luacs1998** [comment]
Ah, I see. Thanks for the explanation.

**Comment by luacs1998** [comment]
Is there any progress on this?
