### ISSUE TITLE
Miscellaneous issues concerning private targets and accessors for them

### ISSUE THREAD

**Issue by Johni0702** [SpongePowered/Mixin#390]
## Context
While trying to debug https://github.com/FabricMC/fabric-mixin-compile-extensions/issues/1, I came across three things which don't appear right to me but I may just be missing the bigger picture for some of them.
#### Disclaimer
I was debugging using Fabric's Mixin fork and mapping provider. The respective sources code concerning the issues appears to be the same in fork and upstream though, so I'm reporting it here.

## Invalid field descriptor
Putting a breakpoint at the line which emits the warning, I noticed this difference in the `desc` field of `targetField.asMapping(false).move(target.getName())` (first with `$`, then with `.`):
![](https://i.johni0702.de/kJy8O.png)
![](https://i.johni0702.de/TTWpo.png)

The extra `()` appears to be because the following line is using `getDesc` when it probably should be using `getAccessorDesc`:
https://github.com/SpongePowered/Mixin/blob/1252714215e03bdca681e9841475d326cdeef475/src/ap/java/org/spongepowered/tools/obfuscation/AnnotatedMixinElementHandlerAccessor.java#L297
As I understand, that code path is used for `@Pseudo` mixins, so this should be affecting those regardless of the other two issues (have not explicitly tested that though).

## Invalid private targets
This begs the question: Why does it take the `@Pseudo` mixin path when the original mixin (the one with `$`) isn't a `@Pseudo` mixin?
Afaict, it does because the `target` `TypeHandle` is an imaginary one, i.e. one without a backing `element`:
![](https://i.johni0702.de/foKEm.png)
It shouldn't be but more on that later. Looking at where it is initialized:
https://github.com/SpongePowered/Mixin/blob/1252714215e03bdca681e9841475d326cdeef475/src/ap/java/org/spongepowered/tools/obfuscation/AnnotatedMixin.java#L218-L227
To me it looks like either `getTypeHandle` must return `null` when it cannot find the target class (it doesn't unless the package is invalid as well) or the else-if-condition must be extended to `(type == null || type.isImaginary())`. I can't tell from context or the javadocs which one it should be.
To be clear, even for obviously non-existent types, `getTypeHandle` still returns a handle:
![](https://i.johni0702.de/kN8Q9.png)

## Looking up private targets which are inner classes
Last but not least, why does `getTypeHandle` not return a real TypeHandle for valid `Outer$Inner` targets in the first place?
This seems to be as simple as a missing `.replace('$', '.')` on the argument for the call to `getTypeElement`:
https://github.com/SpongePowered/Mixin/blob/1252714215e03bdca681e9841475d326cdeef475/src/ap/java/org/spongepowered/tools/obfuscation/AnnotatedMixins.java#L627
cause that appears to be what it demands:
![](https://i.johni0702.de/dzrFJ.png)

**Comment by Mumfrey** [comment]
I'm not sure to be honest it's been a while since I touched the code in question so I'll have to look into it. I do seem to remember originally requesting inner classes from mirror with `.` not working when I was developing the AP but doing it with `$` did. I wonder if that was just a quirk of whatever JDK I was using at the time. It's possible that the fix is to try calling `getTypeElement` with both `.` and `$` and only going down the pseudo code path if both fail.
