### ISSUE TITLE
Question: Arrange IClassTransformer after Mixin is complete, not before.

### ISSUE THREAD

**Issue by TerminatorNL** [SpongePowered/Mixin#393]
While Mixin has served me well in the beginning, but I have encountered several issues that show that Mixin is not suitable for my use: #280  #323 #330.

I have created my own `IClassTransformer` which works beautifully in environments where Mixin is not present.

However, when SpongeForge is added, SpongeForge's Mixins will fail as they happen after my transformations have taken place.

I want to let other mods such as SpongeForge perform all their tasks **_before_** I transform the class. If I perform my tasks before SpongeForge's Mixins have been applied, the Mixins will fail. However, my transformer is perfectly capable of handling the transformation after SpongeForge's Mixins have been applied.

How would I go about configuring my IClassTransformer to run **_after_** Mixin has finished processing? Currently, I am not using Mixin as a library, but I am familiar with it and willing to integrate it if needed.

![image](https://user-images.githubusercontent.com/13693773/79674177-d423e100-81e0-11ea-8daf-b66cc5df010e.png)

Thanks in advance.

**Comment by Mumfrey** [comment]
Part of mixin's core contract is that it is working with bytecode in its final form, without this guarantee things like `@Overwrite` are basically meaningless. This doesn't mean that you can't transform stuff after mixin has touched it, just that those transformations have to happen inside mixin.

It also doesn't preclude using mixin-specific decorations such as `@Final` in your transformer.

The simplest way to apply changes after another mixin is to use a mixin with higher priority. You can either put your changes in the mixin or make it a no-op (empty) mixin and put your arbitrary transformations in the `postApply` method of a companion plugin.

**Comment by TerminatorNL** [comment]
All right, thank you
