### ISSUE TITLE
Allow directly inject a static invoke into target method

### ISSUE THREAD

**Issue by xuetaolu** [SpongePowered/Mixin#394]
I want to use the export mixin class to redefine in a already launch minecraft forge game.
So, Compare to original class the mixin should not add or delete methods.

For, `@overwrite`, It's done. Compare to original class, the mixin class doesn't add or delete method.
etc '@overwrite' the `getBlockReachDistance` method in class `PlayerControllerMP`

But, for `@Inject`, It's not done. Compare to original class, the mixin class add a new method like `method&injectzzz` and only inject a call of this new method into target method.

Can mixin inject the whole method byte code into target method rather than a new method call?

**Comment by xuetaolu** [comment]
I found that inject is a structure that adds a member method like `new_method` to the target class and then adds `if (new_method(new CallbackInfo())) return;` at the injection point. 

Can it directly add a static method call to the target class?

For example,
`@Mixin(Minecraft.class)
public abstract class MixinMinecraft {
    @Inject(method = "runTick", at = @At("HEAD"))
    public static void staticInjectMethod(Minecraft self, CallbackInfo callbackInfo){
        // do something
    }
}`

And directly inject a static invoke into the `runTick` method of Minecraft.class without adding a new method to Minecraft.class

**Comment by Mumfrey** [comment]
I don't understand your use-case here. The entire point of an injector calling a *handler method* is that the contract of the method signature is defined and therefore its behaviour when injected (in terms of stack and locals) is understood by the injector. Arbitrary methods do not carry this guarantee and therefore are not supported.

I also see no use-case for this anyway since in the situation you're talking about, you simply have your handler method call the static method, or any other method of your own choosing.

**Comment by xuetaolu** [comment]
Take `liquidbase `as an example,
[https://git.liquidbounce.net/CCBlueX/LiquidBase](url)

This is part of `MixinEntityPlayerSP.java`

```
    @Inject(method = "onUpdateWalkingPlayer", at = @At("HEAD"))
    private void preMotion(CallbackInfo callbackInfo) {
        EventManager.callEvent(new MotionUpdateEvent(MotionUpdateEvent.State.PRE));
    }
```

I export the mixin `EntityPlayerSP.class` and use jd-gui to decompile it, found that a new member method was added to `EntityPlayerSP.class`
```
    @MixinMerged(mixin = "net.ccbluex.liquidbase.injection.mixins.MixinEntityPlayerSP", priority = 1000, sessionId = "002c2564-5f8d-4e51-ae73-1afccb2ed747")
    private void handler$preMotion$zza000(CallbackInfo callbackInfo) {
        EventManager.callEvent((Event)new MotionUpdateEvent(MotionUpdateEvent.State.PRE));
    }
```

and insert a call of `handler$preMotion$zza000` in the `onUpdateWalkingPlayer` method
```
    public void onUpdateWalkingPlayer() {
        handler$preMotion$zza000(new CallbackInfo("onUpdateWalkingPlayer", false)); // <- HERE
        // more code
```

I want to directly inject the method code into target method without adding method like this: 
```
    public void onUpdateWalkingPlayer() {
        // directly inject the method code
        EventManager.callEvent((Event)new MotionUpdateEvent(MotionUpdateEvent.State.PRE)); 
        // more code
```

Maybe it is complex to merge two method body. So I consider directly injecting a static method call of an external class, such as the MixinEntityPlayerSP.class.

Maybe  `MixinEntityPlayerSP.java` should change to
```
    @Inject(method = "onUpdateWalkingPlayer", at = @At("HEAD"))
    public static void preMotion(CallbackInfo callbackInfo) {
        EventManager.callEvent(new MotionUpdateEvent(MotionUpdateEvent.State.PRE));
    }
```

and the exported mixin `EntityPlayerSP.class` in jd-gui maybe 
```
    public void onUpdateWalkingPlayer() {
        // directly inject a static invoke to MixinEntityPlayerSP.preMotion
        MixinEntityPlayerSP.preMotion(new CallbackInfo("onUpdateWalkingPlayer", false));
        // more code
```

**Comment by Mumfrey** [comment]
No. I already explained why mixin *will not* do this. You haven't described any actual reason for what you're describing except for "I want it", and I'm saying, "there must be a use-case because 'I want' isn't good enough".

What you're asking for does not have any benefit, and makes injectors considerably more complex and less reliable for no reason at all.

**Comment by xuetaolu** [comment]
For Minecraft of NetEase edition, you cannot add mods in the usual way, because NetEase Launcher will detect all game files including mods and libraries every time the game is started. But mod can be injected with javaagent. For mods using mixin, you can use your own launcher to start the game with the mixin mod added, get all the modified mixin class, inject the mod file after starting the game using the NetEase launcher, and then put the mixin class redefine in. . Here, because of redefine restrictions, the mixin class can not add methods relative to the original class, but there is no problem when adding calls to static methods of other classes in the method body. It works when using jbe (java bytecode editor).

**Comment by xuetaolu** [comment]
Can it be achieved by implementing an IMixinConfigPlugin?

**Comment by Mumfrey** [comment]
Sorry this is not something Mixin is designed to do, it invalidates too many assumptions embedded elsewhere in Mixin and will not be supported. You must use a regular transformer to do what you want.
