### ISSUE TITLE
CallbackInjector LVTs clip from double length variables

### ISSUE THREAD

**Issue by Chocohead** [SpongePowered/Mixin#398]
Closely connected to #353 and #337 although slightly different than both. Throwback to FabricMC/Mixin#17 when I said I'd get around to reporting this.

---
If you take the example method:
```java
public List<String> names;
public void method(long big, double accurate) {
	boolean flag = Math.random() > accurate;

	if (!names.isEmpty()) {
		for (String name : names) {
			if (!flag) {
				System.out.println(name);
			}
		}
	}
}
```
Then aim to inject at the `println` statement capturing the locals up to that point, you'd end up with a Mixin something like...
```java
@Inject(method = "method", at = @At(value = "INVOKE", target = "Ljava/io/PrintStream;println(Ljava/lang/String;)V"), locals = LocalCapture.CAPTURE_FAILHARD)
public void method(long big, double accurate, CallbackInfo info, boolean flag, String name, Iterator<String> it) {		
}
```
This is all well and good. Say we were to accidentally miss the `String` parameter off however, that is to capture only the `boolean` and the `Iterator`. Mixin then presents you with a rather unexpected error:
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in com/chocohead/example/Example::method(JD)V has incompatible changes at opcode 42 in callback com/chocohead/example/Example::method.
Expected: [Z, Ljava/util/Iterator;]
   Found: []
```

Now this in and of itself is not entirely unexpected as the LVT no longer matches what we're capturing. But Mixin claims to find nothing which as we know isn't true as matching the 3 LVT entries that are actually present works fine.

---
Take the second example, closely connected to the first, and attempt the same goal:
```java
public void otherMethod(short small, float inaccurate) {
	boolean flag = Math.random() > inaccurate;

	if (!names.isEmpty()) {
		for (String name : names) {
			if (!flag) {
				System.out.println(name);
			}
		}
	}
}
```
```java
@Inject(method = "otherMethod", at = @At(value = "INVOKE", target = "Ljava/io/PrintStream;println(Ljava/lang/String;)V"), locals = LocalCapture.CAPTURE_FAILHARD)
public void otherMethod(short small, float inaccurate, CallbackInfo info, boolean flag, String name, Iterator<String> it) {
}
```
Like before this works. Say we were to make the same mistake and miss the `String` parameter you would expect to get the same result. Instead...
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in com/chocohead/example/Example::otherMethod(SF)V has incompatible changes at opcode 43 in callback com/chocohead/example/Example::otherMethod.
Expected: [Z, Ljava/util/Iterator;]
   Found: [Z, Ljava/lang/String;]
```
Rather than finding nothing Mixin has now found what we should have had instead if we were to capture the first two locals. Seems suspicious if changing two double size parameter types to two single ones has fixed things.

---
Finally try adding the `String` parameter onto the end, a more expected way of compiling the method perhaps:
```java
@Inject(method = "method", at = @At(value = "INVOKE", target = "Ljava/io/PrintStream;println(Ljava/lang/String;)V"), locals = LocalCapture.CAPTURE_FAILHARD)
public void method(long big, double accurate, CallbackInfo info, boolean flag, Iterator<String> it, String name) {
}
	
@Inject(method = "otherMethod", at = @At(value = "INVOKE", target = "Ljava/io/PrintStream;println(Ljava/lang/String;)V"), locals = LocalCapture.CAPTURE_FAILHARD)
public void otherMethod(short small, float inaccurate, CallbackInfo info, boolean flag, Iterator<String> it, String name) {		
}
```
Now running both of these suggests being suspicious of the parameter type size is well placed:
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in com/chocohead/example/Example::method(JD)V has incompatible changes at opcode 42 in callback com/chocohead/example/Example::method.
Expected: [Z, Ljava/util/Iterator;, Ljava/lang/String;]
   Found: [Ljava/util/Iterator;]

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in com/chocohead/example/Example::otherMethod(SF)V has incompatible changes at opcode 43 in callback com/chocohead/example/Example::otherMethod.
Expected: [Z, Ljava/util/Iterator;, Ljava/lang/String;]
   Found: [Z, Ljava/lang/String;, Ljava/util/Iterator;]
```
Suddenly our original method can now find one local, yet the second method is finding all three as expected. Thus our original method is printing locals two slots too late, it perfect to fit two `top`s in for the `long` and `double` parameters.

The reason for this comes down to what [`CallbackInjector#generateBadLVTMessage`](https://github.com/SpongePowered/Mixin/blob/0.8.1/src/main/java/org/spongepowered/asm/mixin/injection/callback/CallbackInjector.java#L530-L539) does. Whilst for the expected set of parameters it used the argument length for the callback, the found is based on the `frameSize` of the callback. For single sized types this is fine as the locals match up to the frames. For double sized types however this causes the `top` parts to start shoving locals out from being printed. When [fixing this originally](https://github.com/FabricMC/Mixin/pull/17/files#diff-2deb5f3c4ddf9c326a3149dfa631c429R520-R521) I just took the point of view that the expected should be what the callback should've been and found what is actually coming from the LVT. In retrospect that is perhaps a more useful error for dev whilst in production the Mixin is more what is expected, but either way I'd suggest switching out 
```java
List<String> found = CallbackInjector.summariseLocals(callback.getDescriptor(), callback.frameSize + (callback.target.isStatic ? 1 : 0));
```
with
```java
//#inject turns any CallbackInfo[Returnable]s into null which is skipped from being shown by #summariseLocals
//so it isn't technically necessary if you didn't want to but expected does the line above
List<String> found = CallbackInjector.summariseLocals(callback.localTypes, callback.frameSize + 1);
```
as a starting point so that both are at least helpful in discovering what could be wrong with an injector.

**Comment by Mumfrey** [comment]
Thanks for the detailed report. The entirety of `CallbackInjector` is going to be gone soon but for the time being I can definitely apply a fix for this specific problem.
