### ISSUE TITLE
@Redirect different constructor in the same method is considered conflict

### ISSUE THREAD

**Issue by Windmill-City** [SpongePowered/Mixin#403]
@Redirect conflict. Skipping mixin.json:MixinAdvMachTEs->@Redirect::ctorProxy2(Lic2/core/block/TileEntityInventory;Ljava/lang/String;I)Lic2/core/block/invslot/InvSlotOutput; with priority 1000, already redirected by mixin.json:MixinAdvMachTEs->@Redirect::ctorProxy(Lic2/core/block/TileEntityInventory;Ljava/lang/String;ILic2/api/recipe/IMachineRecipeManager;)Lic2/core/block/invslot/InvSlotProcessableGeneric; with priority 1000
![QQ截图20200515011615](https://user-images.githubusercontent.com/14292823/81964804-b2841100-9649-11ea-84b1-ae520638b05a.png)
these two Redirect redirect two different constructor，they shouldn't be considered conflict.

**Comment by Mumfrey** [comment]
> these two Redirect redirect two different constructor

No they don't. you haven't actually specified a target in your `@At` so it's matching all.

This issue tracker is for **bugs** in Mixin, not for general help. Please use the discord channel to request help if you run into problems.
