### ISSUE TITLE
Lombok not working with the Mixin Annotation Processor

### ISSUE THREAD

**Issue by qlow** [SpongePowered/Mixin#404]
Hey guys,
whenever I add Lombok to my build.gradle,
`compileOnly 'org.projectlombok:lombok:1.18.12'
annotationProcessor 'org.projectlombok:lombok:1.18.12'`
the Mixin annotation processor stops doing its job. No refmap is being generated.

I don't think it has anything to do with MixinGradle because in the info log it still says "Adding source set 'main' to mixin processor". The compiler outputs the following warning:
`warning: The following options were not recognized by any processor: '[reobfNotchSrgFile, outRefMapFile, defaultObfuscationEnv, outNotchSrgFile, reobfSrgFile, outSrgFile]'`

So I think it has something to do with the annotation processor. Does someone know or has already dealt with this issue?

MixinGradle 0.6-SNAPHOT
Mixin 0.7.11

Best regards,
Jan

**Comment by Mumfrey** [comment]
0.7.11 is an outdated version, please check that the behaviour persists with 0.8.1.

However realistically this doesn't strike me as a bug, as it's incredibly unlikely that the AP is still running but somehow not working. What's more likely is that your configuration change is altering some behaviour in gradle and you need to manually specify the mixin AP or something like that. So I'd suggest checking the gradle documentation.

If the mixin AP masthead is still being logged but the AP is somehow not working, then that's something I can fix. But I can't fix general gradle configuration issues on mixin's end.

**Comment by qlow** [comment]
Thanks! It works with this code:
`annotationProcessor 'com.google.guava:guava:21.0'
    annotationProcessor 'org.apache.logging.log4j:log4j-core:2.0-beta9'
    annotationProcessor 'org.ow2.asm:asm-tree:6.2'
    annotationProcessor 'org.ow2.asm:asm-commons:6.2'
    annotationProcessor 'org.ow2.asm:asm-util:6.2'
    annotationProcessor 'com.google.code.gson:gson:2.2.4'
    annotationProcessor 'org.spongepowered:mixin:0.8.1'

    compileOnly 'org.projectlombok:lombok:1.18.12'
    annotationProcessor 'org.projectlombok:lombok:1.18.12'`

I know that is not a very good looking solution but it's the only one I found. If I just add "annotationProcessor 'org.spongepowered:mixin:0.8.1'" it doesn't add its dependencies and the processor fails.
