### ISSUE TITLE
Capture local variables in @ModifyConstant and @Redirect

### ISSUE THREAD

**Issue by rikka0w0** [SpongePowered/Mixin#417]
Looks like with current version of mixin, it is not possible to capture local variables (not method args) in @ModifyConstant and Redirect, they only give me the option to capture the method args. It will be much better if ModifyConstant and Redirect implements local variable capture, like `@Inject(locals = LocalCapture.CAPTURE_FAILHARD)`.

Target method:
`setBlockState(BlockPos pos, BlockState state, boolean bl)`
Local variables before the injection location:
`int i, int j, int k, ChunkSection chunkSection, boolean bl2, BlockState blockState, Block block, Block block2`

Currently only this is valid:
```
	@ModifyConstant(method = "setBlockState", constant = @Constant(classValue = BlockEntityProvider.class, ordinal = 0))
	public boolean patchwork_setBlockState_instanceof_BlockEntityProvider(Object object, Class<?> clazz, BlockPos pos, BlockState state, boolean bl)
```

Looking for this:
```
	@ModifyConstant(method = "setBlockState", locals = LocalCapture.CAPTURE_FAILHARD), constant = @Constant(classValue = BlockEntityProvider.class, ordinal = 0))
	public boolean patchwork_setBlockState_instanceof_BlockEntityProvider(Object object, Class<?> clazz, BlockPos pos, BlockState state, boolean bl, int i, int j, int k, ChunkSection chunkSection, boolean bl2, BlockState blockState, Block block, Block block2)
```

**Comment by Mumfrey** [comment]
As I've explained many times already, local capture *as it exists now* is going away in the next version but one (though of course supported for backward compatibility). So **no** it won't ever be supported elsewhere, instead it's being replaced with a new system which will be available on all injectors which makes it obsolete.
