### ISSUE TITLE
MappingProvider.getFieldMapping passes an invalid field discriptor to MappingProvider when using @Accessor

### ISSUE THREAD

**Issue by modmuss50** [SpongePowered/Mixin#419]
# MappingProvider.getFieldMapping passes an invalid field discriptor to MappingProvider when using @Accessor

MappingProvider.getFieldMapping in some cases is passing an invalid MappingField.desc of 

`Lnet/minecraft/client/particle/ParticleManager$SimpleSpriteProvider;sprites:()Ljava/util/List;` 

![](https://s.modm.us/idea64_2020-06-21_18-27-36.png)

The expected field desc should be:

`Lnet/minecraft/client/particle/ParticleManager$SimpleSpriteProvider;sprites:Ljava/util/List;`

Note the removal of the `()`

## A Possible Cause

After a bit of digging I believe this is happening here: 

[AnnotatedMixinElementHandlerAccessor.java#L297 ](https://github.com/FabricMC/Mixin/blob/fabric-0.8/src/ap/java/org/spongepowered/tools/obfuscation/AnnotatedMixinElementHandlerAccessor.java#L297 )

It appears to be passing the accessor's method desc including the paramters, I believe it should just be the methods return value. My guess is this went untoiced with MCP as it does not handle the concept of field descriptors.

## An Example

_Note: All minecraft names are in yarn names_

We can came across this issue with the following [mixin](https://github.com/FabricMC/fabric/blob/3c9757ac95ea15379aaa3bcca2ff70217a046ee3/fabric-particles-v1/src/main/java/net/fabricmc/fabric/mixin/client/particle/ParticleManagerAccessor.java). 

The accessor is an innner interface to a parent mixin if that helps. I have tried with `.` and `/` package seperators to no avail, as well as removing the accessor target as its not needed here.

```java
	@Mixin(targets = "net/minecraft/client/particle/ParticleManager$SimpleSpriteProvider")
	interface SimpleSpriteProviderAccessor {
		@Accessor("sprites")
		List<Sprite> getSprites();
	}
```

The target class (`ParticleManager.SimpleSpriteProvider`) looks something similar to this:

```java
   @Environment(EnvType.CLIENT)
   class SimpleSpriteProvider implements SpriteProvider {
      private List<Sprite> sprites;

      public void setSprites(List<Sprite> sprites) {
         this.sprites = ImmutableList.copyOf(sprites);
      }
   }
```

# Conclusion

[fabric-mixin-compile-extensions](https://github.com/FabricMC/fabric-mixin-compile-extensions) could also strip the paremeters from the MappingField before looking up the obfuscated name.

Please dont hesisate to ask for more info if there is something I have missed. I am also in the sponge discord if thats easier.

**Comment by modmuss50** [comment]
I have applied a workaround succesfully here: [MixinMappingProviderTiny.java](https://github.com/FabricMC/fabric-mixin-compile-extensions/commit/f049573bc0ae4d50fc6fc37ea391f6f38cf429f3#diff-29c4bc213970c3e1b6845c51b9934ba3R86).

Its just a simple change that removes any method params that turned up in the field desc

**Comment by Johni0702** [comment]
Same issue as the `Invalid field descriptor` section of https://github.com/SpongePowered/Mixin/issues/390 I believe.

**Comment by modmuss50** [comment]
Yes, you are correct. 

That would have saved me a lot of time lol 👍
