### ISSUE TITLE
[Suggestion] Allow interface mixins for default methods

### ISSUE THREAD

**Issue by Leo40Git** [SpongePowered/Mixin#421]
See title. I have no idea how hard/easy/dumb this would be to implement, so if it's not possible, just tell me and close the issue.

**Comment by Mumfrey** [comment]
You can already do this as long as you set the compatibility level to JAVA_8 or higher.

**Comment by Klotzi111** [comment]
> 
> 
> You can already do this as long as you set the compatibility level to JAVA_8 or higher.

Can you please give a example of how to do this?
I tried:
Interface:
```Java
package test;

public interface TestInterface {

	public double getValue();

	public default boolean greaterThan(double b) {
		double a = getValue();
		boolean c = a > b;
		return c;
	}

}
```
Mixin Class:
```Java
package mixin.test;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.gen.Invoker;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import test.TestInterface;

@Mixin(TestInterface.class)
public interface MixinTestInterface {

	@Invoker("getValue")
	public abstract double getValue();

	@Inject(at = @At(value = "HEAD"), method = "greaterThan(D)Z", cancellable = true)
	public default void greaterThan(double b, CallbackInfoReturnable<Boolean> cir) {
		double a = getValue();
		boolean c = a < b;
		cir.setReturnValue(c);
	}

}
```

And when using the interface in code i get a exception and this message:
```Mixin apply failed klori-client.mixins.json:test.MixinTestInterface -> test.TestInterface: org.spongepowered.asm.mixin.transformer.throwables.InvalidInterfaceMixinException klori-client.mixins.json:test.MixinTestInterface->@Inject::greaterThan(DLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V is not supported on interface mixin method handler$zgn000$greaterThan [ -> PREINJECT Applicator Phase -> klori-client.mixins.json:test.MixinTestInterface -> Prepare Injections]```

I am using compatibility level: JAVA_16

How i used the interface:
Implementation Class:
```Java
package test;

public class TestImplementation implements TestInterface {

	public final double value;

	public TestImplementation(double value) {
		this.value = value;
	}

	@Override
	public double getValue() {
		return value;
	}

}
```
test code:
```Java
	TestInterface ti = new TestImplementation(100);
	System.out.println("greaterThan: " + ti.greaterThan(10));
```

**Comment by Mumfrey** [comment]
You're trying to use *injectors* in interface mixins, this is not currently supported (see #318) as some of Mixin is not currently interface-hierarchy-aware, so you can currently use overwrites but not injectors.

**Comment by Klotzi111** [comment]
Thanks for the quick response. It would be nice if a Injector works with interface methods. But for my current case overwriting the whole interface method is sufficient.
