### ISSUE TITLE
[Suggestion] Better constructor injection

### ISSUE THREAD

**Issue by rikka0w0** [SpongePowered/Mixin#424]
Currently mixin does not support injection to arbitrary location inside a class constructor.
The explaination on the wiki page is `This restriction is imposed because there is no other sensible way to be sure that the class is fully initialised before calling your handler code.`.

However I do think there should be a workaround. Can we make a `private static void` method inside the target class which contains the injection code? In this way, the generated method will not have access to those uninit class fields and methods.

I will be really appreciated if this limitation can be removed in the future, my project urgently require this feature, as the workaround will be super hacky.

**Comment by JBYoshi** [comment]
What are you trying to do?

**Comment by rikka0w0** [comment]
I want to Inject and Redirect some calls within the constructor but after the super constructor is called.

**Comment by Mumfrey** [comment]
You can already do this. Redirects aren't restricted anyway and Inject is gated behind a user-facing mechanism designed to stop casual use of unsafe injects but expose the functionality to those with sufficient experience.
