### ISSUE TITLE
Constant modifier injection fails to match multiple instances/ordinals.

### ISSUE THREAD

**Issue by Deadgye** [SpongePowered/Mixin#427]
Minecraft Version: 1.16.1
SpongePowered MIXIN Subsystem Version: 0.8+build.18

Vanilla Class snippet: net/minecraft/client/gui/screen/ingame/InventoryScreen
```
   protected void init() {
      if (this.client.interactionManager.hasCreativeInventory()) {
         this.client.openScreen(new CreativeInventoryScreen(this.client.player));
      } else {
         super.init();
         this.isNarrow = this.width < 379;
         this.recipeBook.initialize(this.width, this.height, this.client, this.isNarrow, (AbstractRecipeScreenHandler)this.handler);
         this.isOpen = true;
         this.x = this.recipeBook.findLeftEdge(this.isNarrow, this.width, this.backgroundWidth);
         this.children.add(this.recipeBook);
         this.setInitialFocus(this.recipeBook);
         this.addButton(new TexturedButtonWidget(this.x + 104, this.height / 2 - 22, 20, 18, 0, 0, 19, RECIPE_BUTTON_TEXTURE, (buttonWidget) -> {
            this.recipeBook.reset(this.isNarrow);
            this.recipeBook.toggleOpen();
            this.x = this.recipeBook.findLeftEdge(this.isNarrow, this.width, this.backgroundWidth);
            ((TexturedButtonWidget)buttonWidget).setPos(this.x + 104, this.height / 2 - 22);
            this.isMouseDown = true;
         }));
      }
   }

   protected void drawBackground(MatrixStack matrices, float delta, int mouseX, int mouseY) {
      RenderSystem.color4f(1.0F, 1.0F, 1.0F, 1.0F);
      this.client.getTextureManager().bindTexture(BACKGROUND_TEXTURE);
      int i = this.x;
      int j = this.y;
      this.drawTexture(matrices, i, j, 0, 0, this.backgroundWidth, this.backgroundHeight);
      drawEntity(i + 51, j + 75, 30, (float)(i + 51) - this.mouseX, (float)(j + 75 - 50) - this.mouseY, this.client.player);
   }
```

Mixin functions snippet:
```
	@ModifyConstant(method = "init", constant = @Constant(intValue = 104), require = 2)
	private int onInitModifyXVal(int value) {
		return value + 22;
	}
	@ModifyConstant(method = "drawBackground", constant = @Constant(intValue = 51), require = 2)
	private int onDrawBackgroundModifyXVal(int value) {
		return value + 22;
	}
```
`[17:35:46] [main/INFO] (Minecraft) [STDERR]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method onInitModifyXVal(I)I in pocketmobs.mixins.json:InventoryScreenMixin failed injection check, (1/2) succeeded. Scanned 1 target(s). No refMap loaded.`

The latter injection for drawBackground works and replaces both instances of 51 with 73. However the former injection for init only matches 1 out of the 2 instances of 104. Based on the behavior of the GUI while debugging it should be matching the first instance but not the second.

**Comment by Mumfrey** [comment]
The second occurrence of `104` that you see in the code is inside a lambda method. A syntax for effectively specifying lambda targets is in the works (see #355). However in this case you can target the lambda method directly. Note that `method` is an array so you can specify both target methods in the single injector.

**Comment by Deadgye** [comment]
My apologies if this should be obvious, but what would be the method value to target the lambda method directly in this case? I tried following the javadoc breadcrumbs from ModifyConstant to ITargetSelector to MemberInfo and found some generic examples of syntax, but couldn't figure out what syntax targets the lambda method inside the init method.
