### ISSUE TITLE
@ModifyVariable with LOAD or STORE doesn't respect slice

### ISSUE THREAD

**Issue by Earthcomputer** [SpongePowered/Mixin#429]
I made the following mixin in Fabric:
```java
@Mixin(Schemas.class)
public class MixinSchemas {
    @ModifyVariable(method = "build", slice = @Slice(from = @At(value = "CONSTANT", args = "intValue=1466")), at = @At(value = "STORE", ordinal = 0))
    private static Schema fixBlockEntityType(Schema schema1466, DataFixerBuilder builder) {
        builder.addFixer(new ChoiceTypesFix(schema1466, "multiconnect: fix block entity type", TypeReferences.BLOCK_ENTITY));
        return schema1466;
    }
}
```
When looking at the resulting class with `mixin.debug.export`, I noticed that it was injected near the very start of the method, well before the `from` node in the slice, acting as if the slice wasn't there.

It seems this is caused by `BeforeLoadLocal#find` using `method.instructions` and not respecting any slices which may be present.

**Comment by Mumfrey** [comment]
Derp.
