### ISSUE TITLE
Missing "target" injection for @Invoker, causing Undecorated Accessor error

### ISSUE THREAD

**Issue by PhiPro95** [SpongePowered/Mixin#430]
If two identical accessor or invoker methods are injected into the same class, the mixin processor inspects their `target` fields to check if they target the same method and raises an error if the don't match. If this `target` field cannot be found on the method that is injected second, an `Undecorated Accessor` error is raised.
This field is injected into the `@Accessor` and `@Invoker` annotations via
```java
protected ITargetSelector initTarget() {
    MemberInfo target = new MemberInfo(this.getTargetName(this.specifiedName), null, this.targetFieldType.getDescriptor());
    this.annotation.visit("target", target.toString());
    return target;
}
```
in `AccessorInfo`. However, this method is overridden in `InvokerInfo`
```java
@Override
protected ITargetSelector initTarget() {
    if (this.type == AccessorType.OBJECT_FACTORY) {
        return new MemberInfo(Constants.CTOR, null, Bytecode.changeDescriptorReturnType(this.method.desc, "V"));
    }
        
    return new MemberInfo(this.getTargetName(this.specifiedName), null, this.method.desc);
}
```
which misses the call to `this.annotation.visit("target", target.toString());`.

This causes two identical `@Invoker`s to fail whereas two identical `@Accessor` s are fine.

**Comment by Mumfrey** [comment]
Thanks for making an issue. Will fix this.

**Comment by williewillus** [comment]
Bump to get this fixed, as it affects a lot of mods whenever they're used together. Thanks :)
