### ISSUE TITLE
FMLCorePluginContainsFMLMod not supported by MixinTweaker

### ISSUE THREAD

**Issue by luacs1998** [SpongePowered/Mixin#44]
This causes issues where if the MixinTweaker, a coremod, and a regular mod are in the same jar file, only the MixinTweaker and the coremod are loaded, but the regular mod is ignored.

As [I mentioned here](https://github.com/SpongePowered/Mixin/pull/41#issuecomment-96361978), this is due to the MixinTweaker removing the container file from the "loaded coremods" list, which forces FML to look through the container file again, but this only happens during the coremod discovery phase.

A solution [as implemented here](https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/core/preloader/FELaunchHandler.java#L63) would be to also add the container file to the list of files that FML should reparse in the regular mod loading phase (usually, this is handled by FML [here](https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/relauncher/CoreModManager.java#L353), but as the file is treated with tweaker handling processes, that code does not execute).

I will make a PR by the end of this week to resolve this issue, but if you want, feel free to take the linked code from FELaunchHandler. Note that those code makes some assumptions (for example, there is always a @Mod in the same file), which should be catered to with proper checks.

**Comment by Mumfrey** [comment]
I'm still getting to grips with FML so apologies for the oversight and thanks for the example. I will incorporate the logic into the mixin tweaker.

**Comment by luacs1998** [comment]
FML itself already has the FMLCorePluginContainsFMLMod marker so you can just check for that. Let me know if you need any other assistance.

**Comment by Mumfrey** [comment]
Ok thanks will do. I'll poke you on IRC if I need any help.

**Comment by luacs1998** [comment]
Sure thing, you know where to find me, or just send me a PM and I'll respond when I can.

**Comment by Mumfrey** [comment]
Hey luacs could you let me know if this solves the issue. I don't actually have an actual mod to test with so I can only assume that since this is based on the code in your tweaker that it works as expected.

**Comment by Mumfrey** [comment]
I have rebased [feature/shade-asm](https://github.com/SpongePowered/Mixin/tree/feature/shade-asm) on this commit now, so that version 0.4 on the branch also contains these changes.

**Comment by luacs1998** [comment]
Okay. I need to update mixin on my end, and pair this with some classloader changes, so I can only get you a reply Friday at the earliest.

**Comment by Mumfrey** [comment]
Ok no worries, if there are any changes I'll update them on maven.

**Comment by luacs1998** [comment]
On further investigation, I can't get Mixin to run beside only a normal FMLMod without having the ForceLoadAsMod and FMLPluginContains stuff run before the initialization of the FML coremod. I've made a local patch on my side and it seems to work.

Also, how do I get feature/shade-asm to build? It didn't build properly until I added a few lines to build.gradle.

**Comment by Mumfrey** [comment]
Ah ok, so you're saying that if you move the (current) line 134 to line 160 then it works as expected?

`feature/shade-asm` should build without problems, although as I mentioned you should use the artefact from my maven repo instead. Make sure your branch is up to date if trying to build it.

**Comment by luacs1998** [comment]
Hang on, let me commit what I have so you can take a look. I haven't actually tested it wth Sponge or anything else yet.

**Comment by Mumfrey** [comment]
Oh I see, well I can change it to that way around and check it still works with sponge and if so I'll apply the change.

**Comment by Mumfrey** [comment]
Yep, tested and works fine so I've pushed the changes. Just waiting on your feedback on the other branch before I merge it.
