### ISSUE TITLE
Mixins with invalid target descriptors that would fail a build work when run in a dev environment

### ISSUE THREAD

**Issue by Sollace** [SpongePowered/Mixin#440]
*and cause the mixin to be applied to a method that they don't (probably shouldn't) match.

The result of this is having mixins that work in development but generate unnecessary headaches further down the line when they fail the build condition, or that might make their way into production since testing them normally doesn't produce any sort of error.

**What I expected to happen:** The game should have crashed with an exception saying it did not find the target method.

**What actually happened:** The game did not crash, and the mixin was applied to a method that it should not have been able to match given the incorrect descriptor.

Below is a more detailed description of my setup and how exactly I managed to encounter this weird... bug?

The method I'm injecting into looks like this (located in net.minecraft.client.render.GameRenderer):

    public static float getNightVisionStrength(LivingEntity livingEntity, float f)

And it has a target descriptor that should look like this when used in a mixin:

    getNightVisionStrength(Lnet/minecraft/entity/LivingEntity;F)F

Now I wrote my mixin like this (details omitted):

    @Mixin(GameRenderer.class)
    abstract class MixinGameRenderer {
        @Inject(method = "getNightVisionStrength(FJLnet/minecraft/entity/LivingEntity;F)F",
               at = @At("HEAD"),
               cancellable = true)
        private static void onGetNightVisionStrengthHead(LivingEntity entity, float tickDelta, CallbackInfoReturnable<Float> info) {
        }
    }

You will notice it has an ever so slightly, hard to notice typo. Do you see it? There's an additional "FJ" - float and long that snuck in there when copying from another method.

What this means is that the target descriptor _does not match_ any known (or existing) methods in that class, and indeed it doesn't, as when doing a build through gradle it fails and produces the following two errors, as expected:

    warning: Cannot find target method for @Inject in net.minecraft.client.render.GameRenderer
        @Inject(method = "getNightVisionStrength(FJLnet/minecraft/entity/LivingEntity;F)F",
        ^
    error: No obfuscation mapping for @Inject target getNightVisionStrength
        @Inject(method = "getNightVisionStrength(FJLnet/minecraft/entity/LivingEntity;F)F",
        ^

This is **correct**.

Based on these I wouldn't expect the game to even run when there are mixins that cannot find their target methods, 
however, the problem arises when I do run the project in my IDE (as I normally do to test my code - building with gradle is usually the last step to obtain a jar I cna distribute):

When I run the game it "works", and I don't mean it "prints a warning and keeps running with my callback never being executed" I mean it **works**. The mixin is applied to the intended method, and the callback is executed as desired, somehow _despite_ the descriptor not actually being correct!

I would understand it behaving like this when I specify only he method name in the @Inject annotation, however I've given it a full explicit method descriptor. Not only that, but it also doesn't even match the callback method I've given! Either one of those two things should be enough to make the annotation processor panic.

**Comment by Mumfrey** [comment]
Ok that's... unexpected.

Can you clarify the following points:
* When you say "run the game" in the IDE and it breaks, is that via the gradle `runClient` task or via a generated run configuration from `genBlahRuns`?
* Does the same behaviour happen in production?

Also just as a side note to your question:

> Based on these I wouldn't expect the game to even run when there are mixins that cannot find their target methods,

You can elevate mixin-failed-to-apply errors to crashes by setting the `required` key to `true` in the config. This way you can have mixins which fail to apply but don't matter in one config, and "important" mixins which you want to cause a crash in another.

**Comment by Sollace** [comment]
> 
> 
> Ok that's... unexpected.
> 
> Can you clarify the following points:

Certainly. I'm running the game through the IDE (in this case Eclipse) using the generated run configs. I haven't been able to confirm in production, as I'm unable to obtain a jar that could be loaded in a production environment (gradlew build fails with the above errors)

> You can elevate mixin-failed-to-apply errors to crashes by setting the required key to true in the config. This way you can have mixins which fail to apply but don't matter in one config, and "important" mixins which you want to cause a crash in another.

I do believe I am already using that. All of my mods have `"required": true,` at the top of their mixin config, since that is the template I work from.

The issue here isn't that the mixins aren't being applied, though. They are being applied, but they're being applied to the wrong method (or in this case a method that does not exactly match the indicated target).

**Comment by Mumfrey** [comment]
Ah I guess it's not triggering a failure because of the bad match then. I'll look into it when I have a second and see what's going on.

**Comment by Mumfrey** [comment]
Can you confirm the version of Mixin you're using as your example above doesn't exhibit this error under 0.8.1 on 1.16.3 in dev environment.

**Comment by Sollace** [comment]
@Mumfrey I logs I have indicate Mixin 0.8.1:

    [20:09:44] [main/INFO] (mixin) SpongePowered MIXIN Subsystem Version=0.8.1

Sorry, I should probably mention that I'm using fabric on 1.16.2. After looking at other issues I'd hoped that you would have assumed such. Perhaps there's something different in the version of mixins they have?

The method is named using the yarn mappings.

**Comment by Mumfrey** [comment]
Well your example linked above works as expected (errors) with stock Mixin under MCP, I converted your example to MCP and broke it in the same way (added FJ):

```java
@Mixin(GameRenderer.class)
abstract class MixinGameRenderer {
    @Inject(method = "getNightVisionBrightness(FJLnet/minecraft/entity/LivingEntity;F)F",
           at = @At("HEAD"),
           cancellable = true)
    private static void onGetNightVisionStrengthHead(LivingEntity entity, float tickDelta, CallbackInfoReturnable<Float> info) {
    }
}
```

and it crashes on apply:

```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException:
    Critical injection failure: @Inject annotation on onGetNightVisionStrengthHead could not
    find any targets matching 'getNightVisionBrightness(FJLnet/minecraft/entity/LivingEntity;F)F'
    in net.minecraft.client.renderer.GameRenderer. No refMap loaded. [PREINJECT Applicator Phase
    -> mixins.116test.json:MixinGameRenderer -> Prepare Injections ->  
    -> handler$zzb000$onGetNightVisionStrengthHead(Lnet/minecraft/entity/LivingEntity;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
```

Which isn't conclusive proof that it's a bug in fabric's fork but unless you can identify some other environmental factor which might be triggering it, I'm going to assume it is until you can provide a replication case for MCP.

> Sorry, I should probably mention that I'm using fabric on 1.16.2. After looking at other issues I'd hoped that you would have assumed such. Perhaps there's something different in the version of mixins they have?

Unless otherwise stated I *always* assume people are reporting bugs here for Mixin itself, not a fork.

**Comment by Mumfrey** [comment]
Closing since I don't see that there's anything further that can be done with this issue.
