### ISSUE TITLE
Re-entrance detected during prepare phase, this will cause serious problems. Error Crashes forge with exit code 0

### ISSUE THREAD

**Issue by EpicPuppy613** [SpongePowered/Mixin#441]
Minecraft Version: 1.16.2

Forge Crashing when launching latest.log here:
[https://pastebin.com/6e8eW2y7](https://pastebin.com/6e8eW2y7)

**Comment by Mumfrey** [comment]
This was already fixed in 9f5191d1009f11c0142a068e13991901a50eb46a and already pulled into forge, your forge is out of date.

**Comment by EpicPuppy613** [comment]
Issue still persists with forge version 33.0.61(latest)

**Comment by Johni0702** [comment]
> Issue still persists with forge version 33.0.61(latest)

That's cause 33.0.61 is not the latest version (at time of writing it's 34.1.1).
34.0.8 is where the fix landed.
