### ISSUE TITLE
Certain mixins on Forge mods will crash when using certain versions of Java 8

### ISSUE THREAD

**Issue by TelepathicGrunt** [SpongePowered/Mixin#445]
So I have found is if I mixin into JigsawPattern.getMaxSize lambda, SingleJigsawPiece.getBoundingBox head, or SingleJigsawPiece.func_236843_a_ head, the mixins will crash when using 8u242 java or jdk-8.0.252.09-hotspot AdoptOpenJDK Java with this unhelpful crash report: https://hatebin.com/oetyghzicz

-------
### Background

So originally, I was using mixins to try and make my mod Blame be able to state what Template Pool was trying to generate a non-existent structure nbt file. The first mixin I did was to the lambda in JigsawPattern.getMaxSize like so:
https://github.com/TelepathicGrunt/Blame/blob/9b356c6cdf5b81a6c68d9077c31878f03dcecb70/src/main/java/com/telepathicgrunt/blame/mixin/JigsawPatternMixin.java#L35-L46

I had to use the * selector as I was told that any mixin into lambdas on Forge tends to cause issues when not using *. I do that, everything works, and then I very quickly get this bug report that it crashes lol https://github.com/TelepathicGrunt/Blame/issues/4 

I isolated the issue to only when my mod is running with the above mixin and I assumed the issue was because I was trying to mixin into a lambda. All my other mixins works perfectly fine. So, I replaced the problematic mixin with one that injects to the head of SingleJigsawPiece.getBoundingBox instead:
https://github.com/TelepathicGrunt/Blame/blob/be48a0699e508a44bdce660f03727f753cac27a7/src/main/java/com/telepathicgrunt/blame/mixin/SingleJigsawPieceMixin.java#L28-L38

That too also crashed. I changed the mixin's method to SingleJigsawPiece.getBoundingBox instead: `Lnet/minecraft/world/gen/feature/jigsaw/SingleJigsawPiece;getBoundingBox(Lnet/minecraft/world/gen/feature/template/TemplateManager;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/Rotation;)Lnet/minecraft/util/math/MutableBoundingBox;` 
and that too crashed. Finally, I tested changing the mixin to inject at SingleJigsawPiece.getDataMarkers head and it works!

So here I had three methods (where interestingly, JigsawPattern.getMaxSize calls SingleJigsawPiece.getBoundingBox which calls SingleJigsawPiece.func_236843_a_ in a chain. Possibly related) that will crash the game when I try to mixin into but all my other mixins works just fine.

I did more testing and found that my mod works with the vanilla launcher, twitch launcher, and multimc. Only with GDLauncher was it crashing. A friend said GDLauncher ships 8u242 java on their own and when I changed GDLauncher to use my jre1.8.0_261, my mod works and doesn't crash! And the original issue reporter DMed me saying he is using jdk-8.0.252.09-hotspot when he got the crash. So the issue appears to be dependent on the java version used and which method is being mixin into on Forge. I did open an issue report to GDLauncher to ask them to ship 8u51 java instead to match vanilla (and solve other possible issues as well) https://github.com/gorilla-devs/GDLauncher/issues/674

-------
### Summary

MC version: 1.16.3
Forge Version: 34.1.25
Java that breaks: 8u242 and jdk-8.0.252.09-hotspot 
Java that works: 8u51 and jre1.8.0_261
Prints of the mixins that breaks with certain java versions: 
  1. https://hatebin.com/hwgouopydz
  2. https://hatebin.com/lquvqqunlf
  3. https://hatebin.com/cmepbhcups

-------

I hope this helps and let me know if you need any clarification or extra information! I tried checking to see if this issue was already reported and could not find anything so hopefully I didn't miss the original report if there was one.

**Comment by Mumfrey** [comment]
It would be really helpful to know what the original error is, that would give us a lot more information about what's actually causing this. Can you attach debugger (with mixin and modlauncher sources) to the failing setup and try to capture the actual error which is obviously being swallowed inside modlauncher or mixin somewhere.

**Comment by TelepathicGrunt** [comment]
As I was attaching the jdk-8.0.252.09-hotspot to my dev environment, I noticed intellij marked `import javafx.util.Pair;` as non-existent. When I removed that code with the proper `import com.mojang.datafixers.util.Pair;`, the mod started working with openjdk and the others.

Turns out, the mixin I was using used javafx.util.Pair; and crashed. But I still don't know why using javafx.util.Pair; outside the mixin in my own code (with the problematic mixin removed) stopped the crash. 

Nevertheless, this is 100% my fault and sorry about that! I'll close this issue. This is definitely a mistake I'll never make twice lol

**Comment by Mumfrey** [comment]
No worries, thanks for the comprehensive report even though it lead to a dead end.

What I'm more curious about is where the original exception is being swallowed inside modlauncher. Clearly the issue is (somehow) that the javafx package is missing and some other class can't be loaded, but the fact that the real source error is occluded seems like a legitimate issue. Or rather, this is one of those cases where things happening *correctly* is actually the source of the issue, and it's the code that's at fault.

It's also possible that enabling verbose mode in mixin might have revealed the exception, but I'm unsure.

Initialisers are a bitch, and so my suspicion is that it's some code injected into an initialiser which ended up causing the cryptic error. Errors in initialisers can do weird things, especially if they're not handled properly by calling code which isn't expecting them.

**Comment by Barteks2x** [comment]
I was getting crashes hidden that way before, with pretty much identical crash, It is just some weirdness with class initializers and vanilla code doing some weird stuff. I don't remember the details but the error being hidden wasn't even something I could come up with a way to fix.
