### ISSUE TITLE
[Bug] @Inject not remapping properly.

### ISSUE THREAD

**Issue by True-cc** [SpongePowered/Mixin#448]
I don't know if I'm doing anything wrong, but @Inject isn't remapping properly, so I have to remap it myself. For example, I have to do:
```java
@Inject(method = "func_71384_a", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/Minecraft;func_71361_d(Ljava/lang/String;)V", ordinal = 2, shift = At.Shift.AFTER))
```
instead of
```java
@Inject(method = "init", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/Minecraft;checkGLError(Ljava/lang/String;)V", ordinal = 2, shift = At.Shift.AFTER))
```

**Comment by True-cc** [comment]
Might be dup. of https://github.com/SpongePowered/Mixin/issues/414 but it seems that it's not just @At(target), but also @Inject(method)

**Comment by Mumfrey** [comment]
If something this fundamental was broken I'd know about it by now. So I assume this is an incorrectly configured build. Please follow up in discord as this issue tracker is for bugs rather than support.
