### ISSUE TITLE
Better documentation for `ModifyArg`

### ISSUE THREAD

**Issue by yyny** [SpongePowered/Mixin#457]
`@ModifyArg` could use some documentation clarifying that it changes the arguments of function calls INSIDE a method, and NOT the arguments OF the method. `@ModifyVariable(at=@At("HEAD"), index=<argument index>)` seems to have the latter behaviour. For documentation purposes, it might be good to introduce a `@ModifyParam` wrapper around `@ModifyVariable`.

The current documentation reads (Emphasis mine)

> Specifies that this mixin method should inject an argument modifier to **itself**
> in the target method(s) identified by `#method`. This type of injection
> provides a lightweight mechanism for changing a single argument of a target
> method invocation. To affect multiple arguments at once, use `ModifyArgs` instead.

This phrasing makes me assume that `@ModifyArgs(method="foo", ...)` would change the arguments of the `foo` function **itself**.

A possible improvement:

> Specifies that this mixin method should inject an argument modifier to _**a method invocation**_
> in the target method(s) identified by `#method`. This type of injection
> provides a lightweight mechanism for changing a single argument of a target
> method invocation. To affect multiple arguments at once, use `ModifyArgs` instead.
> _To affect the arguments **of the the target method itself**, use `@ModifyParam(method="...", index=<argument index>)`_

**Comment by Mumfrey** [comment]
Adding an "overload" for an existing injector with a clearly defiend contract is not going to happen. "Parameters" are not special in the context of a method, they're just variables in the frame like any other. The only difference is that they're *guaranteed* to be present in the frame right from the start, which can't be said of other locals. But `@ModifyVariable` already has `argsOnly` to optimise for that case.

I will make the documentation clearer.

**Comment by yyny** [comment]
> Adding an "overload" for an existing injector with a clearly defiend contract is not going to happen. "Parameters" are not special in the context of a method, they're just variables in the frame like any other. The only difference is that they're guaranteed to be present in the frame right from the start, which can't be said of other locals. But @ModifyVariable already has argsOnly to optimise for that case.

Perhaps `@ModifyParam` makes more sense in combination with `@ModifyParams` (See #381). For my use case, I'd preferably have received an `Args args`, rather than having to change each parameter individually. Also, I think the need for an `argsOnly` in addition to my confusion implies that the contract for `@ModifyVariable` is perhaps not so well defined, it seems to have two purposes at once.

IMHO it is the `@ModifyVariable` injector being an overload, rather than the potential `@ModifyParam`, considering `@ModifyVariable` has a separate overloaded code path solely for optimizing the change of parameters which would have been implied by a `@ModifyParam`.

**Comment by yyny** [comment]
I would imagine `@ModifyVariables` would have even more diverging paths given `argsOnly` were it to be implemented.

**Comment by Mumfrey** [comment]
`@ModifyVariable` modifies a local variable. The first part of the frame is always the args and doesn't need the complex heuristics that are required to reconstruct a meaningful idea of the state of the frame at arbitrary points in the method. Hence `argsOnly` turns **off** the expensive computation of the frame and simply declares "the variable I care about is in the 'args' part of the frame."

`argsOnly` is an optional optimisation, just a hint, to the mixin processor that the variable you care about is in the known part of the frame.
