### ISSUE TITLE
[1.12] Pseudo Mixin does not see classes from other jars in production

### ISSUE THREAD

**Issue by necauqua** [SpongePowered/Mixin#460]
In 1.12, shadowing the Mixin (0.8) library directly into the jar, if you have a mixin like this:
```java
@Pseudo
@Mixin(targets = "vazkii.neat.HealthBarRenderer")
public final class NeatMixin {
    // yes no actual patches even
}
```
It perfectly works in dev env with and without the Neat mod, but in production it [crashes](https://gist.github.com/necauqua/2beeb8766be1e31792393d76f51e18c2) with CNFE if the mod is present.

But the funniest thing that I found during my debugging, is that you can add this code to a coremod to fix it:
```java
@Override
public void injectData(Map<String, Object> data) {
    for (File file : new File(((File) data.get("mcLocation")), "mods").listFiles()) {
        try { // and this ignores a bunch of stuff like dev env (having no mods folder even or something), duplicates or other inner workings of forge classloading I am completely unaware of, jar file extension etc. lol
            Launch.classLoader.addURL(file.toURI().toURL());
        } catch (MalformedURLException ignored) {}
    }
}
```
I had this `GalacticraftFix` coremod lying around handy because this already happened - I couldn't mixin into their (dumb) `GCEntityClientPlayerMP` class, but I thought it was just a weird quirk related to their coremod or whatever so I rewrote my patches from Mixin back to ASM for that fix of mine - and now it happenned again with another mod I tried to add support for.

In the log you can see early mixin warnings about not finding the class `vazkii.neat.HealthBarRenderer` - just like it does for stuff like `net.optifine.DynamicLights` when optifine is not present, thats how I somehow arrived at the described "fix".

This also happens with only my mod and Neat, so things like VanillaFix also containing shadowed Mixin (because the log I provided is pretty noisy) are not the cause.

I really hope that I am just doing something wrong and this issue is useless, and you will just point at what I did wrong, but this seems like old (not enough experience with >1.12 to judge how it is in the new one) Forge classloading strikes again.

**Comment by Earthcomputer** [comment]
This looks like not a mixin issue but a classloading issue

**Comment by Barteks2x** [comment]
Afaik, this is just how it works on 1.12.2 and older - when the mixin phase transitions occur, normal mods aren't yet added to the classloader (and this is when mixin does some mixin validation), and there is no separate phase for mods (I think remember seeing some discussions for plans for custom phases, and it may have solved the issue, but I think this feature was never implemented). As a result various mods do different hacks to get around this. And this became a non-issue in modlauncher.

Also this should work for mods that are also coremods without any workarounds like this (so it should work for targetting optifine, and I can confirm that myself as I target some optifine classes).

**Comment by necauqua** [comment]
I found out that VanillaFix does [this](https://github.com/DimensionalDevelopment/VanillaFix/blob/1.12-wip/src/main/java/org/dimdev/vanillafix/modsupport/mixins/MixinLoader.java) to avoid this same issue.

I guess I have to do the same somehow, except I would be doing the same thing VanillaFix does and if both mods are present this would be duplicate work, and also the sources list in forge classloaders is, well, a list, instead of a set, so it would contain duplicates if it already didn't :/

**Comment by necauqua** [comment]
The issue is that I kind of expected Mixin to work like transformers do - once the class is getting loaded it will receive and transform its bytes, and it can happen as late as it can, mid-game even.

But the Mixin seems to actively try to load the class (even for `@Pseudo` mixins) when it sees my Mixin definition, fails and caches that fail, and then when the actual attempt to load this class happens it returns that cached fail or something, thats how it looks like from outside at least.

**Comment by Barteks2x** [comment]
The reason mixin does that is to fail **at all** when you target a class that actually doesn't exist (otherwise, if you target a class that doesn't exist... it would just silently do nothing because nothing would ever request that class). Mods just aren't yet loaded at the time mixin does this verification.

**Comment by necauqua** [comment]
Well, then it is actually a bug in how `@Pseudo` mixins work, because they are expected to work just as I've described, for direct mixins that are referenced with a class literal what you said makes sense

**Comment by necauqua** [comment]
So yeah sorry participants for the third ping but the issue is very simple at the end (yes rewording yet again):

`ClassInfo.forName` does not take into account if the mixin that calls it is virtual or not when caching class loading failure [here](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/transformer/ClassInfo.java#L1852).

**Comment by Mumfrey** [comment]
In 1.12 and before you can't transform non-coremods. `@Pseudo` is not a fix for that, it's purely to allow compilation where targets aren't available at compile time.

This is intentional and the gross hacks that VanillaFix is doing are in no way supported, recommended, or even sensible. There are other ways to ensure a mod is shoved into the main classloader without resorting to such crude hacks but I'm not going to encourage this behaviour.

**Comment by necauqua** [comment]
Ooooh, okay, thanks for the clarification.
People have told me that it is possible to mixin into other mods, but I guess they were talking about later versions.
