### ISSUE TITLE
Refmap processor does not generate subdirectories

### ISSUE THREAD

**Issue by ChloeDawn** [SpongePowered/Mixin#463]
**MixinGradle version:** 0.7-SNAPSHOT
**Mixin version:** 0.8.2

I use the following path structure for my refmap `mixins/$modid/refmap.json`, but Mixin does not resolve the parent directories, and in turn silently fails to create the refmap. This results in a `FileNotFoundException` later in compilation as Mixin then cannot find the refmap.

---

This is not high priority as I have a workaround, but it would be nice to have it resolved eventually:
```kotlin
doLast {
  buildDir.resolve("tmp/compileJava/$mixinRefmap").parentFile.mkdirs()
}
```

**Comment by Zidane** [comment]
I am fairly sure it does not support paths in that variable but instead simply a file name.

Mumfrey would need to comment further.

**Comment by ChloeDawn** [comment]
It was discussed on Discord in September of last year but I forgot to create an issue ticket regarding it.

**Comment by Mumfrey** [comment]
Ah thanks for opening an issue. This was floating around in the back of my mind. I think this needs a corresponding fix in MixinGradle to handle including the resource into a subdir in the final jar as well.
