### ISSUE TITLE
Question: How to inject into NEW 

### ISSUE THREAD

**Issue by PercyDan54** [SpongePowered/Mixin#464]
So a class like this:
``` JAVA
public class SheepEntityModel<T extends SheepEntity> extends QuadrupedEntityModel<T> {
    private float headPitchModifier;

    public SheepEntityModel() {
        super(12, 0.0F, false, 8.0F, 4.0F, 2.0F, 2.0F, 24);
        this.head = new ModelPart(this, 0, 0);
        this.head.addCuboid(-3.0F, -4.0F, -6.0F, 6.0F, 6.0F, 8.0F, 0.0F);
        this.head.setPivot(0.0F, 6.0F, -8.0F);
        this.torso = new ModelPart(this, 28, 8);
        this.torso.addCuboid(-4.0F, -10.0F, -7.0F, 8.0F, 16.0F, 6.0F, 0.0F);
        this.torso.setPivot(0.0F, 5.0F, 2.0F);
    }
}
```
How can I inject to `public SheepEntityModel() `

**Comment by Geolykt** [comment]
Chapter 7.3 of https://github.com/SpongePowered/Mixin/wiki/Advanced-Mixin-Usage---Callback-Injectors briefly mentions the limitation of what you attempt to do and the code to do that would briefly look something like this:
```@Inject(method = "<init>", at = @At("RETURN"))
private void onConstructed(CallbackInfo ci) {
    // do initialisation stuff
}```

**Comment by PercyDan54** [comment]
> Chapter 7.3 of https://github.com/SpongePowered/Mixin/wiki/Advanced-Mixin-Usage---Callback-Injectors briefly mentions the limitation of what you attempt to do and the code to do that would briefly look something like this:
> 
> ```java
> @Inject(method = "<init>", at = @At("RETURN"))
> private void onConstructed(CallbackInfo ci) {
>     // do initialisation stuff
> }
> ```

Thanks.
And how to `@Shadow` a class from extended class

**Comment by Geolykt** [comment]
That should work pretty much work like normal.
So create a `@Shadow`-annotated variable and reference it, that should usually work

**Comment by PercyDan54** [comment]
> Chapter 7.3 of https://github.com/SpongePowered/Mixin/wiki/Advanced-Mixin-Usage---Callback-Injectors briefly mentions the limitation of what you attempt to do and the code to do that would briefly look something like this:
> 
> ```java
> @Inject(method = "<init>", at = @At("RETURN"))
> private void onConstructed(CallbackInfo ci) {
>     // do initialisation stuff
> }
> ```

This injected into constructor. But I want to inject into NEW.
I want to modify `this.torso` and it's overwritten in NEW

**Comment by PercyDan54** [comment]
> That should work pretty much work like normal.
> So create a `@Shadow`-annotated variable and reference it, that should usually work
![image](https://user-images.githubusercontent.com/50285552/106381639-25f6ca00-63f5-11eb-89c3-2bf68f6e4d5b.png)

Not working

**Comment by Geolykt** [comment]
what do you mean with it's not working? Are you sure you imported the correct annotation?

**Comment by PercyDan54** [comment]
> what do you mean with it's not working? Are you sure you imported the correct annotation?

It crashed on launch:
https://paste.ubuntu.com/p/B7My8mgVKZ/

```
[16:15:49] [main/FATAL] (mixin) Mixin apply failed modid.mixins.json:ExampleMixin -> net.minecraft.client.render.entity.model.SheepEntityModel: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field torso was not located in the target class net.minecraft.client.render.entity.model.SheepEntityModel. No refMap loaded.
 org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field torso was not located in the target class net.minecraft.client.render.entity.model.SheepEntityModel. No refMap loaded.
```

**Comment by Geolykt** [comment]
I think an "easy" way of doing this would be by creating a supermixin that targets the class that defines the variable `torso`, then creating a `@shadow` in that supermixin and then extending the supermixin in your current ExampleMixin class. Alternatively it might be worth a try to extend QuadrupedEntityModel directly in your ExampleMixin, but I doubt that is going to work (although I recall it working once for me, but idk - could be lying).

**Comment by PercyDan54** [comment]
> I think an "easy" way of doing this would be by creating a supermixin that targets the class that defines the variable `torso`, then creating a `@shadow` in that supermixin and then extending the supermixin in your current ExampleMixin class. Alternatively it might be worth a try to extend QuadrupedEntityModel directly in your ExampleMixin, but I doubt that is going to work (although I recall it working once for me, but idk - could be lying).

There's still a problem that torso is overwritten in NEW but I only injected into ctor

**Comment by Geolykt** [comment]
Wdym `NEW`? Do you mean the constructor (init) with that or the opcode `NEW` (in that case see https://github.com/SpongePowered/Mixin/wiki/Injection-Point-Reference#new)?

**Comment by PercyDan54** [comment]
> Wdym `NEW`? Do you mean the constructor (init) with that or the opcode `NEW` (in that case see https://github.com/SpongePowered/Mixin/wiki/Injection-Point-Reference#new)?

I mean
``` JAVA 
public SheepEntityModel()
 ```

**Comment by Geolykt** [comment]
That's the constructor which you are already injecting into (also known as `<init>`, the static init block is `<clinit>`). If you want to prevent an assignment performed within this constructor then I don't know how that could be achieved (I don't think Mixin allows overwrites to the constructor).
It would be good if you were to provide more information on what you want to do as currently I'm kindof confused to what you want to do.

**Comment by PercyDan54** [comment]
> That's the constructor which you are already injecting into (also known as `<init>`, the static init block is `<clinit>`). If you want to prevent an assignment performed within this constructor then I don't know how that could be achieved (I don't think Mixin allows overwrites to the constructor).
> It would be good if you were to provide more information on what you want to do as currently I'm kindof confused to what you want to do.

ok thanks
