### ISSUE TITLE
Is the maven down?

### ISSUE THREAD

**Issue by Sunconure11** [SpongePowered/Mixin#465]
![Screenshot 2021-01-31 05 51 47](https://user-images.githubusercontent.com/5614902/106381795-42f5b380-6389-11eb-95cb-e2e1dc286713.png)

![Screenshot 2021-01-31 05 55 59](https://user-images.githubusercontent.com/5614902/106381798-46893a80-6389-11eb-9594-3d36d35a8eba.png)

**Comment by Mumfrey** [comment]
This is an issue tracker not a support forum. For questions like this please use discord.

Sponge is migrating to a new maven server this weekend and it doesn't look like snapshots have transferred properly so someone will look into it.
