### ISSUE TITLE
[Question] Access "this" and "OuterClass.this" in @Inject'ed inner class method

### ISSUE THREAD

**Issue by thanhminhmr** [SpongePowered/Mixin#468]
I'm relatively new to Minecraft modding, and I cannot find a way to get the "this" reference and the outer class "this" reference in the injected method.
For example:
```java
public abstract class OuterClass {
    private final String value;

    public abstract class InnerClass {
        public int getHash() {
            return OuterClass.this.value.length(); // or value.length() for short
        }
    }
}
```
I want to inject to the ```getHash``` function, access to ```this``` and ```OuterClass.this``` and do some logic like this:
```java
if (this instanceof SomeOtherInnerClass)
    ((SomeOtherInnerClass) this).getOtherHash(); // ... do logic here ...

if (OuterClass.this instanceof SomeOtherClass)
    ((SomeOtherClass) OuterClass.this).getOtherValue(); // ... do logic here ...
```
How do I do it properly?

**Comment by Geolykt** [comment]
Just casts it to a class that both classes share, so in this case, Object `((YourClass) (Object) this)`

**Comment by LlamaLad7** [comment]
That works if you want to pass `this` to another method, but in the example given they should just `Shadow` `getOtherHash`. To access the outer class instance they can Shadow the synthetic member, whose name can be found by looking at the class bytecode, but may be different inside and outside the development environment.

**Comment by Mumfrey** [comment]
This is not a support forum, this is an issue tracker for feature requests and bugs. Please use [the discord channel](https://discord.gg/tBcwxz2) for support questions.
