### ISSUE TITLE
Mixin application failure

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/Mixin#47]
Continuing the same code from https://github.com/SpongePowered/SpongeVanilla/issues/167, I'm now positive of a correct signature and inject annotation and this source file breaks the server load with the provided error log only when capture locals using PRINT is enabled. If I remove that argument the injection works correctly. https://gist.github.com/modwizcode/98aa1686c643427b8b78

**Comment by Mumfrey** [comment]
You're still using the version from before the fixes so of course it's breaking.

**Comment by modwizcode** [comment]
Oops sorry about that. I did a full update and I thought that would work.
