### ISSUE TITLE
Too many checkcasts are stripped (static methods)

### ISSUE THREAD

**Issue by skyrising** [SpongePowered/Mixin#471]
In `MixinTargetContext::transformTypeNode` any cast from `aload 0` to the target class is removed, this causes class verification to fail in static methods where `0` is not `this`

Example:
```java
@Mixin(Foo.class)
class FooMixin {
  static void bar(Object o) {
    ((Foo) o).baz();
  }
}
```
will be transformed from `aload 0; checkcast Foo; invokevirtual Foo.baz` to `aload 0; invokevirtual Foo.baz` which is invalid because `Foo` methods can't be called on `Object`
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Foo.bar(Ljava/lang/Object;)V @1: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'Foo'
```

**Comment by Mumfrey** [comment]
Good spot. Will fix this.
