### ISSUE TITLE
Mixin doesn't correctly detect side with forge data runs

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#473]
This code
https://github.com/SpongePowered/Mixin/blob/4e4c72ee223883ae2704535ba3d8266f49ed82f4/src/modlauncher/java/org/spongepowered/asm/launch/platform/MixinPlatformAgentMinecraftForge.java#L65-L76
determines the side by checking launch target name, but for data run the target name is for example `fmluserdevdata`, whcih doesn't contain `client` or `server` and causes mixins to fail.

**Comment by Mumfrey** [comment]
This issue doesn't cause the bug to which you were referring, but I will add detection for this env so that it correctly allows application of sided mixins.
