### ISSUE TITLE
Can you stop the execution of a short piece of code?

### ISSUE THREAD

**Issue by 1zuna-chan** [SpongePowered/Mixin#476]
Hello,

I'm not sure if this is already possible, so I'll just ask it:
Can you stop the execution of a short piece of code?

example:
code without modification:
```java
if (this.hasStatusEffect(StatusEffects.LEVITATION)) {
    v += (0.05D * (double)(this.getStatusEffect(StatusEffects.LEVITATION).getAmplifier() + 1) - vec3d7.y) * 0.2D;
    this.fallDistance = 0.0F;
}
```

code using `@Inject` (basically)
```java
if (this.hasStatusEffect(StatusEffects.LEVITATION)) {
    if (callback) {
       return;
    }
    v += (0.05D * (double)(this.getStatusEffect(StatusEffects.LEVITATION).getAmplifier() + 1) - vec3d7.y) * 0.2D;
    this.fallDistance = 0.0F;
}
```

what I would like to do:
```java
if (this.hasStatusEffect(StatusEffects.LEVITATION)) {
    if (!callback) {
        v += (0.05D * (double)(this.getStatusEffect(StatusEffects.LEVITATION).getAmplifier() + 1) - vec3d7.y) * 0.2D;
    }
    this.fallDistance = 0.0F;
}
```

Thank you.

**Comment by Earthcomputer** [comment]
First of all this isn't a support forum, for further questions use the #mixin channel in the Sponge discord (https://discord.gg/sponge). In this case it looks like you could redirect the `hasStatusEffect` to return false if `!callback`, that skips the whole if statement, then you just need to set `fallDistance` to 0 yourself.

**Comment by 1zuna-chan** [comment]
That's how I've already done it, but I was curious if there is no better way. Might be a good idea to implement, because I've already had many situations where something like that would be very useful.

**Comment by Earthcomputer** [comment]
Implementing that would be far more complicated than you're making out. "Statements" of code don't exist in the bytecode.

**Comment by Zidane** [comment]
Earth is quite right, your response screams of someone who clearly does not understand bytecode. Would recommend you to read a primer on it.

**Comment by Geolykt** [comment]
It might be possible to by injecting a label and a jump statement to bridge some pieces of code, but I do not know how one could possibly make a "nice" interface for that, let alone in a way that is comparable to the rest of the mixins framework

**Comment by 1zuna-chan** [comment]
> Earth is quite right, your response screams of someone who clearly does not understand bytecode. Would recommend you to read a primer on it.

I do unterstand bytecode and clearly doesn't see any issue with implementing it. Would you mind to explain where the difficulty is? I already done this many times.
