### ISSUE TITLE
Mixin  transforming method error

### ISSUE THREAD

**Issue by vfyjxf** [SpongePowered/Mixin#477]
When I redirect the contains method of the GuiFluidTerminal class of the extracell mod, he seems to affect the asm of the nei
Minecraft Version:1.7.10
log:https://paste.ubuntu.com/p/9CWb9vCMSs/
code:https://paste.ubuntu.com/p/Dmnj6GGB7C/

**Comment by Earthcomputer** [comment]
Looks like the 1.7.10 version of NEI is using some crappy coremodding practices, exactly the kind of thing mixin was designed to solve. This is not a mixin issue, it's an NEI issue, and it's such an old version that it's unlikely to be supported, so you're on your own, you'll have to find a way to make it compatible.
