### ISSUE TITLE
[Question] how to wrap a method?

### ISSUE THREAD

**Issue by rmuchan** [SpongePowered/Mixin#484]
suppose we have

```java
class C {
  void foo() {
    // something
  }
}
```

is there an elegant way to wrap the method as if by

```java
@Mixin(C.class)
class CMixin {
  @Overwrite
  void foo() {
    enterFoo();
    try {
      // something
    } finally {
      exitFoo();
    }
  }
}
```

without copying method body? inject at RETURN is not safe because foo may throw an exception.

**Comment by Mumfrey** [comment]
This is an issue tracker. Please use discord for questions and support.
