### ISSUE TITLE
Instance initializer is never called

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/Mixin#49]
In the class at https://gist.github.com/zml2008/482eb91adf7f2b174165#file-mixinsubject-java-L86
the highlighted line is never reached. It seems like it should be possible to inject simple initializers with multi-target mixins, but this does not appear to happen currently

**Comment by Mumfrey** [comment]
Initialisers in mixins have always been ignored. You must inject into the initialiser in the target class in order to call construct-time logic.

**Comment by zml2008** [comment]
Except that when I try that, I get told that injecting is not allowed with multi-target mixins

**Comment by Mumfrey** [comment]
It should be allowed if you set `remap=false` on the `@Inject` annotation. The reason it's not allowed on remapped injectors is that a single name in multiple classes which are obfuscated will obviously remap to *multiple* names in each target class so I can't squeeze it through the obfuscator. But `<init>` always has the same name and so you can set `remap=false` on it and it should be fine.

If that doesn't work let me know and I'll check the AP logic.

**Comment by zml2008** [comment]
That sorta works -- now I'm getting an issue with the fact that the different targets take different constructor arguments:
```
Caused by: org.spongepowered.asm.mixin.injection.InvalidInjectionException: Invalid descriptor on callback: expected (Ljava/io/File;Ljava/net/Proxy;Ljava/io/File;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V
    at org.spongep
```
(the output was cut off there in the terminal, not mispaste)

**Comment by Mumfrey** [comment]
Hmm. Well if you don't actually need the actual arguments then I could make it so that injectors can be created which don't take the method args in their signature. That should let you inject with impugnity.

**Comment by zml2008** [comment]
yeah, I don't care about the arguments so that sounds like what I'd need.

**Comment by Mumfrey** [comment]
Ok I'll get right on that.

**Comment by Mumfrey** [comment]
Ok, as of the commit above you can now make injector callbacks with *only* the `CallbackInfo` argument. You will need to update the mixin library version to 0.4.3 in spongecommon to get this change though.

**Comment by zml2008** [comment]
Great, that seems to work. Thanks!
