### ISSUE TITLE
Mixin Error

### ISSUE THREAD

**Issue by Assassin4b** [SpongePowered/Mixin#491]
I know that sounds stupid, but i have no idea why or how this bug is caused.
So basically, it just does not work (im trying to hook on the shutdown() method in the Minecraft class so i have a shutdown event)
Before that i had mapping problems which i got fixed and thought it would work now, but now it just does not work without any Error or Stacktrace. It probably is something with the way i build the jar using shadow.

Heres the src repo: https://github.com/Assassin4b/LynxError .
(this is just a quick forge setup without the mod i had the problem with first, but even with a fresh setup it does not work.)

I know this is not really how tocommit an issue, but i really have no other ideas, i searched trough all of the docs, the forge forum and 3rd party websites.

**Comment by Zidane** [comment]
The github repo is for Mixin is for issues with Mixin itself, it isn't a support forum.

Please join the `mixin` channel on the Discord. https://discord.gg/tBcwxz2
