### ISSUE TITLE
Mixins for Vanilla Java

### ISSUE THREAD

**Issue by SirLennox** [SpongePowered/Mixin#494]
Hello,
is there any version of this project without minecraft stuff in?

**Comment by ItsDoot** [comment]
[Modlauncher](https://github.com/cpw/modlauncher) has no explicit dependency on Minecraft, so you can use it as a general purpose bootstrapper to load mixins. If you have further questions about it, ask in https://discord.gg/sponge

**Comment by Geolykt** [comment]
The Version on this repo has no dependencies for Minecraft whatsoever and has been successfully been used with several non-minecraft games. You would need to bootstrap Mixin though, which is a bit harder to do, but has been done and you could just reuse them.

**Comment by EliteMasterEric** [comment]
For anyone accessing this issue via Google, it is possible to use the Mixin library without Minecraft, however this requires implementing a custom class loader which can execute the transformers.

Thankfully, Fabric Loader provides this functionality (also without dependencies on Minecraft). This allows it to be used for other Java-based applications, such as Slay the Spire or Mindustry.

Here is an example project in which I inject a Mixin into a Hello World JAR:

https://github.com/EliteMasterEric/HelloWorldFabric

**Comment by BlueTheCube** [comment]
mindustry mentioned

**Comment by samuelh2005** [comment]
> For anyone accessing this issue via Google, it is possible to use the Mixin library without Minecraft, however this requires implementing a custom class loader which can execute the transformers.
> 
> Thankfully, Fabric Loader provides this functionality (also without dependencies on Minecraft). This allows it to be used for other Java-based applications, such as Slay the Spire or Mindustry.
> 
> Here is an example project in which I inject a Mixin into a Hello World JAR:
> 
> https://github.com/EliteMasterEric/HelloWorldFabric

@EliteMasterEric Do you have a example that doesn't use the Fabric loader (e.g. an example for the custom class loader)?

Sometimes you may want to load mixins in a generic Java program to overide a libaray that you are using, so you wouldn't want to have Fabric mod loading in your program.

**Comment by Geolykt** [comment]
> Do you have a example that doesn't use the Fabric loader (e.g. an example for the custom class loader)?
> 
> Sometimes you may want to load mixins in a generic Java program to overide a libaray that you are using, so you wouldn't want to have Fabric mod loading in your program.

Well first and foremost this is an issue tracker; conversations about mixins themselves should occur within the sponge discord (which was linked earlier in this issue). That being said, I'll just copy & paste one of my earlier discussions about  the mixin integration within my modloader (that is kinda  a fork of minestom's code, though severely changed over the years): 

Registering the implementations of mixin services: <https://github.com/stianloader/Starloader/tree/master/src/main/resources/META-INF/services> (Mixin uses the standard ServiceLoader API - but even if you do not know that API already it should be fairly obvious what this does)

Implementations of the mixin services: <https://github.com/stianloader/Starloader/tree/master/src/main/java/de/geolykt/starloader/launcher/service>

Initializing the Mixin subsystem and MixinExtras (call this as early as possible): <https://github.com/stianloader/Starloader/blob/665575774acf13e539b3ba9784036c267089ba62/src/main/java/de/geolykt/starloader/launcher/CLILauncher.java#L81-L83> [I'm not too sure whether incrementing all the phases is a requirement, but I'm still doing that just to be safe - so I'd recommend doing that too, even if that isn't highlighted in this piece of code]

Obtaining class transformation capabilities: <https://github.com/stianloader/Starloader/blob/665575774acf13e539b3ba9784036c267089ba62/src/main/java/de/geolykt/starloader/launcher/ASMMixinTransformer.java#L21>

Transforming classes: <https://github.com/stianloader/Starloader/blob/665575774acf13e539b3ba9784036c267089ba62/src/main/java/de/geolykt/starloader/launcher/ASMMixinTransformer.java#L31> (this is where explaining the transformation chain is more or less mandatory, but excuse me if I don't do that as I'm too lazy for that)

Registering mixin configurations: <https://github.com/stianloader/Starloader/blob/665575774acf13e539b3ba9784036c267089ba62/src/main/java/de/geolykt/starloader/mod/ExtensionManager.java#L599>

--

Fabric's implementation might be a bit clearer though, so check them out too
