### ISSUE TITLE
There are no mappings for MC 1.12.2

### ISSUE THREAD

**Issue by hovacmc** [SpongePowered/Mixin#498]
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'waco'.
Caused by: net.minecraftforge.gradle.util.GradleConfigurationException: There are no mappings for MC 1.12.2

forge version - 1.12.2-14.23.5.2855
mappings - 'stable_39'

how do I fix this

**Comment by Mumfrey** [comment]
This is an issue tracker for Mixin, it is not a support forum for completely unrelated gradle questions.
