### ISSUE TITLE
Anonymous inner classes not functional

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/Mixin#50]
Using an anonymous inner class for the predicate in the class linked in #49 caused https://gist.github.com/zml2008/6316871b8ebdd77ebc57 -- seems like references to the mixin class are not being stripped from the class properlfy, or there's some annotation I should be doing but am not.

**Comment by Mumfrey** [comment]
You can't use inner classes in mixins. I make an exception for synthetic inner classes because they are predictable, but allowing inner classes opens up a whole scope of situations that aren't easily cope-withable right now.

Inner classes are easy to avoid, so just don't use them in mixins.

**Comment by zml2008** [comment]
Ok, then I'm fine closing this one, can work around that limitation fairly easily.
