### ISSUE TITLE
[FEATURE] Support URLClassLoader

### ISSUE THREAD

**Issue by xWhitey** [SpongePowered/Mixin#506]
So, I want to make mixin classes load from my server

**Comment by Geolykt** [comment]
I do not think that it is possible to use it with the URLClassLoader class without using a java agent, it is better to just change the classloader to a custom one (it can still extend URLClassLoader).
This is more of an mod loader question than something that should be implemented in Mixins.
If you are looking for an implentation with it, I recommend Minestom's one (https://github.com/Minestom/Minestom/tree/master/src/main/java/net/minestom/server/extras/selfmodification) it is dead easy to adapt it to anything that isn't already using a custom classloader (such as many other java games or bukkit - forge and fabric will not be happy with it though as they use their own classloader)

**Comment by Zidane** [comment]
You need to reach out to whatever server software vendor that is bootstrapping your product. Mixin does not enforce the classloader to use.

Not a Mixin problem.
