### ISSUE TITLE
Ability to disregard public static safety check in mixins

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Mixin#51]
@Mumfrey ,

In updating Sponge for the unified multi-world implementation, I hit a brick wall here:

https://github.com/SpongePowered/Sponge/commit/f8d57a547a68537f19889025500832c3f41ec91a#diff-ef8a3be4b70089992a904af75dec8e5dR23

I need to proxy all of common's DimensionManager calls back to Forge's (to remain 100% compatible) but the Mixin transformer rejects it as it fails the safey check. Any chance of a way to override the check or a better way to do this?

**Comment by Mumfrey** [comment]
You can `@Overwrite` public static methods, you just can't have orphaned ones in mixins because there would be no way to ever call them. It's not so much a safety check as a derp check.

**Comment by Zidane** [comment]
@Mumfrey 

Silly @Aaron1011 told me that @Overwrite is only used for things that are obfuscated. I may need to go back and take a refresher course on your docs...

**Comment by Mumfrey** [comment]
If you read the javadocs you'll see that it has two modes of operation. One for decorating methods which need to overwrite obfuscated targets, and one for forcibly overwriting a public static method which would otherwise raise this error.

**Comment by Mumfrey** [comment]
Actually I take it back, apparently the javadocs **don't** actually say that, which is weird because I remember adding that note. It's possible that I accidentally removed it in a merge commit or something.

**Comment by simon816** [comment]
@Zidane You'll need to put `remap = false` in the `@Mixin` annotation so that `@Overwrite` doesn't go looking for srg names.

**Comment by Mumfrey** [comment]
^this
