### ISSUE TITLE
Move to Gradle 7 for build script?

### ISSUE THREAD

**Issue by LogicFan** [SpongePowered/Mixin#510]

**Comment by zml2008** [comment]
why? there's no reason to update

**Comment by LogicFan** [comment]
Because Gradle 6 does not support Java 16. And this means any time I want to compile Mixin, I need to change my JAVA_HOME variable.

**Comment by SizableShrimp** [comment]
Not true. You can configure the JVM for Gradle from a gradle project property, which can also be done globally in your .gradle file in your user directory, with the full path being `~/.gradle/gradle.properties`

**Comment by LogicFan** [comment]
> Not true. You can configure the JVM for Gradle from a gradle project property, which can also be done globally in your .gradle folder in your user directory, with the full path being `~/.gradle/gradle.properties`

I cannot seem to get it to work project-wise. And is there any particular reason not to upgrade to Gradle 7?

**Comment by SizableShrimp** [comment]
Pretty sure the buildscript uses some FTP stuff removed in Gradle 7, so yes.

**Comment by LexManos** [comment]
Gradle 6.9 backported support for building J16 code. But does not ship the updated groovy and other libs that allow running gradle itself on J16.

I'll be speaking with mumfrey about bumping his scripts to a modern version now that some blockers have been removed. However its not super important so I haven't gotten around to it.
