### ISSUE TITLE
ModifyVariable Context shadowing breaks LV lookup

### ISSUE THREAD

**Issue by sfPlayer1** [SpongePowered/Mixin#511]
https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/injection/modify/ModifyVariableInjector.java#L148 and https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/injection/modify/ModifyVariableInjector.java#L160 reference a storage location that appears to be used more than once in mixins like https://github.com/FabricMC/fabric/blob/1.16/fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/fluid/MixinFluidRenderer.java .

One of the mixin methods captures a boolean, the other a Sprite[], but Mixin uses the latter for both through overwriting the value in `node.decorate` despite having more than one unique entry for the decoration "slot". This results in `discriminator.findLocal` working off the wrong `context`, returning the wrong lv index for the boolean capture and broken bytecode like this (lv 6 is Sprite[], the first load/store should use lv 5):
```
iload6
invokevirtual net/minecraft/class_775.localvar$cel000$modLavaCheck(Z)Z
istore6
aload0
aload6
invokevirtual net/minecraft/class_775.localvar$cel000$modSpriteArray([Lnet/minecraft/class_1058;)[Lnet/minecraft/class_1058;
astore6
```

The `InjectionNode` is not a sufficient discriminator for attaching data.

This is a regression from https://github.com/SpongePowered/Mixin/commit/99a51998c0b9270c7e85102cc37854f46dc132ea

**Comment by Mumfrey** [comment]
> The `InjectionNode` is not a sufficient discriminator for attaching data.

This is the meat of the issue. I used the same approach for this injector as for the `CallbackInjector` but storing the whole context was a mistake. Since this is a definite regression I feel it justifies an updated release so I will look into it straight away.
