### ISSUE TITLE
ModifyVariableInjector.printLocals passes incorrect amount of variable names

### ISSUE THREAD

**Issue by sfPlayer1** [SpongePowered/Mixin#512]
I force-enabled printLocals for debugging purposes through bypassing `if (this.discriminator.printLVT()) {`, but https://github.com/SpongePowered/Mixin/blob/2046b44ad2fed1255256699f3b0b729bdb674369/src/main/java/org/spongepowered/asm/mixin/injection/modify/ModifyVariableInjector.java#L206 fails with e.g. `IllegalArgumentException: Types array length must not exceed names array length! (names=1, types=7)`

**Comment by Mumfrey** [comment]
I think this came from the fact that ModifyVariable didn't support capturing target args originally, f9e19c32f4af07479c6256e6c3a19d398f838979 added support but this was obviously missed.
