### ISSUE TITLE
Change integer value with mixin

### ISSUE THREAD

**Issue by LegoRaft** [SpongePowered/Mixin#519]
I want to change the value of this `int k = this.scaledHeight - 59;` integer in the renderHeldItemTooltip with a mixin, without using an override. I've seen the [@ModifyVariable](https://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/ModifyVariable.html) function, but the documentation isn't that clear. How would I change an integer without using an overrride?

**Comment by Mumfrey** [comment]
This is an issue tracker for bugs and feature requests for mixin, not a support forum. Please use discord for general support questions.
