### ISSUE TITLE
MixinServiceModLauncherBootstrap not a subtype initialising service

### ISSUE THREAD

**Issue by EliteUn17y** [SpongePowered/Mixin#524]
hi! i'm trying to use mixins (0.8.3), however when i run it in my dev environment, it doesn't load the mixins and prints 
[main/DEBUG] [mixin]: Catching java.util.ServiceConfigurationError:org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap not a subtype initialising service

it doesn't happen when i run it through the official minecraft launcher.

**Comment by Mumfrey** [comment]
Why are you using 0.8.3? Ensure this is reproducible on current mixin and also actually provide logs with your full command line and ideally gist of your build.gradle.

The fact that you're trying to use a version which wasn't ever officially added to forge, and are reporting an error which implies you screwed something up in your configuration makes me suspect this isn't a bug and is just user error.

**Comment by EliteUn17y** [comment]
https://gist.github.com/EliteUn17y/fe03e222e71e176efe9ce58d5d9519a2
^ build.gradle and a console log.

I am using 0.8.4 now which I presume is the latest.

**Comment by Mumfrey** [comment]
You're not even using ModLauncher, you're using 1.12 with LaunchWrapper so of course the ModLauncher service won't start...
