### ISSUE TITLE
Mixin AP unable to parse the new TSRG format in FG 5

### ISSUE THREAD

**Issue by FoxShadew** [SpongePowered/Mixin#526]
When using the Mixin Annotation Processor in ForgeGradle 5 (which is required for 1.17.1), it fails to process the mixin annotations because the TSRG format used in ForgeGradle 5 is different from the format used in ForgeGradle 4 and 3. ForgeGradle 5 TSRG starts with a header `tsrg left right`, and contains extra lines `static` to indicate static methods. Here's a part from the TSRG generated from Mojang mappings in 1.17.1:
```
tsrg2 left right
com/mojang/blaze3d/Blaze3D com/mojang/blaze3d/Blaze3D
	<init> ()V <init>
	getTime ()D m_83640_
		static
	process (Lcom/mojang/blaze3d/pipeline/RenderPipeline;F)V m_166118_
		static
		0 p_166119_ p_166119_
		1 p_166120_ p_166120_
	render (Lcom/mojang/blaze3d/pipeline/RenderPipeline;F)V m_166121_
		static
		0 p_166122_ p_166122_
		1 p_166123_ p_166123_
	youJustLostTheGame ()V m_83639_
		static
com/mojang/blaze3d/DontObfuscate com/mojang/blaze3d/DontObfuscate
com/mojang/blaze3d/FieldsAreNonnullByDefault com/mojang/blaze3d/FieldsAreNonnullByDefault
com/mojang/blaze3d/MethodsReturnNonnullByDefault com/mojang/blaze3d/MethodsReturnNonnullByDefault
com/mojang/blaze3d/audio/Channel com/mojang/blaze3d/audio/Channel
	BUFFER_DURATION_SECONDS f_166124_
	LOGGER f_83641_
	QUEUED_BUFFER_COUNT f_166125_
```

I fixed it by manually removing the `tsrg left right` and `static` lines and feeding that to the AP instead (via MixinGradle):
```gradle
createMcpToSrg {
    outputs.upToDateWhen {false}
    doLast {
        fixMcp2Srg(output.get().asFile, file("${buildDir}/fixMcpToSrg/output.tsrg"))
    }
}

static def fixMcp2Srg(File inFile, File outFile) {
    outFile.parentFile.mkdirs()
    try (Scanner scanner = new Scanner(inFile); PrintWriter out = new PrintWriter(outFile)) {
        boolean firstLine = true
        while (scanner.hasNextLine()) {
            String next = scanner.nextLine()
            if (firstLine) {
                firstLine = false
                continue
            }
            if (next.trim() == "static") {
                continue
            }
            out.println(next)
        }
    }
}
```

Without this workaround, building Forge mods for 1.17.1 with Mixin is impossible.

**Comment by dualdragoon** [comment]
Seems like this will work. However I'm unclear on how to feed the fixed file to the AP. An example of that would be greatly appreciated.

**Comment by zml2008** [comment]
This has been fixed in Mixin 0.8.4. Why on earth would you need to hack around it?

**Comment by dualdragoon** [comment]
I would like to point out that just following the official guide on enabling mixins with forge with the most recent recommended Forge MDK results in this issue. I don't know if it uses an older version just that it's the issue I came across when trying to set it up. If there's a newer version I'd love to know how to target that instead.

**Comment by zml2008** [comment]
What official guide?

**Comment by dualdragoon** [comment]
This one. https://github.com/SpongePowered/Mixin/wiki And looking through the gradle build files of other projects that use Mixins.

**Comment by dualdragoon** [comment]
I also feel the need to specify that I'm using 1.16.5 not 1.17.

**Comment by SizableShrimp** [comment]
This is a non-issue. I personally fixed TSRGv2 parsing, and it was included in Mixin 0.8.3 and up. All you need to do is ensure you are using 0.8.3 or higher for your annotation processor, and it will work fine.

**Comment by dualdragoon** [comment]
That's great but how do I do that? I have found very little readily available information on how to do that. I'm using MixinGradle which is where I originally posted this issue but it linked here. I have found no real info on changing which version of Mixin I'm targeting using MixinGradle.

**Comment by SizableShrimp** [comment]
It's a single version number in your build.gradle. This issue tracker isn't for tech support, use #mixin in Sponge discord for that.

**Comment by FoxShadew** [comment]
I might have been severely dumb for not having tried updating to mixin 0.8.4. Thanks anyway, I'll close the issue.
