### ISSUE TITLE
Mixin as a testing and documentation framework

### ISSUE THREAD

**Issue by SoniEx2** [SpongePowered/Mixin#527]
It would be quite powerful if one could use mixin directly for testing and documentation. We're not sure what it would have to look like but it would need to be able to generate documentation based on mixins. Okay, maybe this shouldn't be a part of mixin proper, but even if it were an addon or side project to mixin, it'd help so much with reverse engineering and documentation efforts that it'd be worth it. It's one of those things that could enable eventually making an open source clone of the Minecraft engine, complete with mod support.

**Comment by Geolykt** [comment]
Why would mixin be connected to documentation and testing?
I believe that this awards a completely separate project

**Comment by Aizistral** [comment]
My opinion thus far is exactly the same as such of above commenter. What Mixin has to do with documentation and testing in the first place?

**Comment by SoniEx2** [comment]
Mixin injects stuff at injection points. Extending that to docs could be useful.

**Comment by Aizistral** [comment]
You mean, like, eh... Injecting documentation?

**Comment by SoniEx2** [comment]
Yeah!?

**Comment by Aizistral** [comment]
Uhmm... I don't think you have sufficient understanding of what constitutes Mixin and how it works. Tools you describe have to operate on source-code level, whereas Mixin uses ASM to manipulate JVM bytecode. No meaningful bridge can be built to achieve what you describe within the bounds of this framework or somehow involving it.

**Comment by gabizou** [comment]
Yeah... no. Mixin is not a tool for injecting testing and documentation into applications. There are other tools to do that. If anything, there is the possible future tool to enable running JUnit tests or integration tests with Mixin, but otherwise, that's out of scope of this repository/project.
