### ISSUE TITLE
JVM Crash (segfault) when hot-swapping mixins while using DCEVM

### ISSUE THREAD

**Issue by DaMatrix** [SpongePowered/Mixin#528]
When hot-swapping mixin code changes, [DCEVM](https://ssw.jku.at/dcevm/) will segfault. The crash occurs consistently and regardless of the complexity of the changes being hot-swapped (even swapping in an unmodified class will crash).
[Sample JVM crash log](https://github.com/SpongePowered/Mixin/files/7285400/hs_err_pid8273.log)

DCEVM behaves perfectly fine when hot-swapping code changes in other (non-mixin) classes, even with the mixin javaagent present.

Mixin hot-swapping works as expected when using the standard HotSpot VM.

**Comment by Mumfrey** [comment]
What do you actually expect from opening this bug? If it's a native crash that you confirm doesn't happen with Oracle's VM then how do you anticipate that this can be fixed on Mixin's end?

I'm totally baffled about what you actually expect to happen here?

**Comment by DaMatrix** [comment]
Well, I'd been hoping that perhaps somebody who knew what they're doing would be able to look into it and perhaps come up with a workaround, or maybe there's even an already known workaround for this problem.

I've managed to come up with a somewhat shitty, albeit functional workaround: moving the line `MixinAgent.instrumentation.redefineClasses(new ClassDefinition(targetClass, targetBytecode));` in `MixinAgent` to be executed on a different thread yields the expected results without segfaulting. Am I correct in assuming that that's not a change you'd be interested in merging if I were to make a PR?

**Comment by Mumfrey** [comment]
Since you haven't really articulated what you actually expect from this, I'm closing for now. Reopen if you have any further updates.
