### ISSUE TITLE
Inject into method added by other Mixin

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Mixin#53]
@Mumfrey 

Yet another from the unified changes:

https://github.com/SpongePowered/Sponge/commit/f8d57a547a68537f19889025500832c3f41ec91a#diff-7935aaf1dc2aaf2359fbb6ef6905acf3L61

I need teleportEntity (the method changes that were added here) to exist up in Common. The correct code would be to keep that inection. Common's MixinEntity adds teleportEntity, Sponge's MixinEntity needs to inject into it.

Mixin throws an exception because its mixin into a mixin provided method.

**Comment by Mumfrey** [comment]
Don't inject. Provide an empty stub method in the common mixin which is called where you want your injection to happen. Then in the downstream mixin simply overwrite that method.

eg. **Mixin 1**
```java
void someCommonMethod(int foo, int bar) {
     this.someStub(foo);
     // blah
}

void someStub(int foo) {
    // do nothing :(
}
```

**Mixin 2**
```java
void someStub(int foo) {
    // do something with foo!
}```
