### ISSUE TITLE
always adding "." to package

### ISSUE THREAD

**Issue by kadir1243** [SpongePowered/Mixin#540]
mixin package is empty
but my mixin plugin adds mixin (mixin classes in the default package)
gives this error :
[main/FATAL] (mixin) Mixin prepare failed preparing ExampleMixin in kajava.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin '.ExampleMixin' was not found

**Comment by Mumfrey** [comment]
You must use a package, mixins are not classes and must exist in a package where loadable classes do not exist, putting mixins in the default package is not supported.
