### ISSUE TITLE
how remove this lines with mixin????? without @Overwrite

### ISSUE THREAD

**Issue by RezaNajafianRN** [SpongePowered/Mixin#543]
public void drawScreen(int mouseX, int mouseY, float partialTicks)
{
_**GlStateManager.disableAlpha();
this.renderSkybox(mouseX, mouseY, partialTicks);
GlStateManager.enableAlpha();
Tessellator tessellator = Tessellator.getInstance();
WorldRenderer worldrenderer = tessellator.getWorldRenderer();**_
int i = 274;
int j = this.width / 2 - i / 2;
int k = 30;
this.drawGradientRect(0, 0, this.width, this.height, -2130706433, 16777215);
this.drawGradientRect(0, 0, this.width, this.height, 0, Integer.MIN_VALUE);
this.mc.getTextureManager().bindTexture(minecraftTitleTextures);
GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);
}

**Comment by Earthcomputer** [comment]
With difficulty. Also this is not a support forum, use the discord for support questions
