### ISSUE TITLE
Mixin apply failing causing Minecraft Forge to stall on startup but not crash.

### ISSUE THREAD

**Issue by OrsellGIT** [SpongePowered/Mixin#553]
Hi, I'm in the darkness when it comes to how forge works or Mixin, but one thing for sure I found is that Mixin, or something else, isn't working relating to it. I've removed the mods that seem to cause the issue, but it seems to always result in a kind of crash that doesn't display that it crashed but says in the console. I do not know if this is the right place to report this kind of thing, but I can't find anywhere else that it is proper to report something relating to Mixin. Not only is there a fatal error concerning Mixin, but afterward is also an InvocationTargetException. I've included the complete log (including debugging texts) with all mods-enabled if you want a log with the problem mods disabled or without the debug text, I'll do so. If this is the wrong place to report, please redirect me to the right site. This is running Minecraft Forge 1.12.2 forge-14.23.5.2860, running off the Curse Forge Launcher. Thank you for your time.

[debug.log](https://github.com/SpongePowered/Mixin/files/7810586/debug.log)

**Comment by Mumfrey** [comment]
This is an issue tracker for bugs and features related to mixin, not a support forum.

> I do not know if this is the right place to report this kind of thing, but I can't find anywhere else that it is proper to report something relating to Mixin.

Except the discord link at the very top of the readme, or the forge forums, or literally a dozen other places like the support pages for the mods which are conflicting? You have a conflict between two mods, they're even mentioned in the error, this is not a mixin bug this is intended behaviour.

**Comment by OrsellGIT** [comment]
Hi,
Sorry for posting in the wrong place. If it's a conflict between two mods do you mind pointing out where in the log they conflict, because I've never been able to find anything else that went wrong? Again sorry for posting in the wrong place. Once I learn which two mods are having trouble I’ll be on my way.
Thank you for your help.

**Comment by Mumfrey** [comment]
Read the error message:
```
Mixin apply failed controllable.mixins.json:client.MinecraftMixin -> net.minecraft.client.Minecraft:
    org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException
    @At("INVOKE") on net/minecraft/client/Minecraft::sendClickBlockToController with priority 1000
    cannot inject into net/minecraft/client/Minecraft::func_184117_aA()V
    merged by com.modularwarfare.mixin.client.MixinMinecraft with priority 1000
    [
        PREINJECT Applicator Phase
        -> controllable.mixins.json:client.MinecraftMixin
        -> Prepare Injections ->
        -> modify$zzm000$sendClickBlockToController(Z)Z -> Prepare
    ]
```
This is **still** not a support forum and you **still** should have asked in discord. :frowning_face:
