### ISSUE TITLE
Typo in Accessor.java

### ISSUE THREAD

**Issue by Jack-Papel** [SpongePowered/Mixin#556]
https://github.com/SpongePowered/Mixin/blob/155314e6e91465dad727e621a569906a410cd6f4/src/main/java/org/spongepowered/asm/mixin/gen/Accessor.java#L71

On this line, it says `maye` instead of `may`.

**Comment by Mumfrey** [comment]
If the error doesn't in any way affect actually understanding the text, then it's seriously just not worth the overhead of the issue, a message in discord is perfectly adequate.

For example if the typo is "does" when it should be "doesn't", or "may" when it should be "must", there's an important semantic distinction to be made. Those are worth flagging. But a single-character typo that doesn't in any way affect the meaning - or even the parsing - of the sentence? Yeah, nah.

**Comment by Jack-Papel** [comment]
Sure. Thanks for the quick response. I'll head to the discord next time instead if I notice anything else.
