### ISSUE TITLE
Injection into method call from child of TargetClass

### ISSUE THREAD

**Issue by FlashHUN** [SpongePowered/Mixin#561]
If we have two classes that inherit a method from TargetClass that has an injection and ChildClassA overrides it while ChildClassB doesn't, calling the method from ChildClassA will not produce the injected behaviour while ChildClassB will. How could I also make ChildClassA work the same way?

In this example, interacting with any block that doesn't override BlockBehavior#use will log "used" to the console, while interacting with blocks like the chest will not print out anything:

BlockBehavior.java
```java
public InteractionResult use(BlockState p_60503_, Level p_60504_, BlockPos p_60505_, Player p_60506_, InteractionHand p_60507_, BlockHitResult p_60508_) {
  return InteractionResult.PASS;
}
```

ChestBlock.java
```java
public InteractionResult use(BlockState p_51531_, Level p_51532_, BlockPos p_51533_, Player p_51534_, InteractionHand p_51535_, BlockHitResult p_51536_) {
  if (p_51532_.isClientSide) {
     return InteractionResult.SUCCESS;
  } else {
     MenuProvider menuprovider = this.getMenuProvider(p_51531_, p_51532_, p_51533_);
     if (menuprovider != null) {
        p_51534_.openMenu(menuprovider);
        p_51534_.awardStat(this.getOpenChestStat());
        PiglinAi.angerNearbyPiglins(p_51534_, true);
     }

     return InteractionResult.CONSUME;
  }
}
```

BlockBehaviourMixin.java
```java
@Mixin(BlockBehaviour.class)
public class BlockBehaviourMixin extends net.minecraftforge.registries.ForgeRegistryEntry<Block> {

  @Inject(method = "use", at = @At("HEAD"))
  public void useHead(BlockState state, Level level, BlockPos pos, Player player, InteractionHand hand, BlockHitResult hitResult, CallbackInfoReturnable<InteractionResult> ci) {
    Main.LOGGER.info("used");
  }
}
```

**Comment by gabizou** [comment]
It isn't intended to blanket injections across a hierarchy for overridden methods. If you want to target overridden methods, you have to explicitly create a mixin and inject into said targets. The problem you're facing is plain and simple OOP where we're expecting subclasses to have different behaviors. To properly interact with `use`, you'd want to inject instead at the callsites of `use` instead of in the method of BlockBehavior.
