### ISSUE TITLE
Missing toString override in GlobalProperties$Keys causes incorrectly named Keys due to string concatenation with existing Keys

### ISSUE THREAD

**Issue by DJtheRedstoner** [SpongePowered/Mixin#562]
The lack of a toString override in [`GlobalProperties$Keys`](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/launch/GlobalProperties.java#L43) makes the following code (and other similar instances) create a key similar to `org.spongepowered.asm.launch.GlobalProperties$Keys@239b0f9d.default`. https://github.com/SpongePowered/Mixin/blob/155314e6e91465dad727e621a569906a410cd6f4/src/main/java/org/spongepowered/asm/mixin/MixinEnvironment.java#L1096

**Comment by Mumfrey** [comment]
Thanks for opening this, marked as bug.
