### ISSUE TITLE
How do I use mixin in MCP to build a client, instead of building a forge mod or sponge plugin?

### ISSUE THREAD

**Issue by Chaosdave34** [SpongePowered/Mixin#565]
Hello, is there a way to use Mixin without Forge or Sponge, but in a MCP project? I want to use it to build a custom Minecraft client.

**Comment by gabizou** [comment]
This isn't a support forum, nor a related Mixin question. Sounds like you don't know the basis of how MCP works (the toolchain), there's modding platforms for a reason (because they figured out how to build such toolchains).
