### ISSUE TITLE
ClassInfo cache is never cleared

### ISSUE THREAD

**Issue by altrisi** [SpongePowered/Mixin#570]
The cache keeps growing without ever being cleared, being a waste of memory after mixins have been applied.

https://github.com/SpongePowered/Mixin/blob/155314e6e91465dad727e621a569906a410cd6f4/src/main/java/org/spongepowered/asm/mixin/transformer/ClassInfo.java#L670-L675

**Comment by Mumfrey** [comment]
> after mixins have been applied.

and when is that exactly?

**Comment by altrisi** [comment]
While getting that may not be the easiest, the caching strategy could be tweaked to not be wasting memory in most cases, not necessarily clearing only when it's known they're completely useless. A bit more compute time if some mixin hasn't been applied after a while is better than having lots of memory wasted all the time in there, in my opinion.

From a quick look at heap dump with memory analyzer, that hashmap was using over 10MB with a single fabric mod (in a dev env if that matters).
