### ISSUE TITLE
Cannot Inject into Lambda's

### ISSUE THREAD

**Issue by hYdos** [SpongePowered/Mixin#571]
Mixin expects only public methods but it also wants all static methods to be private in a Mixin. Below is an example of how you can run into this issue.
Example Mixin: 
```
@Mixin(RegistryAccess.class)
public interface RegistryAccessMixin {

    @Inject(method = "method_30531", at = @At("RETURN"), cancellable = true, locals = LocalCapture.PRINT)
    private static void hookBuiltinRegistriesEvent(@NotNull CallbackInfoReturnable<Map<ResourceKey<? extends Registry<?>>, RegistryAccess.RegistryData<?>>> cir) {
        //cir.setReturnValue(net.minecraftforge.experimental.registries.DataPackRegistriesHooks.addBuiltinRegistriesEvent(cir.getReturnValue()));
    }
}
```

This Mixin tries to inject into a lambda inside of the interface RegistryAccess. The bytecode of the class states that the method is `public static synthetic method_30531()Lcom/google/common/collect/ImmutableMap;` meaning that it requires the @Inject method to be static and private. The issue with this is that mixin will give `Interface mixin contains a non-public method!`. Setting the method to public will then make Mixin say `Mixin dynamicRegistries.mixins.json:RegistryAccessMixin contains non-private static method`

**Comment by hYdos** [comment]
This issue was ran into on a forge environment but thanks, Ill move the issue there.

**Comment by hYdos** [comment]
Forge doesnt seem to have a mixin fork. Are you sure vanilla mixin cant inject interfaces?

> You can't inject in interfaces on stock mixin. This should probably be an issue on Fabric's fork.

**Comment by LlamaLad7** [comment]
An architectury environment? You seem to be using yarn

**Comment by hYdos** [comment]
> Are you in an architectury environment? You seem to be using yarn

Yep

**Comment by Earthcomputer** [comment]
> Are you sure vanilla mixin cant inject interfaces?

Yes

**Comment by LlamaLad7** [comment]
IIRC Architectury uses Fabric Mixin in dev even on Forge. Should be clear from the console output.

**Comment by hYdos** [comment]
> IIRC Architectury uses Fabric Mixin in dev even on Forge. Should be clear from the console output.

Oh alright my bad.

**Comment by hYdos** [comment]
This is actually an issue with Sponge Mixin. See #497
