### ISSUE TITLE
Trying to modifyvariable flag in EntityRenderer.class doesn't work 

### ISSUE THREAD

**Issue by JoeV6** [SpongePowered/Mixin#573]
i'm new to Mixins, so can someone check if this is a bug or if my code is just wrong

Code:

package com.LPC1.Lmod.injection.mixins;

import net.minecraft.client.renderer.EntityRenderer;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.ModifyVariable;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(EntityRenderer.class)
@SideOnly(Side.CLIENT)
public class MixinEntityRenderer {

    @ModifyVariable(method = "getMouseOver", at = @At(value = "org.spongepowered.asm.mixin.injection.points.BeforeReturn", ordinal = 0))
    private boolean getMouseOver(boolean flag) {
        return true;
    }
}

**Comment by Geolykt** [comment]
Well, considering that we may not know what the code SHOULD do and what it ACTUALLY does, it appears to be working as intended

**Comment by Zidane** [comment]
**This is an issue tracker for issues with Mixin itself not a support forum**

For instance in using Mixin, feel free to join us on Discord (the link is in the README) to discuss this further.
