### ISSUE TITLE
Mixing into a Fabric Mod

### ISSUE THREAD

**Issue by DeMineArchiver** [SpongePowered/Mixin#577]
Can I use `@Redirect` to redirect a method from another Fabric mod? I would like to redirect the `new ButtonWidget` call in the `init` method of Mod Menu's mod `ModsScreen` class. So far I have tried many methods, but when I try to use `@Redirect` in ModsScreen, it always throws the same error.

[Log (Stacktrace)](https://pastebin.com/PhD7pQMF)

Once I remove the redirect, the code works just fine and the mixin doesn't give any errors.
My redirect code:
```Java
@Redirect(method = "init", at = @At(value = "NEW", target = "Lnet/minecraft/client/gui/widget/ButtonWidget;<init>(IIIILnet/minecraft/text/Text;Lnet/minecraft/client/gui/widget/ButtonWidget$PressAction;)V"))
    public ButtonWidget changeButton(int x, int y, int width, int height, Text message, ButtonWidget.PressAction onPress) {
        return new ButtonWidget(x, y, width, height,
                new TranslatableText("modmenu.youtube"), onPress);
    }
```

**Comment by Geolykt** [comment]
Note that fabric has it's own fork, so it might be better to report the issue there unless they say that it is an issue with sponge's mixin
