### ISSUE TITLE
Help Pls I cant get it to work in mods folder.

### ISSUE THREAD

**Issue by Th3C0D3R1** [SpongePowered/Mixin#579]
When I went to put it in my mods folder, nothing happened. So I used my coder experience and looked through all the code for errors and I found that ClassVisitor.java has a lot of errors. My current coding terminal isn't working, so I am unable to fix the current error, I am also looking for a new coding terminal to fix my current coding terminal. Anyone know any good coding terminals? Thank you and have a happy fellow coding day,

-Th3C0D3R1

**Comment by gabizou** [comment]
This is an issue tracker for reporting bugs and requesting features. For questions please use discord.

Your statement translates to "I want to use your custom gear box, but didn't read the manufacturer's manual on replacing the gear box." A lot of what you're describing is not knowing anything about build tools or already established frameworks solving how to use Mixins in a modding environment.

[Link to #mixin discord channel](https://discord.gg/tBcwxz2)
