### ISSUE TITLE
Abnormal cores + Sponge 1.16.5

### ISSUE THREAD

**Issue by codcrusher12** [SpongePowered/Mixin#582]
So I've been having an issue running abnormal cores and Sponge together on 1.16.5 and I know this issue was fixed in 1.17 and was wondering if anyone had the file/ code to make it work on 1.16.5. Thank you

**Comment by zml2008** [comment]
This is the issue tracker for Mixin, not the Sponge plugin platform implementation.

**Comment by codcrusher12** [comment]
> 

But the problem is within the mixin file so I figured someone could help me with the coding here..

**Comment by gabizou** [comment]
The [fix for abnormals](https://github.com/team-abnormals/blueprint/commit/df4932960266f2e30a541097811193c17d1bb339) has already been made, but abnormals has not made a release with it. This issue tracker is NOT for incompatibilities with mods.

**Comment by codcrusher12** [comment]
> The [fix for abnormals](https://github.com/team-abnormals/blueprint/commit/df4932960266f2e30a541097811193c17d1bb339) has already been made, but abnormals has not made a release with it. This issue tracker is NOT for incompatibilities with mods.

But where is the fix..... I've been looking for a week and have found absolutely no fix at all
