### ISSUE TITLE
Invalid descriptor, issues with CallbackInfo

### ISSUE THREAD

**Issue by MoltenHydrogen** [SpongePowered/Mixin#583]
If you couldn't tell by the title I'm a newbie, and while I know my way around an IDE I don't have a programmer's knowledge. Apologies for the crappy terminology. I'm just trying to update [this mod](https://github.com/PotatoPresident/worldborderfixer) to 1.19 for my server. 

I updated the properties from 1.18.2 to 1.19 and changed the `GetCoordinateScale` methods to `CoordinateScale`, as it seemed they were no longer supported in the new version.

I was able to successfully build the mod but I crash upon startup with this error:
`[main/ERROR] (FabricLoader/Mixin) Mixin apply for mod multiworldborders failed multiworldborders.mixins.json:WorldMixin from mod multiworldborders -> net.minecraft.world.World: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on multiworldborders.mixins.json:WorldMixin from mod multiworldborders->@Inject::setWorldBorderWorld()V! Expected (Lnet/minecraft/world/MutableWorldProperties;Lnet/minecraft/util/registry/RegistryKey;Lnet/minecraft/util/registry/RegistryEntry;Ljava/util/function/Supplier;ZZJILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found ()V [INJECT Applicator Phase -> multiworldborders.mixins.json:WorldMixin from mod multiworldborders -> Apply Injections ->  -> Inject -> multiworldborders.mixins.json:WorldMixin from mod multiworldborders->@Inject::setWorldBorderWorld()V]`

The error seems to suggest that it expects the path for `CallbackInfo` to start with `ZZJILorg` instead of `ZZJLorg`. I'm not entirely sure if this is an error of the mod or an error in Mixin, but either way I need guidance on how to resolve this error.

Here's the code that's setting off the error:
`private void setWorldBorderWorld(MutableWorldProperties properties, RegistryKey<World> registryRef, RegistryEntry<DimensionType> registryEntry, Supplier<Profiler> profiler, boolean isClient, boolean debugWorld, long seed, CallbackInfo ci) {
        World world = (World) (Object) this;
        ((BorderWithWorld) world.getWorldBorder()).setWorld(world);
    }`

**Comment by SizableShrimp** [comment]
These issue reports are for issues with mixin, not user error. Please use the mixin discord or somewhere else. 🙂
