### ISSUE TITLE
How obfuscate mixin classes ?

### ISSUE THREAD

**Issue by RezaNajafianRN** [SpongePowered/Mixin#586]

**Comment by RezaNajafianRN** [comment]
Play help me I can't join discord Channel
I think I am ban

Pls unban me RezaNajafian

**Comment by RezaNajafianRN** [comment]
Or how protect mixin clients?

**Comment by Geolykt** [comment]
There is also the mixin irc channel fyi

**Comment by RezaNajafianRN** [comment]
Pls unban me
