### ISSUE TITLE
Unable to Suppress @Shadow warning: Unable to locate obfuscation mapping for @Shadow field

### ISSUE THREAD

**Issue by fxmorin** [SpongePowered/Mixin#588]
Using a simple mixin into Sodium's menu: `SodiumOptionsGUI.class`
I get the warning `warning: Unable to locate obfuscation mapping for @Shadow field`
```java
@Mixin(SodiumOptionsGUI.class)
public class SodiumOptionsGUIMixin {

    @Shadow
    @Final
    private List<OptionPage> pages;
    
    // ...
    
}
```
The method does exist, and it works perfectly fine. If I attempt to remap the mixin no longer works (obviously).

It would be nice if I could suppress the warning. Since that is not currently possible, [the printMessage() used is not suppressable](https://github.com/SpongePowered/Mixin/blob/155314e6e91465dad727e621a569906a410cd6f4/src/ap/java/org/spongepowered/tools/obfuscation/AnnotatedMixinElementHandlerShadow.java#L172)

**Comment by AterAnimAvis** [comment]
Why not just disable the remapping on the annotation
<https://github.com/SpongePowered/Mixin/blob/b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52/src/main/java/org/spongepowered/asm/mixin/Shadow.java#L89-L104>

**Comment by fxmorin** [comment]
Didn't know that was n option, thanks
