### ISSUE TITLE
How to access a private class in another class ?

### ISSUE THREAD

**Issue by Wizi8914** [SpongePowered/Mixin#594]
In a project I'm trying to get the textureState variable but this one is of type class which is inside another class I asked several people but each one didn't know how to answer or they asked me to try things which didn't work 

![image](https://user-images.githubusercontent.com/45132525/183469276-a3257e6f-ebe4-4db9-ab0f-be42cd72c691.png)

**Comment by tennox** [comment]
I think using an access widener is the way to go:
https://www.fabricmc.net/wiki/tutorial:accesswideners

see also https://github.com/SpongePowered/Mixin/issues/578

**Comment by gabizou** [comment]
This is an issue tracker, not a support forum.
