### ISSUE TITLE
OutOfMemoryError when compile java files at runtime

### ISSUE THREAD

**Issue by MrMks** [SpongePowered/Mixin#595]
Recently i'm writing a runtime compile mod so then I can add and remove functions on my server dynamically, via JavaCompiler provided by javax.tools.

When I testing the performance of the compiler, it ran into a OutOfMemoryError, which related to a map named instances in AnnotatedMixins.

It seems like a memory leak behavior, so is there any way to resolve this problem?

(English isn't my first language, sentences may looks strange, please just ignore it)

**Comment by gabizou** [comment]
It sounds like you're asking for a feature request for dynamic re-running of the annotation processor. We're not going to entertain a feature for the time being as our developer time is fairly limited as is.
