### ISSUE TITLE
Error when building Fabricmc project: @At() not fully qualified

### ISSUE THREAD

**Issue by borisJohnsonDaBest** [SpongePowered/Mixin#596]
When I try to build a fabricMC project, i get this error:
`~/intellij/fabric/src/main/java/net/amogus/modded/mixin/ExampleMixin.java:13: error: @At(HEAD.<target>) is not fully qualified, missing owner
    @Inject(method = "tick()V", at = @At(value = "HEAD", target = "go()V", shift = At.Shift.BY, by = 9))
                                     ^`
 Here is my code:
 

> package net.amogus.modded.mixin;

> import org.spongepowered.asm.mixin.Mixin;
> import org.spongepowered.asm.mixin.injection.Inject;
> import org.spongepowered.asm.mixin.injection.At;

> import net.minecraft.entity.projectile.ArrowEntity;

> import net.amogus.modded.ExampleMod;

> @Mixin(ArrowEntity.class)
> public class ExampleMixin {
>     @Inject(method = "tick()V", at = @At(value = "HEAD", target = "go()V", shift = At.Shift.BY, by = 9))
>    private void go() {
>        ExampleMod modInst = new ExampleMod(((ArrowEntity)(Object)this));
>        modInst.doThing();
>        }
>    }

**Comment by zml2008** [comment]
This is a bug tracker, not a support forum. What you are describing does not appear to be a bug.
