### ISSUE TITLE
How to provide custom mixin service implementation without hacking the whole library

### ISSUE THREAD

**Issue by xxDark** [SpongePowered/Mixin#599]
And dealing with service loaders?
Thanks

**Comment by LlamaLad7** [comment]
I'd suggest using [Fabric's fork of Mixin](https://github.com/FabricMC/Mixin), as they have [a mechanism for setting an implementation explicitly](https://github.com/FabricMC/Mixin/pull/85/files).

**Comment by Mumfrey** [comment]
This kind of discussion is more suited to discord as this is an issue tracker rather than a forum.
