### ISSUE TITLE
[FEATURE] Target All Subclasses of a Class

### ISSUE THREAD

**Issue by ByThePowerOfScience** [SpongePowered/Mixin#601]
I'm making a lag profiler, and I want to target every single implementation of a method, specifically `Block#onRandomTick()`.  While this is easily done through ASM, I want to use the Mixin framework since the whole reason I'm making this is because TickCentral doesn't like some Mixins.  However, as far as I can tell, this can't be done in Mixin?

If it is not already a feature, I propose the following syntax:
```java
@Mixin(targets="*") @Pseudo
public abstract class Foo extends FooSuper {
    @Inject(method="bar", at=@At("HEAD"))
    private void inject(CallbackInfo ci) {}
}
```

This is in keeping with the current syntax for pseudo-mixins being determined based on the target's superclasses, but applied as a global transformation instead of a targeted one.  Any classes that extend `FooSuper` and implement `bar` will have the injection applied to them, obfuscated according to the superclass's method mappings.

**Comment by ByThePowerOfScience** [comment]
I did the thing I wanted to do by another means, but the global target would still be appreciated.

**Comment by Mumfrey** [comment]
No, this is something Mixin specifically will not support. Mixins target specific known classes and will never target wildcards or arbitrary selectors.
