### ISSUE TITLE
Problem when loading in world.

### ISSUE THREAD

**Issue by Cycloness** [SpongePowered/Mixin#607]
![image0](https://user-images.githubusercontent.com/23457533/193603224-5a9b1427-36d5-4af2-9e21-60e258cbf530.jpg)

This is the crashcode that pops up whenever I boot up a game/server on my macbook.
Its the first 1.19 create version, any ideas as to how I fix it?

**Comment by Mumfrey** [comment]
This repo is for issues and bugs with Mixin, not for asking questions related to mods, contact the author of the mod.
