### ISSUE TITLE
PatchedClass does not define or inherit an implementation of the resolved method 'abstract void method()' of interface my.package.Interface

### ISSUE THREAD

**Issue by edgarogh** [SpongePowered/Mixin#610]
Hello,

I'm following the [Mixin guide](https://mixin-wiki.readthedocs.io/tricks/) to call a method on a patched class by having it implement a new interface. I have the following interface:

```java
interface Interface {
  void method();
}
```

and it is implemented by the mixin class in order to be implemented on the patched class.

Elsewhere in the code, I'm doing:

```java
if (potentiallyPatchedClass instanceof Interface i) {
  i.method();
}
```

When this code path gets run, Minecraft crashes with the following error message:
`Receiver class PatchedClass does not define or inherit an implementation of the resolved method 'abstract void method()' of interface my.package.Interface`. Of course, the method is actually implemented at compile-time or the Java compiler wouldn't even let me launch the game. I also tried not using the fancy `instanceof` cast hybrid syntax thing and it doesn't help.
This suggests that the interpreter entered the `if` statement because the class declares that it implements the interface, but for some reason the method hasn't been defined by Mixin upon patching?

Am I doing something wrong? I can try to make an MRE but setting up a Forge+Mixin project is very long so I'll only do it if necessary.

**Comment by LlamaLad7** [comment]
This is an issue tracker, for support use the discord https://discord.gg/tBcwxz2

**Comment by edgarogh** [comment]
I thought this was a bug (or at least a problem in the docs), that's why I opened an issue.
I'll go to the Discord server if that looks like a simple issue on my side, thank you.

**Comment by Mumfrey** [comment]
Those docs aren't mine though, so you'd need to report an issue to the author of those.
