### ISSUE TITLE
com.mojang.authlib.GameProfile.class not found/LinkageError when using bridge.

### ISSUE THREAD

**Issue by Skitbet** [SpongePowered/Mixin#614]
I am currently working on a client using Mixin but for the last day and a half, I've been trying to fix the error below. 
![image](https://user-images.githubusercontent.com/54096334/204141412-d8038dda-a26a-407c-bc3f-19d009bd7814.png)
![image](https://user-images.githubusercontent.com/54096334/204141422-386e9a47-e995-4822-9698-de1024bcf357.png)

This all started after I made a session mixin and bridge so I could create an Alt system on the client.

### **Mixin Class**
![image](https://user-images.githubusercontent.com/54096334/204141455-4b9cf1cd-6264-49d2-9835-680888c463ae.png)

### **Bridge Class**
![image](https://user-images.githubusercontent.com/54096334/204141459-b1e28110-4b90-460f-a616-8f40d39629be.png)

Very simple classes yet nothing I tried seems to have fixed this error. I may just be dumb as I have taken a year break from developing and just came back.

**Comment by LlamaLad7** [comment]
This is an issue tracker. Use the discord for questions / support.
