### ISSUE TITLE
Mixins dont injecting in EventBus

### ISSUE THREAD

**Issue by Blu3cr0ss** [SpongePowered/Mixin#615]
So yeah, all classes mixing fine, for instance:
[18:16:19] [pool-3-thread-1/DEBUG] [mixin/]: Mixing MixinAbstractHorse from fhax16.mixins.json into net.minecraft.entity.passive.horse.AbstractHorseEntity
but when im doing @Mixin(EventBus.class)
its just dont mixing...
no error messages
forge 1.16.5
'org.spongepowered:mixingradle:0.7-SNAPSHOT'
'org.spongepowered:mixin:0.8.5'
P.S.: here is my mixins congig
{
  "required": true,
  "package": "idk.bluecross.fhax16.mixin.impl",
  "minVersion": "0.8",
  "compatibilityLevel": "JAVA_8",
  "injectors": {
    "defaultRequire": 1
  },
  "refmap": "fhax16.mixins.refmap.json",
  "mixins": [
    "MixinAbstractHorse",
    "MixinEventBus"
  ]
}

**Comment by marchermans** [comment]
Injecting into core forge libraries is not supported.

**Comment by Earthcomputer** [comment]
Neither are people using github issues as a support forum. Use the mixin channel in the sponge discord in future.

**Comment by Blu3cr0ss** [comment]
> Injecting into core forge libraries is not supported.
thats sooo bad...
then ho should i do event manager?
