### ISSUE TITLE
[Question] How to use LegacyLauncher with mixin 8.3

### ISSUE THREAD

**Issue by FatSaw** [SpongePowered/Mixin#619]
I try to update Bukkit based server core on 1.12.2 witch uses mixin 7. to newer java version (11). But mixin 8.3 loads modlauncher bootstarp. Is there example or manual how to properly load mixin 8.3 with legacylauncher?

**Comment by LlamaLad7** [comment]
This is an issue tracker. Use [the discord](https://discord.gg/sponge) for questions
