### ISSUE TITLE
Normal mod is ignored when using mixins

### ISSUE THREAD

**Issue by iocmet** [SpongePowered/Mixin#620]
I need combine core mod normal mod and mixins in my minecraft mod but when i adding
`'TweakClass': 'org.spongepowered.asm.launch.MixinTweaker'` 
to manifest normal mod is ignored when launching minecraft
Why?

**Comment by zml2008** [comment]
Thanks for reaching out! Unfortunately this is a bug tracker for Mixin issues only - while you appear to be requesting support for using Mixin with an older version of FML. If you have a support question about Mixin itself, feel free to ask on our Discord :)
