### ISSUE TITLE
Access non-static variables without having access to the object

### ISSUE THREAD

**Issue by gkursi** [SpongePowered/Mixin#621]
Basically there is a place in my project that says something like this: ```new MyClass("")```, without having it assigned to a variable. Is there a way to get this object, or set the values inside of it some other way? I wrote an accessor for it, but the variable is not static.

**Comment by LlamaLad7** [comment]
This is an issue tracker, not a support forum. Use the discord for support questions and provide more context with the actual target method, what you want to change, why, etc
