### ISSUE TITLE
Serverside Mixin Application failed

### ISSUE THREAD

**Issue by Kapitencraft** [SpongePowered/Mixin#624]
I have made a Mixin, that is @Accessor "protected boolean jumping" and "private int noJumpDelay" in LivingEntity.
If i try to cast the Mixin to a ServerPlayer, it is throwing a ClassCastExeption and it isn't getting called. (Also Client and Local Player work fine)

**Comment by LlamaLad7** [comment]
This is not a support forum. Go to the discord and provide far more detail.
