### ISSUE TITLE
How can i add "notch" data to my mixin refmap? (Minecraft 1.16.5)

### ISSUE THREAD

**Issue by sxmurxy2007** [SpongePowered/Mixin#630]
### I am using mixins to develop an addon for one launcher, and addon refmap should contain "notch" data, as in other addons (i don't know how they did it). 

**My addon refmap:**
<img width="646" alt="Снимок экрана 2023-05-08 081336" src="https://user-images.githubusercontent.com/46312126/236705081-d58b65ae-05da-46ae-b8d2-e16f12147d06.png">

**Other addon refmap:**
<img width="643" alt="image" src="https://user-images.githubusercontent.com/46312126/236705116-7a3f7b7a-1b78-45e4-a0cd-08e0590b298a.png">

**I am using Mixin 0.8.5 and MixinGradle 0.7-SNAPSHOT. 
Or should I ask this question elsewhere?**

**Comment by Mumfrey** [comment]
> Or should I ask this question elsewhere?

Hi. Yes please ask support questions in the discord channel, this issue tracker is for feature requests and bugs.
