### ISSUE TITLE
Mixin Issues compatitibilty with recipes mixing

### ISSUE THREAD

**Issue by Arginou57** [SpongePowered/Mixin#632]
Hey, the 2 mods are working well together on solo client, so on server side i have this issue

https://hastebin.com/share/aberaruvem.php

forge version: forge-1.19.2-43.2.11
Cucumber version : Cucumber-1.19.2-6.0.7.jar
Steams and rails version : Steam_Rails-1.3.5+forge-mc1.19.2.jar

**Comment by Mumfrey** [comment]
This is an issue tracker for bugs and feature requests for Mixin, crashes related to mods using it should be raised against the mods in question.
