### ISSUE TITLE
[Question] Modifying existing Bytecode via Mixin

### ISSUE THREAD

**Issue by BlazingTwist** [SpongePowered/Mixin#635]
I'm aware of [Overwriting Methods](https://github.com/SpongePowered/Mixin/wiki/Introduction-to-Mixins---Overwriting-Methods) but that is too destructive in my opinion.

I was hoping it would be possible to do something like [Harmony's Transpilers](https://harmony.pardeike.net/articles/patching-transpiler.html)

**My Usecase:**
I have a Method that I want to modify with Mixin:
```java
public void targetMethod() {
    /* A bunch of lines I DON'T want to execute, sometimes */

    /* A bunch of lines I DO want to execute, always */
}
```

Ideally I could modify the method to look like this:
```java
public void targetMethod() {
    if (MyMixin.shouldExecuteFirstBlock()) {
        /* A bunch of lines I DON'T want to execute, sometimes */
    }

    /* A bunch of lines I DO want to execute, always */
}
```

**Comment by LlamaLad7** [comment]
Your use case is probably possible but you _**always need to show the actual situation**_. Pseudocode is entirely unhelpful when talking about mixins. However, this is an issue tracker; post your question with full details in the discord.

**Comment by BlazingTwist** [comment]
I disagree, my request is basically "give my the bytecode of that method and let me edit it directly".
Which should not depend on the specific content of the method.

**Comment by LlamaLad7** [comment]
Modifying bytecode directly is a terrible idea for compatibility and that is why mixin exists in the first place. In any actual situation you will be able to do what you want with mixin's existing tools. If you have an actual scenario then show it, if not then we can't help. Regardless, this is still not a support forum and further discussion should go to the discord.
