### ISSUE TITLE
Java 24/Project Leyden Support

### ISSUE THREAD

**Issue by thejudge156** [SpongePowered/Mixin#670]
Probably not a critical issue, but I figured it should be brought up.

Project Leyden and/or Java 24 (class version 68) is broken with Mixin, 

https://mclo.gs/EuQOO1k

**Comment by zml2008** [comment]
There is no "Java 24" that exists yet -- the errors you see are because ASM cannot support a version that has not been finalized.

**Comment by gabizou** [comment]
Java 23 hasn’t been fully released yet, there’s a reason 23 and 24 are still experimental (or in ramp-down phase 1).
