### ISSUE TITLE
Only apply mixins to logical server

### ISSUE THREAD

**Issue by FamroFexl** [SpongePowered/Mixin#680]
I am currently using mixins for common, client, and the dedicated server ("mixins", "client", and "server" in `mixins.json`). However, I need a way to ensure mixins are only applied to a _logical server_, so that in the case of an integrated server, only the server-side logic is affected by the mixin transformations, while the client remains untouched.

I am attempting to modify classes that are shared between the client and server. However, I've encountered difficulties distinguishing between the client and the integrated server. Specifically:

- Using a `Level`’s`isClientSide` field isn't viable, as the `Level` instance I need is further up the call stack (on the server), and passing it down causes it to always appear as a server `Level`.
- I've also explored checking the stack trace for the `net.minecraft.client` package for signs the caller is a client, but this approach has not worked either.

For context, you can refer to the method `isWithinDistance` in [this source](https://github.com/FamroFexl/Circumnavigate/blob/develop/src/main/java/com/fexl/circumnavigate/mixin/chunkHandle/ChunkTrackingViewMixin.java).

**I realize that this might be impossible, given that the mixin transformed class on the integrated server is the same class for the client. This would mean you would have to generate separate classes for the integrated server and for the client.** 

Do you have any solutions or alternatives?

**Comment by FamroFexl** [comment]
If you registered two mixins with the same class, one registered in the client mixins and the other registered in the common mixins, would the client mixin override the common mixin? Would this mean only the server would use the common mixin?

**Comment by FamroFexl** [comment]
Ideally, I need complete separation of the logical client and logical server code.

**Comment by Earthcomputer** [comment]
This is not possible and not how the game works. This is a tracker for issues in Mixin, not for support. For further support use the mixin channel in the Sponge discord.
