### ISSUE TITLE
Java 23 support

### ISSUE THREAD

**Issue by mucookul** [SpongePowered/Mixin#682]
Hi maintainers, Java 23 is generally available now but it semes that you can't use it on SpongeMixin 0.8.7 as ASM is only updated for Java 21 (ASM 9.5), I believe updating ASM to version 9.7 will fix this. Would you consider this? (Don't know if you plan to support non-LTS Java versions)

**Comment by zml2008** [comment]
Mixin can use any version of ASM, runtime support depends on your environment (Fabric, Forge, NeoForge, etc)

**Comment by mucookul** [comment]
Okay, I was looking at this file: https://github.com/SpongePowered/Mixin/blob/master/gradle.properties

**Comment by mucookul** [comment]
Nvm theres a reason fabric doesn't support it, https://github.com/FabricMC/fabric-loader/issues/976#issuecomment-2356625536
