### ISSUE TITLE
Inject an interface into an interface.

### ISSUE THREAD

**Issue by FamroFexl** [SpongePowered/Mixin#683]
Right now, I have a WorldTransformer that is injected into a class. The injection includes a variable to store the transformer, and a getter and a setter for the transformer.

 I need the transformer to modify methods in the class. However, some of the methods are inside interfaces the class implements, meaning I can't apply the WorldTransformer to them. If I could implement the WorldTransformer's getter method inside an interface the class implements, I could access it from the implemented methods inside that interface.

**Comment by gabizou** [comment]
I'm not understanding what your situation is nor the structure of your mixins. This is an issue tracker, not a support forum. If you're asking for help to write mixins, please seek help either in [Discord](https://discord.gg/tBcwxz2) or somewhere else for your modding platform of choice.

In general, if I'm understanding the vagueness, you _cannot_ add non-static fields to an interface, per the [JVM specification](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-4.html#jvms-4.5):

> Fields of interfaces must have their ACC_PUBLIC, ACC_STATIC, and ACC_FINAL flags set; they may have their ACC_SYNTHETIC flag set and must not have any of the other flags in [Table 4.5-A](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-4.html#jvms-4.5-200-A.1) set (JLS §9.3).

**Comment by FamroFexl** [comment]
Nevermind. I figured it out. It is identical to how this Fabric API module is laid out:
[Interface to be injected](https://github.com/FabricMC/fabric/blob/1.21.2/fabric-block-view-api-v2/src/main/java/net/fabricmc/fabric/api/blockview/v2/FabricBlockView.java)
[Mixin class which injects the interface into the BlockView interface](https://github.com/FabricMC/fabric/blob/1.21.2/fabric-block-view-api-v2/src/main/java/net/fabricmc/fabric/mixin/blockview/BlockEntityMixin.java)

This really needs to be clarified in the [Interface Injection](https://fabricmc.net/wiki/tutorial:interface_injection) mixin tutorial. It isn't clear injecting an interface into an interface is even possible.

**Comment by gabizou** [comment]
Just so you're aware, you're pointing to wikis that aren't maintained by SpongePowered, they're maintained by the Fabric community. The purpose of those interfaces is however covered by the Mixin [official wiki ](https://github.com/SpongePowered/Mixin/wiki/Introduction-to-Mixins---Understanding-Mixin-Architecture#2-through-the-looking-glass) which is always recommended to read through to better understand how to properly use Mixins in general. Whether an interface is directly implemented or remaining abstract is irrespective of the target, and you can find several examples of implementing interfaces with mixins on top of [interface targets in Sponge itself](https://github.com/SpongePowered/Sponge/blob/3ddbb5600cf445a22f6e1ba8ae64f4afb1e795fe/src/mixins/java/org/spongepowered/common/mixin/api/minecraft/world/level/LevelReaderMixin_API.java#L68) and further more advanced usages to avoid naming [conflicts](https://github.com/SpongePowered/Sponge/blob/3ddbb5600cf445a22f6e1ba8ae64f4afb1e795fe/src/mixins/java/org/spongepowered/common/mixin/api/minecraft/world/level/LevelAccessorMixin_API.java#L140-L143).
