### ISSUE TITLE
Mixins cannot target a package-private class or protected inner class

### ISSUE THREAD

**Issue by Mumfrey** [SpongePowered/Mixin#7]
Paging @Zidane and @bloodmc

The title says it all. Because mixins require the ```@Mixin``` annotation to refer to the target class literal, they cannot reference protected inner classes or any package-private classes.

Looking for opinions on adding a second *targets* array to the ```@Mixin``` annotation which would allow additional targets to be specified as strings, this would allow even private inner classes to be referenced by a mixin by specifying the fully-qualified inner class name.

```java
@Mixin(targets = { "net.minecraft.entity.monster.EntityGhast$AILookAround" })
public abstract class MixinEntityGhastAILookAround {
```

There are use-cases where we would likely want to mix in to a package-private class such as the one mentioned above.

Any thoughts? My main concern is that this is pretty easy to screw up, which is why the hard class references are used in the first place, but at the same time the only other way to deal with this is via access transformers (assuming access transformers can change the visibility of classes, not sure if they can) so it could be a more straightforward way to target classes which would otherwise not be mixinable.

**Comment by Zidane** [comment]
Honestly, this seems like the best way to approach this.

**Comment by Mumfrey** [comment]
Since it's the one outstanding issue but nobody's commented, I was thinking of just either going ahead with this plan *or* just closing the issue until an actual use-case appeared and I got bugged into adding something like this anyway.

The two choices for implementation basically are:

* Add an extra array of strings to the `@Mixin` annotation
* Add an alternate version of `@Mixin` (eg. `@PrivateMixin`) which is identical in every way but just takes strings instead of class references.

**Comment by ryantheleach** [comment]
Would PrivateMixin error if a mixin could have been used instead?

**Comment by Mumfrey** [comment]
That would make sense.

**Comment by simon816** [comment]
I think a `String[] targets()` would be fine here, unless private-class specific parameters are needed there's not much reason to use another annotation.

**Comment by Mumfrey** [comment]
No particular reason, and programmatically it makes no odds either way, the complexity is pretty much exactly equal whether it's an extra property or an extra annotation.

Really it's just nicer that the `value` property is default if no other properties are specified and just leads to the slightly nicer

```java
@PrivateMixin("some.target.Clazz")
public abstract class SomeClazzMixin {
```

versus

```java
@Mixin(targets = "some.target.Clazz")
public abstract class SomeClazzMixin {
```

So there's that. Basically since annotation properties when being parsed with ASM or AP are all dynamic lookups anyway, it doesn't really make any odds either way since neither code will actually care what the actual annotation passed in is, as long as it has the relevant keys.

**Comment by bloodmc** [comment]
Lets go with option 2 for the sake of the users

```java
@Mixin(targets = "some.target.Clazz")
public abstract class SomeClazzMixin {
```

**Comment by Mumfrey** [comment]
Alrighty then!

**Comment by cossacksman** [comment]
@Mumfrey Is there any documentation on this, I can't seem to find it. A good use-case that I've stumbled across is that SpongeLoadingTicket is a private class in SongeChunkTicketManager, leaving me unable to access it to mixin.

**Comment by cossacksman** [comment]
Took me a while to find this as I couldn't find it in the documentation, is there any chance it could be made more obvious? A good use-case I found was trying to access `SpongeLoadingTicket` inside `SpongeChunkTicketManager`, since SpongeLoadingTicket is a private inner class. 

Would `@Mixin(targets = "org.spongepowered.mod.service.world.SpongeChunkTicketManager.SpongeLoadingTicket")` work for that means?
