### ISSUE TITLE
Disable decompiling when debug exporting mixin classes

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#82]
Using `mixin.debug.export` seems to always cause the decompiler to run for _all_ the exported classes currently, which delays the start a lot. It would be nice if this could be optionally disablable if you only need to look at one class you want to decompile manually using the IDE.

I might have missed this though, does an option exist for this?

**Comment by Mumfrey** [comment]
Decompiling is only enabled if you deliberately add fernflower to the classpath, to disable decompiling just **don't** add fernflower to your runtime classpath. You can also choose which classes are exported by using the [`mixin.debug.export.filter`](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/MixinEnvironment.java#L236-L249) option to specify class names/patterns to export.

**Comment by Mumfrey** [comment]
If the existing functionality suits your needs, just close this ticket. If you would prefer a separate filter for fernflower that can be added easily. However I normally find that I just set the filter to the package I'm working on, since in general you only care about a particular subset of classes when using export anyway.

**Comment by Minecrell** [comment]
Fernflower seems to be automatically added to the classpath when using Mixin as a Gradle dependency (at least I didn't add it manually). The export filter makes sense, although I would personally prefer if I could just disable fernflower globally without messing with the classpath so I don't need to set the classes I want to look at manually every time.

**Comment by Mumfrey** [comment]
Done.

**Comment by Minecrell** [comment]
Thanks!

**Comment by Mumfrey** [comment]
Backported changes to 0.4.7 so you shouldn't need to bump the sponge dependency to get these fixes.
