### ISSUE TITLE
When upgrading from 0.4.7 to 0.4.10, got a VerifyError

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#85]
Not entirely sure why, but, when trying to update and run in IDE, the game crashes immediately. Provided log:
https://gist.github.com/gabizou/0dba7458fca4c486d03b

**Comment by Mumfrey** [comment]
0.4.10 is not stable yet, this is expected. This is the reason I'm backporting any bugfixes to 0.4.7 currently. 0.4.10 is definitely not ready for prime time.
