### ISSUE TITLE
Incompatibility with CoFHCore? 

### ISSUE THREAD

**Issue by mcsnetworks** [SpongePowered/Mixin#86]
I opened a dialog with @skyboy, the dev for CoFH Core regarding a recent incompatibility with his product and Mixin, here's what I got in a response.

Dockter: skyboy, why you break my mixin's again with CoFH's transformer?  http://pastie.org/pastes/10648125/text

Dockter: I thought we had made peace regarding this subject :/

skyboy: i'm changing it back to what it was when it was first broken, since sponge doesn't work with any method of what i need to do

Dockter: So you've thrown in the towel with staying compatible?

skyboy: take up any issue you have with sponge not functioning reasonably

skyboy: frankly, if they weren't fucking around with my transformer, this method would work

skyboy: but oh well

Dockter: What exactly are we doing on the mixin side that you dont agree with?  Sponge is going to be the main server platform going forward so your guaranteeing to be incompatible

skyboy: you alter the contract FML establishes with ASM transformers

skyboy: my code isn't running when and where my code should be running, so it doesn't work at all, regardless of what changes i make

skyboy: works fine in FML, and i could even implement this as a raw ITweaker and it would still work

skyboy: it's sponge that breaks all of the logic

Dockter: I think that Lex and Mumfrey would disagree on this.

skyboy: i give no shits

Dockter: That is a really piss poor attitude to have.

Dockter: Where is mixin breaking the contract exactly?

Dockter: Cause if your right, we'll adjust.

skyboy: https://paste.kde.org/pkv7dqmts

skyboy: all of that bullshit between vanilla code and my code

skyboy: my transformer is not a mixin

skyboy: it relies on the stackdepth vanilla has to gather all of the data it needs to process things correctly

skyboy: the previous implementation that broke your stuff worked if only the vanilla classloader was present, but it breaking suggests sponge adds its own class loader somewhere to do its own processing, so when the class loads in a super classloader, they don't get to process it

skyboy: this one will work regardless of what classloader is present, but the stackdepth is non-negotiable

How can I proceed @Mumfrey?

**Comment by mcsnetworks** [comment]
Additional feedback from Skyboy:

if you had any way to add my logic to the transformer list for the vanilla classloader, but not to the mixin list, you could easily test to see if what i'm doing works correctly with sponge and settle where the issue is

**Comment by mcsnetworks** [comment]
His AT:  https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/asm/CoFHAccessTransformer.java

**Comment by Mumfrey** [comment]
Closing for now since this should be resolved as of 14f3f403dd3e7e3b29d117324e3ba499ce4e7ad7 and the corresponding CoFH/CoFHCore@c559069149a4f4e2728d78fd4365f2db95bb9ee3
