### ISSUE TITLE
Testing issue

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Mixin#89]
_From @gabizou on January 1, 2016 19:10_

This is a test issue for testing purposes.

_Copied from original issue: SpongePowered/SpongeForge#478_

**Comment by gabizou** [comment]
Testing comment.

**Comment by gabizou** [comment]
Testing comment.

**Comment by JBYoshi** [comment]
@gabizou 
So what is this about?

**Comment by gabizou** [comment]
This was a test for moving issues across repositories.
