### ISSUE TITLE
Fix loadAsMod/ForceLoadAsMod for FML update

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/Mixin#92]
[This commit](https://github.com/MinecraftForge/MinecraftForge/commit/c5a980f8a4fefd6403e3ebdf7b391d48227bc62c#diff-a2e39957fc7736049bbaa4ae6c58e4f7L101) renamed `getLoadedCoremods` to `getIgnoredMods`, breaking [`MixinLaunchAgentFML#loadAsMod`](https://github.com/SpongePowered/Mixin/blob/8c6be0e99c00d857f6c36fdb0f3bc29249a21d88/src/main/java/org/spongepowered/asm/launch/MixinLaunchAgentFML.java#L113). [Example crash](http://hastebin.com/cufesobavu.pas).

**Comment by darkevilmac** [comment]
Putting a post here so I know when it's fixed.

**Comment by JBYoshi** [comment]
@darkevilmac Just click “Subscribe” on the right side of the page.

**Comment by Mumfrey** [comment]
Seriously...
