### ISSUE TITLE
Mixin AP resolves incorrect target class for method reference

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#93]
**Note:** This is closely related to #33 which seems to have broken in the latest Mixin builds.

Basically in SpongeVanilla there are quite a few injections where Minecraft code is calling the methods on the current class (e.g. `DedicatedServer.loadAllWorlds` instead of `MinecraftServer.loadAllWorlds`) even though the method is only defined in one of the super classes. We fixed this back then by just looking into the hierarchy for finding the appropriate obfuscation mapping for the injections.

As far as I can tell this is generally still working fine, there is no problem with _finding the actual method mapping_. However, when writing to the refmap, instead of keeping the original defined target of the method call (e.g. here `DedicatedServer`) Mixin replaces the target owner of the method call with the owner defined in the mapping (`MinecraftServer`), so the injection will **never** match in production.

Here is an example:
```
Lnet/minecraft/server/dedicated/DedicatedServer;loadAllWorlds(Ljava/lang/String;Ljava/lang/String;JLnet/minecraft/world/WorldType;Ljava/lang/String;)V
```
Gets obfuscated to the refmap as:
```
Lnet/minecraft/server/MinecraftServer;func_71247_a(Ljava/lang/String;Ljava/lang/String;JLnet/minecraft/world/WorldType;Ljava/lang/String;)V
```
... instead of keeping the target owner of the method call which will prevent the injection from ever being successful in production.

For now I have fixed it [by doing the obfuscation manually and setting the correct injection target owner class](https://github.com/SpongePowered/SpongeVanilla/blob/master/src/main/java/org/spongepowered/server/mixin/server/MixinDedicatedServer.java#L80-L88), however it would be nice if we could get that somehow working again (it broke some other parts in SpongeVanilla too).

**Comment by Mumfrey** [comment]
Is this still broken as of `0.4.10`? I added specific handling for this case so either I misunderstand the problem or my fix didn't actually work.

**Comment by Mumfrey** [comment]
Actually looking back at my fix, I think I [only fixed this for fields references](https://github.com/SpongePowered/Mixin/commit/e2275d15e2e9c40a2dc7825614f7d1df4fc9ced3), so basically the same fix needs to be applied for methods too by the looks of it.
