### ISSUE TITLE
Annotation processor is not claiming all supported options

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#98]
**Note:** The option itself is working perfectly fine, this is just a very minor issue that the Mixin annotation processor doesn't claim the options for the extra SRG files.

When using the extra SRG file feature of Mixin the Java compiler will complain that these options weren't recognized by any processor, e.g.:
`warning: The following options were not recognized by any processor: '[reobfSrgFiles]'`

This is probably because you have added them to [`SupportedOptions`](https://github.com/SpongePowered/Mixin/blob/initphase/src/ap/java/org/spongepowered/tools/obfuscation/SupportedOptions.java#L35) but not to the [`SupportedOptions.all`](https://github.com/SpongePowered/Mixin/blob/initphase/src/ap/java/org/spongepowered/tools/obfuscation/SupportedOptions.java#L47-L58) set.

**Comment by Minecrell** [comment]
Thanks :)

**Comment by Mumfrey** [comment]
NP! :smile: It's only a warning message anyway :stuck_out_tongue:
