### ISSUE TITLE
@Redirect annotation specifies a target class which is not supported

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#99]
Still working on replacing the manual anonymous inner class mappings in SpongeVanilla with the refmap. Extra SRG files are read without problems, and on the first look the refmap looks fine as well:

```json
"org/spongepowered/common/mixin/core/MixinBootstrapAnonInner7": {
  "net/minecraft/init/Bootstrap$7": "net/minecraft/init/Bootstrap$14",
  "Lnet/minecraft/world/World;spawnEntityInWorld(Lnet/minecraft/entity/Entity;)Z": "Lnet/minecraft/world/World;func_72838_d(Lnet/minecraft/entity/Entity;)Z",
  "dispenseStack(Lnet/minecraft/dispenser/IBlockSource;Lnet/minecraft/item/ItemStack;)Lnet/minecraft/item/ItemStack;": "Lnet/minecraft/init/Bootstrap$7;func_82487_b(Lnet/minecraft/dispenser/IBlockSource;Lnet/minecraft/item/ItemStack;)Lnet/minecraft/item/ItemStack;"
}
```

However, if we look closely at this particular line:

`"dispenseStack(Lnet/minecraft/dispenser/IBlockSource;Lnet/minecraft/item/ItemStack;)Lnet/minecraft/item/ItemStack;": "Lnet/minecraft/init/Bootstrap$7;func_82487_b(Lnet/minecraft/dispenser/IBlockSource;Lnet/minecraft/item/ItemStack;)Lnet/minecraft/item/ItemStack;"`

... you'll notice it prepends **the original class name** in front of the `@Redirect` target which later causes the redirect to fail to apply at runtime ([full exception](https://gist.github.com/Minecrell/4e2ef4bb5706c139ea77#file-gistfile1-txt-L2)):

`@Redirect annotation on onSpawnEntityInWorld specifies a target class 'net/minecraft/init/Bootstrap$7', which is not supported`

For reference, mixin class is at https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/MixinBootstrapAnonInner7.java#L39-L49

**Comment by Mumfrey** [comment]
*Stop finding broken things! You're really messing with my mojo!*

No but seriously, ok I'll look into this. I think I know why it's happening.

**Comment by Mumfrey** [comment]
@Minecrell can you upload the extra srg file you're using.

**Comment by Minecrell** [comment]
@Mumfrey Here is it: https://github.com/SpongePowered/SpongeVanilla/blob/feature/anon-inner-srg/anon_inner_classes.srg

You can also checkout `feature/anon-inner-srg` on SpongeVanilla if you need something for testing (make sure the SpongeCommon submodule is up-to-date) although you will likely need to install SpongeGradle's `feature/anon-inner-srg` in the Maven local repository first.

Sorry for all the issues. :sob:

**Comment by Mumfrey** [comment]
Ok that will fix it for now. What really needs to happen is that when a second SRG file is loaded, it gets "applied" to existing mappings so that the stored mappings actually get updated with the new values. This is simpler to implement and will work for now, but I'll add it to my TODO list to actually apply the SRG files in a layered way rather than having to muck around doing remappings like this.

One drawback with this method is that it won't catch remapped class names which appear in method argument descriptors, but we'll cross that bridge if we ever come to it.

**Comment by Minecrell** [comment]
I wish I could tell you everything is working now; however I seem to have come across a completely different issue now independent to our anonymous inner class mappings, although I don't understand why this is happening now at all.

This time, our beloved failing injection is [`MixinEntityItemMinecart.implementCustomDerailedDeceleration`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/entity/item/MixinEntityMinecart.java#L48-L59) in SpongeCommon. Basically while previously the generated refmap for this mixin looked like this:

```json
"org/spongepowered/common/mixin/core/entity/item/MixinEntityMinecart": {
  "moveDerailedMinecart()V": "Lnet/minecraft/entity/item/EntityMinecart;func_180459_n()V",
  "Lnet/minecraft/entity/item/EntityMinecart;moveEntity(DDD)V": "Lnet/minecraft/entity/item/EntityMinecart;func_70091_d(DDD)V"
}
```

... for some reason it does now look like this:

```json
"org/spongepowered/common/mixin/core/entity/item/MixinEntityMinecart": {
  "moveDerailedMinecart()V": "Lnet/minecraft/entity/item/EntityMinecart;func_180459_n()V"
}
```

**Comment by Minecrell** [comment]
This seems to be directly related to your fix for this issue, if I revert to the previous version (before this commit, `0.4.17-20160126.141141-3`) it shows up in the refmap again. However, if I upgrade to the latest version (`0.4.17-20160126.173143-4`) it disappears.

**Comment by Minecrell** [comment]
(Sorry for the spam) One thing as a note, I think this is one of the methods from #93 where the actual method owner is different from the mapping owner, not sure if your commit broke something for that. However it does not affect **all** mappings of these type, because others (e.g. `DedicatedServer.loadAllWorlds` are present in the refmap.

**Comment by Mumfrey** [comment]
This will teach me to fix stuff in a hurry before I leave. I will look at it later. I had to change the way the lookups work to fix this so probably broke an assumption elsewhere, my guess would be that [this](https://github.com/SpongePowered/Mixin/blob/initphase/src/ap/java/org/spongepowered/tools/obfuscation/TargetObfuscationEnvironment.java#L204) may break it.

**Comment by Minecrell** [comment]
Your latest commit seems to fix all the issues, the server is launching fine now and all injections apply successfully. Thanks a lot for your effort and all these bug fixes! :)

Considering Mixin validates all injections with the required successful injection count, I think now that it works properly it should be safe to update SpongeCommon to use the latest version? Or do you have any other huge changes planned for this version?

**Comment by Mumfrey** [comment]
There's just one last thing I want to add before it's bumped, related to `@Final` and a discussion I had with @gabizou yesterday. But that's it, then it'll be good to go.

**Comment by Minecrell** [comment]
Awesome. Can you ping me once you have pushed that so I can merge my branch in SpongeVanilla and update it in SpongeCommon?

**Comment by Mumfrey** [comment]
@Minecrell ping :smile:
